function st_assert_cut_library_link_unchanged(before, cutPath, operation)
%ST_ASSERT_CUT_LIBRARY_LINK_UNCHANGED Reject Harness-induced link changes.

after = st_cut_library_link_state(cutPath);
if strcmp(before.StaticLinkStatus, after.StaticLinkStatus) && ...
        strcmp(before.ReferenceBlock, after.ReferenceBlock)
    return;
end

error('simtest:HarnessChangedLibraryLink', ...
    ['Harness operation changed the CUT library link. Do not save the ' ...
     'model; close it without saving and reopen the saved source. ' ...
     'Operation=%s | CUT=%s | Status=%s->%s | Reference=%s->%s'], ...
    char(string(operation)), char(string(cutPath)), ...
    before.StaticLinkStatus, after.StaticLinkStatus, ...
    before.ReferenceBlock, after.ReferenceBlock);
end
