function state = st_cut_library_link_state(cutPath)
%ST_CUT_LIBRARY_LINK_STATE Capture non-resolving library-link identity.

cutPath = char(string(cutPath));
state = struct( ...
    'CUTPath', cutPath, ...
    'StaticLinkStatus', char(string(get_param( ...
        cutPath, 'StaticLinkStatus'))), ...
    'ReferenceBlock', char(string(get_param( ...
        cutPath, 'ReferenceBlock'))), ...
    'IsLinked', false);
state.IsLinked = ~strcmpi(state.StaticLinkStatus, 'none') || ...
    ~isempty(state.ReferenceBlock);
end
