function R = st_create_harnesses(stageSelection)
%ST_CREATE_HARNESSES Create missing Harnesses from TestManagement.xlsx.
%
% Existing Harnesses are skipped.
% Harness creation uses normal compile mode.
%
% Progress:
%   Each target prints a START line and a result line through
%   st_log_progress. This is especially useful because
%   sltest.harness.create can take several minutes.

cfg = st_require_runtime_target();

T = st_load_targets( ...
    cfg.OnlyEnabled);

if nargin < 1
    stageSelection = [];
end
selection = st_normalize_stage_selection(T, stageSelection);

st_validate_clone_mapping(T, cfg);
n = height(T);

Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);
PreparationAction = selection.Action;
PreparationReason = selection.Reason;


totalTimer = tic;


st_log(cfg, 'INFO', 'Create Test Harnesses | Model=%s | Count=%d', ...
    cfg.TopModel, n);


for i = 1:n

    if ~selection.Run(i)
        Status(i) = 'CACHED';
        Message(i) = selection.Reason(i);
        Timestamp(i) = string(datetime('now', ...
            'Format', 'yyyy-MM-dd HH:mm:ss'));
        continue;
    end

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    timerValue = tic;
    linkState = [];

    st_log(cfg, 'DEBUG', ...
        '[HarnessCreate %d/%d] target resolved | CUT=%s | Harness=%s', ...
        i, n, ownerPath, harnessName);

    st_log_progress(cfg, i, n, 'START', harnessName, 'Detail', ownerPath);


    try

        st_log(cfg, 'TRACE', ...
            '[HarnessCreate %d/%d] getSimulinkBlockHandle start', ...
            i, n);

        blockHandle = ...
            getSimulinkBlockHandle( ...
                ownerPath);

        st_log(cfg, 'TRACE', ...
            '[HarnessCreate %d/%d] getSimulinkBlockHandle done | handle=%g', ...
            i, n, double(blockHandle));

        if blockHandle == -1

            error( ...
                'CUT not found: %s', ...
                ownerPath);
        end

        if ~strcmp( ...
                get_param(blockHandle, 'BlockType'), ...
                'SubSystem')

            error( ...
                'CUT is not a Subsystem: %s', ...
                ownerPath);
        end

        linkState = st_cut_library_link_state(ownerPath);


        st_log(cfg, 'DEBUG', ...
            '[HarnessCreate %d/%d] checking existing Harness', ...
            i, n);

        existing = ...
            sltest.harness.find( ...
                ownerPath, ...
                'SearchDepth', 0, ...
                'Name', harnessName);

        st_log(cfg, 'DEBUG', ...
            '[HarnessCreate %d/%d] existing Harness count=%d', ...
            i, n, numel(existing));

        if st_is_harness_clone(T(i,:))
            [cloneStatus, cloneMessage] = st_clone_template_harness(T(i,:), cfg);
            Status(i) = cloneStatus;
            Message(i) = cloneMessage;
        elseif ~isempty(existing)

            Status(i) = 'SKIP';
            Message(i) = 'Harness already exists';

        else

            synchronizationMode = 'SyncOnOpenAndClose';
            if linkState.IsLinked
                synchronizationMode = 'SyncOnOpen';
                st_log(cfg, 'WARN', ...
                    ['Library-linked CUT detected; creating Harness with ' ...
                     'SyncOnOpen to prevent close-time push | CUT=%s | ' ...
                     'Harness=%s'], ...
                    ownerPath, harnessName);
            end

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] forcing model stopped', ...
                i, n);

            st_force_model_stopped( ...
                cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                ['[HarnessCreate %d/%d] entering sltest.harness.create. ' ...
                 'This call can take several minutes.'], ...
                i, n);

            st_call_quiet(cfg, 'sltest.harness.create', ...
                @() sltest.harness.create( ...
                    ownerPath, ...
                    'Name', harnessName, ...
                    'Source', 'Signal Editor', ...
                    'Sink', 'Outport', ...
                    'AutoShapeInputs', false, ...
                    'SchedulerBlock', 'Test Sequence', ...
                    'SeparateAssessment', true, ...
                    'CreateWithoutCompile', false, ...
                    'VerificationMode', 'Normal', ...
                    'LogOutputs', false, ...
                    'RebuildOnOpen', false, ...
                    'RebuildModelData', false, ...
                    'SaveExternally', false, ...
                    'SynchronizationMode', synchronizationMode));

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] sltest.harness.create returned', ...
                i, n);

            st_log(cfg, 'TRACE', ...
                '[HarnessCreate %d/%d] verifying created Harness', ...
                i, n);


            created = ...
                sltest.harness.find( ...
                    ownerPath, ...
                    'SearchDepth', 0, ...
                    'Name', harnessName);

            if isempty(created)

                error( ...
                    'Harness not found after creation: %s', ...
                    harnessName);
            end

            st_assert_cut_library_link_unchanged( ...
                linkState, ownerPath, 'sltest.harness.create');


            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] save_system start', ...
                i, n);

            save_system( ...
                cfg.TopModel);

            st_log(cfg, 'DEBUG', ...
                '[HarnessCreate %d/%d] save_system done', ...
                i, n);

            Status(i) = 'OK';
            Message(i) = 'Harness created';
        end


    catch ME

        if ~isempty(linkState)
            try
                st_assert_cut_library_link_unchanged( ...
                    linkState, ownerPath, 'Harness creation failure path');
            catch linkError
                st_log(cfg, 'ERROR', ...
                    'Harness creation changed library link | CUT=%s | %s', ...
                    ownerPath, linkError.message);
                rethrow(linkError);
            end
        end

        if st_is_user_interrupt(ME)

            st_log(cfg, 'ERROR', ...
                'Harness creation terminated by user | %d/%d | %s', ...
                i, n, st_log_elapsed_text(toc(totalTimer)));

            rethrow(ME);
        end

        st_log(cfg, 'DEBUG', 'Harness creation failed | CUT=%s | Harness=%s | %s', ...
            ownerPath, harnessName, ME.message);
        Status(i) = 'FAIL';
        Message(i) = string(ME.message);
    end


    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', 'yyyy-MM-dd HH:mm:ss'));


    st_log(cfg, 'DEBUG', ...
        '[HarnessCreate %d/%d] finished | status=%s | elapsed=%.3f sec', ...
        i, n, char(Status(i)), ElapsedSec(i));

    st_log_progress(cfg, i, n, Status(i), harnessName, ...
        'Elapsed', ElapsedSec(i), 'Message', Message(i), 'Detail', ownerPath);
end


R = table( ...
    T.No, ...
    T.CUTName, ...
    T.CUTPath, ...
    T.HarnessName, ...
    PreparationAction, ...
    PreparationReason, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'CUTPath', ...
        'HarnessName', ...
        'PreparationAction', ...
        'PreparationReason', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});


st_write_result( ...
    'HarnessCreateResult', ...
    R);


end


function tf = st_is_user_interrupt(ME)

id = ...
    lower(char(string(ME.identifier)));

msg = ...
    lower(char(string(ME.message)));

% If Ctrl+C bypasses catch, MATLAB stops naturally. This branch handles
% internal operations that surface the user interrupt as an exception.
tf = ...
    contains(id, 'operationterminated') || ...
    contains(id, 'interrupted') || ...
    contains(msg, 'operation terminated by user') || ...
    contains(msg, 'terminated by user') || ...
    contains(msg, 'interrupted by user');

end
