function info = st_run_standalone_coverage_pipeline(varargin)
%ST_RUN_STANDALONE_COVERAGE_PIPELINE Run resumable standalone coverage stages.
%
% RunMode values:
%   STEP1      prepare Harness/input/Assessment/Test Manager without running
%   STEP234    export standalone Harness models, rewire copied TCs, run and
%              attach each generated CVF to its completed coverage result
%   STEP5      create portable CUT folders from a completed STEP234
%   STEP6      create the consolidated CoverageSummary.xlsx
%   STEP2_TO_6 run STEP234, STEP5, and STEP6 with one new PipelineId

p = inputParser;
p.FunctionName = mfilename;
addParameter(p, 'RunMode', '', @(x) ischar(x) || isstring(x));
addParameter(p, 'PipelineId', 'LATEST', @(x) ischar(x) || isstring(x));
addParameter(p, 'OutputRoot', '', @(x) ischar(x) || isstring(x));
addParameter(p, 'PreparationMode', 'AUTO', ...
    @(x) ischar(x) || isstring(x));
addParameter(p, 'FromStage', 'START', @(x) ischar(x) || isstring(x));
addParameter(p, 'ContinueOnFailure', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p, 'FailOnNonPass', false, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p, 'ReportMode', 'FULL', ...
    @(x) ismember(upper(string(x)), ["SUMMARY","FULL"]));
parse(p, varargin{:});

runMode = upper(strtrim(char(string(p.Results.RunMode))));
validModes = {'STEP1','STEP234','STEP5','STEP6','STEP2_TO_6'};
if isempty(runMode) || ~ismember(runMode, validModes)
    error('simtest:StandalonePipelineRunModeInvalid', ...
        'RunMode is required and must be one of: %s.', ...
        strjoin(validModes, ', '));
end
% STEP1 reuses the preparation workflow, whose existing contract loads the
% selected source model. All remaining modes operate on saved artifacts and
% must not load the source merely while resolving cfg: the bundle runner
% later loads an isolated copy with the same model name.
loadSourceModel = strcmp(runMode, 'STEP1');
cfg = st_require_runtime_target('LoadModel', loadSourceModel);
outputRoot = strtrim(char(string(p.Results.OutputRoot)));
if isempty(outputRoot), outputRoot = cfg.StandaloneCoverageRootDir; end
if ~isfolder(outputRoot), mkdir(outputRoot); end

timerValue = tic;
st_log(cfg, 'INFO', ...
    'Standalone coverage pipeline start | RunMode=%s | PipelineId=%s', ...
    runMode, char(string(p.Results.PipelineId)));
try
    switch runMode
        case 'STEP1'
            info = run_step1(p.Results, cfg);
        case 'STEP234'
            pipelineId = resolve_new_pipeline_id(p.Results.PipelineId, outputRoot);
            info = run_step234(outputRoot, pipelineId, p.Results, cfg);
        case 'STEP5'
            [manifest, manifestPath] = ...
                st_load_standalone_pipeline_manifest( ...
                outputRoot, p.Results.PipelineId);
            manifest = st_package_standalone_coverage_artifacts( ...
                outputRoot, manifest, p.Results.ReportMode);
            assert_source_unchanged(cfg, manifest.SourceBefore);
            manifestPath = st_write_standalone_pipeline_manifest( ...
                outputRoot, manifest);
            info = public_info(manifest, manifestPath);
        case 'STEP6'
            [manifest, manifestPath] = ...
                st_load_standalone_pipeline_manifest( ...
                outputRoot, p.Results.PipelineId);
            manifest = st_export_standalone_coverage_summary( ...
                outputRoot, manifest);
            assert_source_unchanged(cfg, manifest.SourceBefore);
            manifestPath = st_write_standalone_pipeline_manifest( ...
                outputRoot, manifest);
            info = public_info(manifest, manifestPath);
        case 'STEP2_TO_6'
            pipelineId = resolve_new_pipeline_id(p.Results.PipelineId, outputRoot);
            info = run_step234(outputRoot, pipelineId, p.Results, cfg);
            [manifest, ~] = st_load_standalone_pipeline_manifest( ...
                outputRoot, pipelineId);
            manifest = st_package_standalone_coverage_artifacts( ...
                outputRoot, manifest, p.Results.ReportMode);
            st_write_standalone_pipeline_manifest(outputRoot, manifest);
            manifest = st_export_standalone_coverage_summary( ...
                outputRoot, manifest);
            assert_source_unchanged(cfg, manifest.SourceBefore);
            manifestPath = st_write_standalone_pipeline_manifest( ...
                outputRoot, manifest);
            info = public_info(manifest, manifestPath);
    end
    st_log(cfg, 'INFO', ...
        'Standalone coverage pipeline complete | RunMode=%s | elapsed=%.3f sec', ...
        runMode, toc(timerValue));
catch ME
    if exist('manifest', 'var') && isstruct(manifest) && ...
            isfield(manifest, 'Steps') && ...
            ~strcmp(runMode, 'STEP234')
        manifest = record_active_stage_failure(manifest, ME);
        try
            st_write_standalone_pipeline_manifest(outputRoot, manifest);
        catch manifestME
            ME = addCause(ME, manifestME);
        end
    end
    st_log(cfg, 'ERROR', ...
        ['Standalone coverage pipeline failed | RunMode=%s | ' ...
         '%s: %s'], runMode, ME.identifier, ME.message);
    rethrow(ME);
end
end

function manifest = record_active_stage_failure(manifest, exception)
names = {'STEP6','STEP5','STEP234'};
for i = 1:numel(names)
    name = names{i};
    if isfield(manifest.Steps, name) && ...
            strcmpi(manifest.Steps.(name).Status, 'RUNNING')
        manifest.Steps.(name) = step_state('FAIL', ...
            sprintf('%s: %s', exception.identifier, exception.message));
        break;
    end
end
manifest.Status = 'FAIL';
manifest.UpdatedAt = timestamp_text();
end

function info = run_step1(options, cfg)
timerValue = tic;
st_log(cfg, 'INFO', 'Standalone coverage STEP1 start | prepare-only');
[~, ~, workflow, report] = st_run_from_harness( ...
    'PreparationMode', options.PreparationMode, ...
    'FromStage', options.FromStage, ...
    'ExecutionMode', 'PER_CUT', ...
    'ExecuteTests', false, ...
    'ContinueOnFailure', options.ContinueOnFailure, ...
    'FailOnNonPass', options.FailOnNonPass, ...
    'ReportMode', options.ReportMode);
info = struct( ...
    'PipelineId', '', ...
    'Manifest', '', ...
    'RunMode', 'STEP1', ...
    'PreparedOnly', true, ...
    'Workflow', workflow, ...
    'Report', report);
st_log(cfg, 'INFO', ...
    'Standalone coverage STEP1 complete | elapsed=%.3f sec', ...
    toc(timerValue));
end

function info = run_step234(outputRoot, pipelineId, options, cfg)
timerValue = tic;
pipelineRoot = fullfile(outputRoot, pipelineId);
mkdir(pipelineRoot);
mkdir(fullfile(pipelineRoot, 'logs'));
workRoot = fullfile(pipelineRoot, '.work');
mkdir(workRoot);
% Exporting straight into workRoot (instead of a nested "exports" folder)
% saves a path segment. The deep nesting st_export_test_bundle/
% st_export_standalone_harnesses build below this point (template/
% workspace/standalone/{CUTName}) can otherwise push a deeply nested
% project path past the Windows 260-character MAX_PATH limit.
exportRoot = workRoot;

st_log(cfg, 'INFO', ...
    'Standalone coverage STEP234 start | PipelineId=%s', pipelineId);
targets = st_load_targets(cfg.OnlyEnabled);
validate_pipeline_filter_policy(targets);
if ~strcmp(st_coverage_filter_existing_policy( ...
        cfg.CoverageFilterExistingPolicy), 'REPLACE')
    error('simtest:StandalonePipelineRequiresFilterReplacement', ...
        ['The pipeline must collect coverage without inherited filters. ' ...
         'Set cfg.CoverageFilterExistingPolicy to REPLACE.']);
end
assert_pipeline_source_unloaded(cfg, 'before standalone export');
source = source_snapshot(cfg);
manifest = initial_manifest(pipelineId, pipelineRoot, source, options);
manifest.Steps.STEP234 = step_state('RUNNING', 'Standalone export started');
manifestPath = st_write_standalone_pipeline_manifest(outputRoot, manifest);

try
    bundle = st_export_test_bundle( ...
        'Destination', exportRoot, ...
        'Profile', 'REPRODUCIBLE', ...
        'ExecutionModelMode', 'STANDALONE_HARNESS', ...
        'CreateArchive', false, ...
        'IncludeReferenceReport', false);
    assert_pipeline_source_unloaded(cfg, 'before bundle runner');
    manifest.BundleDirectory = bundle.BundleDirectory;
    manifest.BundleManifest = bundle.Manifest;
    manifest = checkpoint(outputRoot, manifest, 'STEP234', ...
        'RUNNING', 'Standalone bundle exported; executing copied Test File');

    execution = invoke_bundle_runner(bundle.BundleDirectory, options);
    manifest.ExecutionDirectory = execution.ExecutionDirectory;
    manifest.Workspace = execution.Workspace;
    manifest.PerCutRunDirectory = execution.Report.RunDirectory;
    sourceLog = fullfile(manifest.PerCutRunDirectory, ...
        'logs', 'execution.log');
    if isfile(sourceLog)
        manifest.ExecutionLog = fullfile(pipelineRoot, ...
            'logs', 'step234-execution.log');
        copyfile(sourceLog, manifest.ExecutionLog, 'f');
    end
    manifest.TestManagerWorkFile = fullfile( ...
        execution.Workspace, [cfg.TopModel '.mldatx']);
    manifest.Targets = build_target_state(bundle.Manifest, execution);
    assert_source_unchanged(cfg, source);
    manifest.SourceAfter = source_snapshot(cfg);
    manifest.Steps.STEP234 = step_state( ...
        step_status(manifest.Targets), ...
        'Standalone execution and required post-run CVF registration completed');
    manifest.Status = pipeline_status(manifest);
    manifest.UpdatedAt = timestamp_text();
    manifestPath = st_write_standalone_pipeline_manifest( ...
        outputRoot, manifest);
    info = public_info(manifest, manifestPath);
    st_log(cfg, 'INFO', ...
        ['Standalone coverage STEP234 complete | PipelineId=%s | ' ...
         'Targets=%d | elapsed=%.3f sec'], ...
        pipelineId, numel(manifest.Targets), toc(timerValue));
catch ME
    manifest.Steps.STEP234 = step_state('FAIL', ...
        sprintf('%s: %s', ME.identifier, ME.message));
    manifest.Status = 'FAIL';
    manifest.UpdatedAt = timestamp_text();
    st_write_standalone_pipeline_manifest(outputRoot, manifest);
    st_log(cfg, 'ERROR', ...
        'Standalone coverage STEP234 failed | %s: %s', ...
        ME.identifier, ME.message);
    rethrow(ME);
end
end

function assert_pipeline_source_unloaded(cfg, context)
%ASSERT_PIPELINE_SOURCE_UNLOADED Keep the source and replay copies isolated.
if ~bdIsLoaded(cfg.TopModel)
    st_log(cfg, 'DEBUG', ...
        'Standalone source isolation OK | Context=%s | Model=%s', ...
        context, cfg.TopModel);
    return;
end
dirtyText = '';
if strcmp(get_param(cfg.TopModel, 'Dirty'), 'on')
    dirtyText = ' It has unsaved changes; save or discard them first.';
end
st_log(cfg, 'ERROR', ...
    ['Standalone source isolation failed | Context=%s | Model=%s%s'], ...
    context, cfg.TopModel, dirtyText);
error('simtest:StandaloneModelStillLoadedBeforeRun', ...
    ['%s must be unloaded %s because the exported bundle loads its own ' ...
     'copy under the same model name.%s'], ...
    cfg.TopModel, context, dirtyText);
end

function execution = invoke_bundle_runner(bundleDirectory, options)
previousDirectory = pwd;
previousPath = path;
cleanup = onCleanup(@() restore_runner_environment( ...
    previousDirectory, previousPath)); %#ok<NASGU>
cd(bundleDirectory);
addpath(bundleDirectory, '-begin');
clear run_exported_tests;
execution = run_exported_tests( ...
    'ContinueOnFailure', options.ContinueOnFailure, ...
    'FailOnNonPass', options.FailOnNonPass, ...
    'ReportMode', options.ReportMode, ...
    'ResultFilterMode', 'POST_RUN_REQUIRED');
clear run_exported_tests;
end

function restore_runner_environment(previousDirectory, previousPath)
cd(previousDirectory);
path(previousPath);
clear run_exported_tests st_setup st_config st_project_root;
end

function targets = build_target_state(bundleManifestPath, execution)
bundleManifest = jsondecode(fileread(bundleManifestPath));
reportTargets = execution.Report.Targets;
if ~istable(reportTargets)
    error('simtest:StandalonePipelineRunReportInvalid', ...
        'PER_CUT execution did not return its Targets table.');
end
n = numel(bundleManifest.Targets);
targets = repmat(empty_target_state(), n, 1);
for i = 1:n
    source = bundleManifest.Targets(i);
    match = find(double(reportTargets.No) == double(source.No) & ...
        string(reportTargets.TestCaseName) == string(source.TestCaseName));
    if numel(match) ~= 1
        error('simtest:StandalonePipelineTargetMappingFailed', ...
            'Cannot map execution result for No=%g, TestCase=%s.', ...
            double(source.No), char(string(source.TestCaseName)));
    end
    row = reportTargets(match,:);
    targetDirectory = fileparts(char(row.TargetManifest));
    if logical(row.RerunPerformed)
        selectedDirectory = fullfile(targetDirectory, 'final');
        selectedLabel = 'FINAL';
    else
        selectedDirectory = fullfile(targetDirectory, 'initial');
        selectedLabel = 'INITIAL';
    end
    item = empty_target_state();
    item.Order = i;
    item.No = double(source.No);
    item.CUTName = char(string(source.CUTName));
    item.CUTPath = char(string(source.CUTPath));
    item.TestCaseName = char(string(source.TestCaseName));
    item.ExpectedUpdateMode = char(string(source.ExpectedUpdateMode));
    item.CoverageFilterMode = char(string(source.CoverageFilterMode));
    item.CoverageBoundaryMode = char(string(source.CoverageBoundaryMode));
    item.CoverageFilterAction = char(string(source.CoverageFilterAction));
    item.CoverageFilterRationale = ...
        char(string(source.CoverageFilterRationale));
    item.StandaloneModel = char(string(source.StandaloneModel));
    item.StandaloneCUTPath = char(string(source.StandaloneCUTPath));
    preparationMatch = find([execution.Preparation.No] == double(source.No));
    if numel(preparationMatch) ~= 1
        error('simtest:StandalonePipelinePreparationMappingFailed', ...
            'Cannot map standalone preparation readback for No=%g.', ...
            double(source.No));
    end
    preparation = execution.Preparation(preparationMatch);
    item.AssessmentBlock = char(string(preparation.AssessmentBlock));
    item.IterationSignature = char(string(preparation.IterationSignature));
    item.StandaloneModelFile = bundle_work_path( ...
        execution.Workspace, source.StandaloneModelFile);
    item.SignalEditorInput = bundle_work_path( ...
        execution.Workspace, source.SignalEditorInput);
    item.PerCutTargetDirectory = targetDirectory;
    item.SelectedResultDirectory = selectedDirectory;
    item.SelectedResultLabel = selectedLabel;
    item.CVFPath = char(string(row.CVFPath));
    item.ExecutionCVFPath = item.CVFPath;
    item.CVFSHA256 = char(string(row.CVFSHA256));
    item.CVFRuleCount = double(row.CVFRuleCount);
    item.InitialOutcome = char(string(row.InitialOutcome));
    item.FinalOutcome = char(string(row.FinalOutcome));
    item.RerunPerformed = logical(row.RerunPerformed);
    item.ResultFilterStatus = char(string(row.ResultFilterStatus));
    item.ResultFilterMode = char(string(row.ResultFilterMode));
    item.FilterRestoreStatus = char(string(row.FilterRestoreStatus));
    item.Step234Status = char(string(row.Status));
    item.Message = char(string(row.Message));
    if ~strcmp(item.ResultFilterMode, 'POST_RUN_REQUIRED') || ...
            ~strcmp(item.ResultFilterStatus, 'OK') || ...
            ~strcmp(item.FilterRestoreStatus, 'OK')
        item.Step234Status = 'FAIL';
        item.Message = 'Required result CVF registration or Test File restoration failed';
    end
    targets(i) = item;
end
end

function value = bundle_work_path(workspace, bundlePath)
value = char(string(bundlePath));
if isempty(value), return; end
native = strrep(value, '/', filesep);
prefix = ['template' filesep];
if startsWith(native, prefix)
    value = fullfile(workspace, char(extractAfter( ...
        string(native), strlength(prefix))));
end
end

function validate_pipeline_filter_policy(targets)
requiredColumns = {'CoverageFilterMode','CoverageBoundaryMode', ...
    'CoverageFilterAction','CoverageFilterRationale'};
missing = setdiff(requiredColumns, targets.Properties.VariableNames);
if ~isempty(missing)
    error('simtest:StandalonePipelineFilterPolicyMissing', ...
        'Targets is missing required coverage columns: %s.', ...
        strjoin(missing, ', '));
end
invalid = upper(strtrim(string(targets.CoverageFilterMode))) ~= "ALL_CONTENT" | ...
    upper(strtrim(string(targets.CoverageBoundaryMode))) ~= "CUT_ONLY" | ...
    upper(strtrim(string(targets.CoverageFilterAction))) ~= "EXCLUDE" | ...
    strlength(strtrim(string(targets.CoverageFilterRationale))) == 0;
if any(invalid)
    rows = strjoin(string(double(targets.No(invalid))), ', ');
    error('simtest:StandalonePipelineFilterPolicyInvalid', ...
        ['Every pipeline target requires ALL_CONTENT + CUT_ONLY + ' ...
         'EXCLUDE and a non-empty rationale. Invalid target No: %s'], ...
        char(rows));
end
end

function value = source_snapshot(cfg)
assert_saved_source(cfg);
value = struct( ...
    'Model', st_file_signature(cfg.ModelFile), ...
    'TestFile', st_file_signature(cfg.TestFile), ...
    'ManagementExcel', st_file_signature(cfg.ManagementExcel), ...
    'ModelDirty', model_dirty(cfg), ...
    'TestFileDirty', test_file_dirty(cfg), ...
    'HarnessInventory', harness_inventory(cfg));
end

function assert_saved_source(cfg)
files = {cfg.ModelFile, cfg.TestFile, cfg.ManagementExcel};
for i = 1:numel(files)
    if ~isfile(files{i})
        error('simtest:StandalonePipelineSourceMissing', ...
            'Required source file is missing: %s', files{i});
    end
end
if model_dirty(cfg)
    error('simtest:StandalonePipelineModelDirty', ...
        'Save the source model before starting the pipeline.');
end
if test_file_dirty(cfg)
    error('simtest:StandalonePipelineTestFileDirty', ...
        'Save the source Test File before starting the pipeline.');
end
end

function value = model_dirty(cfg)
value = false;
if bdIsLoaded(cfg.TopModel)
    value = strcmp(get_param(cfg.TopModel, 'Dirty'), 'on');
end
end

function value = test_file_dirty(cfg)
tf = sltest.testmanager.TestFile(cfg.TestFile);
value = isprop(tf, 'Dirty') && logical(tf.Dirty);
end

function inventory = harness_inventory(cfg)
loadedHere = ~bdIsLoaded(cfg.TopModel);
if loadedHere, load_system(cfg.ModelFile); end
cleanup = onCleanup(@() close_loaded_model(cfg.TopModel, loadedHere)); %#ok<NASGU>
items = sltest.harness.find(cfg.TopModel);
inventory = strings(numel(items),1);
for i = 1:numel(items)
    inventory(i) = string(items(i).ownerFullPath) + "|" + ...
        string(items(i).name);
end
inventory = cellstr(sort(inventory));
end

function close_loaded_model(model, loadedHere)
if loadedHere && bdIsLoaded(model), close_system(model, 0); end
end

function assert_source_unchanged(cfg, before)
after = source_snapshot(cfg);
fields = {'Model','TestFile','ManagementExcel'};
for i = 1:numel(fields)
    name = fields{i};
    if ~strcmpi(before.(name).SHA256, after.(name).SHA256)
        error('simtest:StandalonePipelineSourceChanged', ...
            'Source %s checksum changed during isolated execution.', name);
    end
end
if before.ModelDirty ~= after.ModelDirty || ...
        before.TestFileDirty ~= after.TestFileDirty || ...
        ~isequal(string(before.HarnessInventory), ...
        string(after.HarnessInventory))
    error('simtest:StandalonePipelineSourceStateChanged', ...
        'Source Dirty state or Harness inventory changed.');
end
end

function manifest = initial_manifest(id, root, source, options)
manifest = struct( ...
    'Version', 1, ...
    'PipelineId', id, ...
    'PipelineRoot', root, ...
    'Status', 'RUNNING', ...
    'CreatedAt', timestamp_text(), ...
    'UpdatedAt', timestamp_text(), ...
    'Options', struct( ...
        'ContinueOnFailure', logical(options.ContinueOnFailure), ...
        'FailOnNonPass', logical(options.FailOnNonPass), ...
        'ReportMode', upper(char(string(options.ReportMode)))), ...
    'SourceBefore', source, ...
    'SourceAfter', struct(), ...
    'BundleDirectory', '', ...
    'BundleManifest', '', ...
    'ExecutionDirectory', '', ...
    'Workspace', '', ...
    'PerCutRunDirectory', '', ...
    'ExecutionLog', '', ...
    'TestManagerWorkFile', '', ...
    'TestManagerFile', '', ...
    'TestManagerSHA256', '', ...
    'CoverageSummary', '', ...
    'Targets', repmat(empty_target_state(), 0, 1), ...
    'Steps', struct( ...
        'STEP234', step_state('NOT_RUN', ''), ...
        'STEP5', step_state('NOT_RUN', ''), ...
        'STEP6', step_state('NOT_RUN', '')));
end

function value = empty_target_state()
value = struct( ...
    'Order', 0, 'No', 0, 'CUTName', '', 'CUTPath', '', ...
    'TestCaseName', '', 'ExpectedUpdateMode', '', ...
    'CoverageFilterMode', '', 'CoverageBoundaryMode', '', ...
    'CoverageFilterAction', '', ...
    'CoverageFilterRationale', '', 'StandaloneModel', '', ...
    'StandaloneCUTPath', '', 'StandaloneModelFile', '', ...
    'AssessmentBlock', '', 'IterationSignature', '', ...
    'SignalEditorInput', '', 'PerCutTargetDirectory', '', ...
    'SelectedResultDirectory', '', 'SelectedResultLabel', '', ...
    'CVFPath', '', 'ExecutionCVFPath', '', ...
    'CVFSHA256', '', 'CVFRuleCount', 0, ...
    'InitialOutcome', '', 'FinalOutcome', '', 'RerunPerformed', false, ...
    'ResultFilterMode', '', 'ResultFilterStatus', '', ...
    'FilterRestoreStatus', '', ...
    'Step234Status', 'NOT_RUN', 'Step5Status', 'NOT_RUN', ...
    'Step6Status', 'NOT_RUN', 'Message', '', ...
    'OutputDirectory', '', 'TargetManifest', '', ...
    'PackagedStandaloneModel', '', 'PackagedInput', '', ...
    'PackagedStandaloneModelSHA256', '', ...
    'PackagedInputSHA256', '', ...
    'CoverageResult', '', 'TestReport', '', ...
    'CoverageResultSHA256', '', ...
    'MetricSnapshot', '', 'MetricSnapshotSHA256', '', ...
    'DecisionCovered', NaN, 'DecisionTotal', NaN, ...
    'DecisionPercentage', NaN, 'DecisionPercentageText', 'N/A', ...
    'ExecutionCovered', NaN, 'ExecutionTotal', NaN, ...
    'ExecutionPercentage', NaN, 'ExecutionPercentageText', 'N/A');
end

function manifest = checkpoint(root, manifest, step, status, message)
manifest.Steps.(step) = step_state(status, message);
manifest.UpdatedAt = timestamp_text();
st_write_standalone_pipeline_manifest(root, manifest);
end

function value = step_state(status, message)
value = struct('Status', status, 'Message', message, ...
    'UpdatedAt', timestamp_text());
end

function status = step_status(targets)
values = upper(string({targets.Step234Status}));
if any(values == "FAIL"), status = 'WARN'; else, status = 'OK'; end
end

function status = pipeline_status(manifest)
names = fieldnames(manifest.Steps);
values = strings(numel(names),1);
for i = 1:numel(names)
    values(i) = string(manifest.Steps.(names{i}).Status);
end
if any(values == "FAIL")
    status = 'FAIL';
elseif any(values == "WARN") || any(values == "NOT_RUN")
    status = 'WARN';
else
    status = 'OK';
end
end

function id = resolve_new_pipeline_id(requested, outputRoot)
id = strtrim(char(string(requested)));
if isempty(id) || strcmpi(id, 'LATEST')
    stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
    uuid = char(java.util.UUID.randomUUID());
    id = [stamp '_' uuid(1:8)];
end
if ~strcmp(id, st_export_safe_name(id)) || isfolder(fullfile(outputRoot, id))
    error('simtest:StandalonePipelineIdInvalid', ...
        'PipelineId is unsafe or already exists: %s', id);
end
end

function info = public_info(manifest, manifestPath)
info = struct( ...
    'PipelineId', char(string(manifest.PipelineId)), ...
    'Manifest', manifestPath, ...
    'TestManagerFile', char(string(manifest.TestManagerFile)), ...
    'Targets', manifest.Targets, ...
    'CoverageSummary', char(string(manifest.CoverageSummary)), ...
    'Status', char(string(manifest.Status)));
end

function value = timestamp_text()
value = char(datetime('now', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
end
