function rootDir = st_project_root()
%ST_PROJECT_ROOT Resolve the repository root from the root bootstrap file.

setupFile = which('st_setup');

if isempty(setupFile)
    error( ...
        'simtest:ProjectRootNotFound', ...
        ['Cannot locate st_setup.m. Open the repository root as the ' ...
         'MATLAB Current Folder and run st_setup first.']);
end

rootDir = fileparts(setupFile);

if ~isfile(fullfile(rootDir, 'VERSION.txt')) || ...
        ~isfolder(fullfile(rootDir, 'src'))
    error( ...
        'simtest:InvalidProjectRoot', ...
        'Resolved project root is invalid: %s', ...
        rootDir);
end
end
