function snapshot = st_create_verification_snapshot( ...
        cfg, destination, createArchive)
%ST_CREATE_VERIFICATION_SNAPSHOT Reuse the export collector as read-only snapshot.

if nargin < 3, createArchive = false; end
before = st_verification_source_inventory(cfg);
exportInfo = st_export_test_bundle( ...
    'Destination', destination, 'RunId', 'LATEST', ...
    'CreateArchive', logical(createArchive), ...
    'IncludeReferenceReport', false);
after = st_verification_source_inventory(cfg);

if height(before) ~= height(after) || ...
        ~isequal(before.Path, after.Path) || ...
        ~isequal(before.SHA256, after.SHA256)
    error('simtest:VerificationChangedSource', ...
        ['Creating an isolated verification snapshot changed a source ' ...
         'model, Test File, Excel, dependency, or input file.']);
end

snapshot = struct( ...
    'BundleId', exportInfo.BundleId, ...
    'Root', exportInfo.BundleDirectory, ...
    'Manifest', exportInfo.Manifest, ...
    'SourceInventory', before, ...
    'Archive', exportInfo.Archive);
end
