function checks = st_empty_verification_checks()
%ST_EMPTY_VERIFICATION_CHECKS Create the normalized verification table.

checks = table( ...
    strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    false(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    zeros(0,1), strings(0,1), strings(0,1), ...
    'VariableNames', { ...
    'CheckId','FeatureId','Profile','Target','Required','Status', ...
    'Message','EvidencePath','DurationSec','StartedAt','CompletedAt'});
end
