function row = st_verification_check( ...
        checkId, featureId, profile, target, required, status, message, ...
        evidencePath, durationSec, startedAt, completedAt)
%ST_VERIFICATION_CHECK Build one normalized verification result row.

if nargin < 8, evidencePath = ''; end
if nargin < 9, durationSec = 0; end
if nargin < 10, startedAt = ''; end
if nargin < 11, completedAt = ''; end

status = upper(strtrim(string(status)));
if ~ismember(status, ["PASS","FAIL","BLOCKED","SKIP","WARN"])
    error('simtest:InvalidVerificationStatus', ...
        'Unsupported verification status: %s', status);
end

row = table( ...
    string(checkId), string(featureId), string(profile), string(target), ...
    logical(required), status, string(message), string(evidencePath), ...
    double(durationSec), string(startedAt), string(completedAt), ...
    'VariableNames', { ...
    'CheckId','FeatureId','Profile','Target','Required','Status', ...
    'Message','EvidencePath','DurationSec','StartedAt','CompletedAt'});
end
