function catalog = st_verification_catalog()
%ST_VERIFICATION_CATALOG Map every supported feature to verification checks.

FeatureId = [ ...
    "CORE"; "CONFIG"; "TARGETS"; "PATHS"; "HARNESS"; "SLDV"; ...
    "SIGNAL_EDITOR"; "ASSESSMENT"; "TEST_MANAGER"; "EXECUTION"; ...
    "EXPECTED_UPDATE"; "CACHE"; "COVERAGE"; "REPORTING"; ...
    "EXPORT"; "STANDALONE_SUT"; "DIAGNOSTICS"; "GUI"];
FeatureName = [ ...
    "Bootstrap and unit regression"; ...
    "Configuration and management workbook"; ...
    "Runtime model and CUT validation"; ...
    "Subsystem inventory and path selection"; ...
    "Harness creation and configuration"; ...
    "SLDV OFF FILE and GENERATE"; ...
    "Signal Editor scenarios"; ...
    "Assessment mapping and verify actions"; ...
    "Test File cases and iterations"; ...
    "Test execution and enabled scope"; ...
    "Expected value APPLY and OFF"; ...
    "Incremental checkpoints and recovery"; ...
    "Decision and Execution coverage"; ...
    "Integrated reports and status"; ...
    "Reproducible bundle export and rerun"; ...
    "Exported Harness model SUT execution"; ...
    "Excel assessment and timing diagnostics"; ...
    "Interactive model path and visual checks"];
AutomatedCheckIds = [ ...
    "UNIT_SUITE,ENVIRONMENT"; ...
    "CONFIG_PATHS,MANAGEMENT_EXCEL"; ...
    "RUNTIME_TARGET,CURRENT_STRUCTURE"; ...
    "PATH_LOGIC"; ...
    "FIXTURE_HARNESS,CURRENT_HARNESS"; ...
    "FIXTURE_SLDV_GENERATE,FIXTURE_SLDV_FILE,SLDV_MANIFEST"; ...
    "FIXTURE_SIGNAL_EDITOR,CURRENT_SIGNAL_EDITOR"; ...
    "FIXTURE_ASSESSMENT,CURRENT_ASSESSMENT"; ...
    "FIXTURE_TEST_MANAGER,CURRENT_TEST_FILE"; ...
    "FIXTURE_EXECUTION,CURRENT_EXECUTION"; ...
    "FIXTURE_EXPECTED_UPDATE"; ...
    "FIXTURE_CACHE,WORKFLOW_STATE"; ...
    "FIXTURE_COVERAGE,CURRENT_COVERAGE"; ...
    "LATEST_REPORT,FIXTURE_REPORT"; ...
    "FIXTURE_EXPORT,EXPORT_MANIFEST"; ...
    "STANDALONE_STATIC"; ...
    "DIAGNOSTIC_STATIC"; ...
    "GUI_LOGIC"];
ManualCheckIds = [ ...
    ""; ""; ""; ...
    "MANUAL.SUBSYSTEM_EXCEL_INDENT,MANUAL.DUPLICATE_CUT_SELECTION"; ...
    ""; ""; ""; ""; ""; ""; ""; ""; ""; ...
    "MANUAL.REPORT_VISUAL"; ...
    ""; ""; "MANUAL.EXCEL_APPLICATION"; ...
    "MANUAL.MODEL_SELECTION,MANUAL.CUT_HIGHLIGHT"];

catalog = table(FeatureId, FeatureName, AutomatedCheckIds, ManualCheckIds);
end
