function report = st_write_verification_report( ...
        runDirectory, runId, options, checks, environment, ...
        features, manualEvidence, cfg)
%ST_WRITE_VERIFICATION_REPORT Write JSON, Excel, JUnit, manifest, and latest.

status = st_verification_overall_status(checks);
createdAt = timestamp_text();
jsonPath = fullfile(runDirectory, 'verification.json');
excelPath = fullfile(runDirectory, 'VerificationSummary.xlsx');
junitPath = fullfile(runDirectory, 'junit.xml');
environmentPath = fullfile(runDirectory, 'environment.json');
manifestPath = fullfile(runDirectory, 'manifest.json');

payload = struct( ...
    'Version', 1, 'RunId', runId, 'Status', char(status), ...
    'Profile', options.Profile, 'Target', options.Target, ...
    'CreatedAt', createdAt, 'Checks', table2struct(checks), ...
    'Features', table2struct(features), ...
    'Environment', table2struct(environment), ...
    'ManualEvidence', table2struct(manualEvidence));
write_json(jsonPath, payload);
write_json(environmentPath, struct( ...
    'Version', 1, 'MATLABRelease', version('-release'), ...
    'MATLABVersion', version(), ...
    'Products', table2struct(environment)));
st_write_verification_junit(junitPath, checks);

artifactPaths = {jsonPath; environmentPath; junitPath; ...
    fullfile(runDirectory, 'logs'); fullfile(runDirectory, 'evidence'); ...
    fullfile(runDirectory, 'workspace')};
artifactNames = {"verification.json"; "environment.json"; "junit.xml"; ...
    "logs"; "evidence"; "workspace"};
artifacts = empty_artifacts();
for i = 1:numel(artifactPaths)
    artifacts = [artifacts; artifact_row( ...
        artifactNames{i}, artifactPaths{i}, 'PASS', 'Created')]; %#ok<AGROW>
end
unitJunit = fullfile(runDirectory, 'logs', 'matlab-unit-junit.xml');
if isfile(unitJunit)
    artifacts = [artifacts; artifact_row( ...
        'matlab-unit-junit.xml', unitJunit, 'PASS', ...
        'Official MATLAB unit-test JUnit')];
end

try
    write_excel(excelPath, runId, status, options, checks, ...
        environment, features, manualEvidence, artifacts);
    artifacts = [artifacts; artifact_row( ...
        'VerificationSummary.xlsx', excelPath, 'PASS', 'Created')];
catch ME
    artifacts = [artifacts; artifact_row( ...
        'VerificationSummary.xlsx', excelPath, 'FAIL', ME.message)];
    checks = [checks; st_verification_check( ...
        'REPORT.EXCEL', 'REPORTING', options.Profile, options.Target, ...
        true, 'FAIL', ME.message)];
    status = st_verification_overall_status(checks);
    payload.Status = char(status);
    payload.Checks = table2struct(checks);
    write_json(jsonPath, payload);
    st_write_verification_junit(junitPath, checks);
end
artifacts = refresh_artifacts(artifacts);

manifest = struct( ...
    'Version', 1, 'RunId', runId, 'Status', char(status), ...
    'CreatedAt', createdAt, 'Artifacts', table2struct(artifacts));
write_json(manifestPath, manifest);

latest = struct( ...
    'Version', 1, 'RunId', runId, 'Status', char(status), ...
    'RunDirectory', runDirectory, 'Summary', excelPath, ...
    'JSON', jsonPath, 'JUnit', junitPath, 'Manifest', manifestPath, ...
    'UpdatedAt', timestamp_text());
if ~isfolder(cfg.VerificationRootDir)
    mkdir(cfg.VerificationRootDir);
end
write_json(fullfile(cfg.VerificationRootDir, 'latest.json'), latest);

report = struct( ...
    'RunId', runId, 'Status', char(status), ...
    'RunDirectory', runDirectory, 'Summary', excelPath, ...
    'JSON', jsonPath, 'JUnit', junitPath, 'Manifest', manifestPath, ...
    'Checks', checks, 'Artifacts', artifacts);
end

function write_excel(path, runId, status, options, checks, ...
        environment, features, manualEvidence, artifacts)
if isfile(path), delete(path); end
Metric = ["RunId"; "Status"; "Profile"; "Target"; ...
    "CreatedAt"; "Pass"; "Fail"; "Blocked"; "Skip"; "Warn"];
Value = [string(runId); string(status); string(options.Profile); ...
    string(options.Target); string(timestamp_text()); ...
    string(sum(checks.Status == "PASS")); ...
    string(sum(checks.Status == "FAIL")); ...
    string(sum(checks.Status == "BLOCKED")); ...
    string(sum(checks.Status == "SKIP")); ...
    string(sum(checks.Status == "WARN"))];
writetable(table(Metric, Value), path, 'Sheet', 'Overview');
writetable(features, path, 'Sheet', 'Features');
writetable(checks, path, 'Sheet', 'Checks');
writetable(environment, path, 'Sheet', 'Environment');
writetable(manualEvidence, path, 'Sheet', 'ManualEvidence');
writetable(artifacts, path, 'Sheet', 'Artifacts');
end

function write_json(path, value)
parent = fileparts(path);
if ~isfolder(parent), mkdir(parent); end
temporary = [tempname(parent) '.json'];
cleanup = onCleanup(@() delete_quiet(temporary)); %#ok<NASGU>
fileId = fopen(temporary, 'w', 'n', 'UTF-8');
if fileId < 0
    error('simtest:VerificationJsonWriteFailed', ...
        'Cannot write JSON: %s', path);
end
fileCleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', jsonencode(value, 'PrettyPrint', true));
clear fileCleanup;
[ok, message] = movefile(temporary, path, 'f');
if ~ok
    error('simtest:VerificationJsonWriteFailed', ...
        'Cannot replace %s: %s', path, message);
end
end

function delete_quiet(path)
if isfile(path), delete(path); end
end

function T = empty_artifacts()
T = table(strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), zeros(0,1), 'VariableNames', ...
    {'Artifact','Path','ArtifactStatus','Message','SHA256','Bytes'});
end

function row = artifact_row(name, path, status, message)
sha256 = "";
bytes = 0;
if isfile(path)
    signature = st_file_signature(path);
    sha256 = string(signature.SHA256);
    bytes = signature.Bytes;
end
row = table(string(name), string(path), string(status), ...
    string(message), sha256, bytes, 'VariableNames', ...
    {'Artifact','Path','ArtifactStatus','Message','SHA256','Bytes'});
end

function artifacts = refresh_artifacts(artifacts)
for i = 1:height(artifacts)
    refreshed = artifact_row(artifacts.Artifact(i), ...
        artifacts.Path(i), artifacts.ArtifactStatus(i), ...
        artifacts.Message(i));
    artifacts(i,:) = refreshed;
end
end

function value = timestamp_text()
value = char(datetime('now', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
end
