function R = st_configure_signal_editors(stageSelection)
%ST_CONFIGURE_SIGNAL_EDITORS Configure existing harness Signal Editor blocks.
% - OFF: rename and select the first scenario whenever Signal Editor exists.
% - FILE/GENERATE: import SLDV test cases or ordinary MAT Dataset variables
%   into a dedicated Signal Editor MAT file, persist the new Filename,
%   reopen the Harness, then select the imported UT_REQ scenario.
%
% Detailed checkpoints are controlled by cfg.VerboseLogging.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);
if nargin < 1
    stageSelection = [];
end
selection = st_normalize_stage_selection(T, stageSelection);
st_force_model_stopped(cfg.TopModel);

n = height(T);
SignalEditorBlock = strings(n,1);
DataFile = strings(n,1);
OldScenario = strings(n,1);
NewScenario = strings(n,1);
ScenarioCount = zeros(n,1);
Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);
PreparationAction = selection.Action;
PreparationReason = selection.Reason;

totalTimer = tic;

st_log(cfg, 'INFO', ...
    'Configure Signal Editor start | count=%d', ...
    n);

for i = 1:n

    if ~selection.Run(i)
        Status(i) = 'CACHED';
        Message(i) = selection.Reason(i);
        Timestamp(i) = string(datetime('now', ...
            'Format', 'yyyy-MM-dd HH:mm:ss'));
        continue;
    end

    ownerPath = ...
        st_normalize_cut_path( ...
            T.CUTPath(i), ...
            cfg.TopModel);

    harnessName = ...
        char(T.HarnessName(i));

    profile = st_get_sldv_profile(T(i,:), cfg);
    dataFileFormat = char(profile.DataFileFormat);
    scenarioNames = profile.ScenarioNames;
    scenarioName = scenarioNames{1};

    NewScenario(i) = ...
        string(strjoin(scenarioNames, ', '));

    ScenarioCount(i) = ...
        numel(scenarioNames);

    timerValue = tic;

    st_log(cfg, 'DEBUG', ...
        '[SignalEditor %d/%d] start | CUT=%s | Harness=%s | Scenario=%s', ...
        i, n, ownerPath, harnessName, scenarioName);

    try

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] force model stopped', ...
            i, n);

        st_force_model_stopped(cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load start', ...
            i, n);

        sltest.harness.load( ...
            ownerPath, ...
            harnessName);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] harness.load done', ...
            i, n);

        st_log(cfg, 'TRACE', ...
            '[SignalEditor %d/%d] locating Signal Editor block', ...
            i, n);

        try
            sigBlock = st_find_signal_editor_block(harnessName);
        catch findME
            if strcmp(profile.Mode, 'OFF') && ...
                    strcmp(findME.identifier, ...
                    'simtest:SignalEditorBlockMissing')
                st_close_harness_quiet(ownerPath, harnessName);
                Status(i) = 'SKIP_NO_SIGNAL_EDITOR';
                Message(i) = ...
                    'Harness has no Signal Editor block; input scenario omitted';
                ElapsedSec(i) = toc(timerValue);
                Timestamp(i) = string(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss'));
                st_log(cfg, 'WARN', ...
                    ['[SignalEditor %d/%d] input scenario omitted | ' ...
                     'CUT=%s | Harness=%s | reason=no Signal Editor block'], ...
                    i, n, ownerPath, harnessName);
                fprintf( ...
                    '[%d/%d] SKIP %s: no Signal Editor block\n', ...
                    i, n, char(T.CUTName(i)));
                st_log(cfg, 'INFO', ...
                    ['[SignalEditor %d/%d] complete | ' ...
                     'status=SKIP_NO_SIGNAL_EDITOR | elapsed=%.3f sec'], ...
                    i, n, ElapsedSec(i));
                continue;
            end
            rethrow(findME);
        end

        SignalEditorBlock(i) = ...
            string(sigBlock);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] block=%s', ...
            i, n, sigBlock);

        options = ...
            st_normalize_options( ...
                get_param( ...
                    sigBlock, ...
                    'options@ActiveScenario'));

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] scenario option count=%d', ...
            i, n, numel(options));

        if isempty(options)

            error( ...
                'Signal Editor has no scenario: %s', ...
                sigBlock);
        end

        oldName = char(get_param(sigBlock, 'ActiveScenario'));
        if isempty(oldName) || ~ismember(oldName, options)
            error('simtest:SignalEditorActiveScenarioInvalid', ...
                ['Signal Editor ActiveScenario is empty or unavailable. ' ...
                 'Active=%s | Available=[%s] | Block=%s'], ...
                oldName, strjoin(options, ', '), sigBlock);
        end

        OldScenario(i) = ...
            string(oldName);

        fileName = ...
            get_param( ...
                sigBlock, ...
                'Filename');

        matPath = ...
            st_resolve_data_file( ...
                fileName, ...
                cfg.TopModel);

        DataFile(i) = ...
            string(matPath);

        st_log(cfg, 'DEBUG', ...
            ['[SignalEditor %d/%d] data file=%s | ' ...
             'oldScenario=%s | newScenario=%s'], ...
            i, n, matPath, oldName, scenarioName);

        templateDatasets = {};

        if ~strcmp(profile.Mode, 'OFF') && strcmp(dataFileFormat, 'SLDV')

            % The Harness ActiveScenario is the runtime input contract.
            % It can contain upstream signals that are not direct CUT
            % Inports; those elements must survive every SLDV import.
            templateScenarioName = ...
                char(profile.HarnessScenarioName);

            if isempty(templateScenarioName)
                error( ...
                    ['SLDV profile is missing the Harness ActiveScenario. ' ...
                     'Run st_prepare_sldv_targets again.']);
            end

            templateMatPath = ...
                sldv_template_source_mat_path(matPath);

            templateScenarioNames = ...
                sldv_template_scenario_names( ...
                    templateMatPath, ...
                    templateScenarioName, ...
                    profile.OriginalNames, ...
                    profile.SourceIndices);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] loading Harness input template | ' ...
                 'scenarios=[%s] | file=%s'], ...
                i, n, strjoin(templateScenarioNames, ', '), ...
                templateMatPath);

            templateDatasets = cell(size(templateScenarioNames));
            for templateIndex = 1:numel(templateScenarioNames)
                templateDatasets{templateIndex} = ...
                    load_scenario_dataset( ...
                        templateMatPath, ...
                        templateScenarioNames{templateIndex});

                assert_dataset_matches_interface( ...
                    templateDatasets{templateIndex}, ...
                    profile.HarnessInputNames, ...
                    profile.HarnessInputTypes, ...
                    profile.HarnessInputDimensions, ...
                    sprintf( ...
                        'Harness template scenario %s', ...
                        templateScenarioNames{templateIndex}));
            end
        end

        if strcmp(profile.Mode, 'OFF')

            set_param( ...
                sigBlock, ...
                'SampleTime', ...
                cfg.SignalEditorSampleTime);

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] SampleTime applied=%s', ...
                i, n, cfg.SignalEditorSampleTime);

            if ~strcmp(oldName, scenarioName)

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] Simulink.data.connect start', ...
                    i, n);

                dc = ...
                    Simulink.data.connect( ...
                        matPath);

                vars = ...
                    who(dc);

                st_log(cfg, 'TRACE', ...
                    '[SignalEditor %d/%d] MAT variable count=%d', ...
                    i, n, numel(vars));

                if any(strcmp(vars, scenarioName))

                    error( ...
                        'Scenario already exists in MAT file: %s', ...
                        scenarioName);
                end

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] rename start: %s -> %s', ...
                    i, n, oldName, scenarioName);

                ok = ...
                    rename( ...
                        dc, ...
                        oldName, ...
                        scenarioName);

                if ~all(ok)

                    error( ...
                        ['Failed to rename Signal Editor scenario: ' ...
                         '%s -> %s'], ...
                        oldName, ...
                        scenarioName);
                end

                saveChanges(dc);

                st_log(cfg, 'DEBUG', ...
                    '[SignalEditor %d/%d] rename/saveChanges done', ...
                    i, n);
            end

        else

            if ~same_file( ...
                    matPath, ...
                    profile.SignalEditorDataFile)

                error( ...
                    ['Signal Editor data file changed after FILE preflight. ' ...
                     'Expected=%s, Actual=%s'], ...
                    profile.SignalEditorDataFile, ...
                    matPath);
            end

            % Close the Harness before replacing its linked MAT scenarios.
            % This avoids using a stale Signal Editor scenario cache after
            % the MAT-file content changes.
            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] closing Harness before ' ...
                 'FILE scenario import | Format=%s'], ...
                i, n, dataFileFormat);

            st_close_harness_quiet( ...
                ownerPath, ...
                harnessName);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] FILE scenario import start | ' ...
                 'Format=%s | file=%s'], ...
                i, n, dataFileFormat, profile.EffectiveDataFile);

            % Build and validate the complete Signal Editor MAT file before
            % linking it to the Harness.  In particular, do not use the
            % Simulink.data connector for this file: a connector can report
            % the requested workspace variable names while the resulting
            % MAT content is not a Signal Editor scenario source.
            targetMatPath = ...
                prepare_file_signal_editor_file( ...
                    cfg, ...
                    i, ...
                    n, ...
                    matPath, ...
                    dataFileFormat, ...
                    profile.EffectiveDataFile);

            ignoreUnexpectedSldvInputs = false;
            if isfield(profile, 'IgnoreUnexpectedSldvInputs')
                ignoreUnexpectedSldvInputs = ...
                    logical(profile.IgnoreUnexpectedSldvInputs);
            end

            if strcmp(dataFileFormat, 'MAT')
                replace_with_mat_scenarios( ...
                    cfg, i, n, targetMatPath, scenarioNames, ...
                    profile.EffectiveDataFile, profile.OriginalNames, ...
                    profile.HarnessInputNames, ...
                    profile.HarnessInputTypes, ...
                    profile.HarnessInputDimensions);
            else
                replace_with_sldv_scenarios( ...
                    cfg, ...
                    i, ...
                    n, ...
                    targetMatPath, ...
                    scenarioNames, ...
                    profile.EffectiveDataFile, ...
                    profile.SourceIndices, ...
                    templateDatasets, ...
                    profile.HarnessInputNames, ...
                    profile.HarnessInputTypes, ...
                    profile.HarnessInputDimensions, ...
                    ignoreUnexpectedSldvInputs);
            end

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] FILE scenario import/save done | ' ...
                 'Format=%s | count=%d | targetMAT=%s'], ...
                i, n, dataFileFormat, numel(scenarioNames), targetMatPath);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] reopening Harness with validated ' ...
                 'FILE MAT | Format=%s'], ...
                i, n, dataFileFormat);

            sltest.harness.load( ...
                ownerPath, ...
                harnessName);

            sigBlock = ...
                st_find_signal_editor_block( ...
                    harnessName);

            SignalEditorBlock(i) = ...
                string(sigBlock);

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] switching Signal Editor Filename | ' ...
                 '%s -> %s'], ...
                i, n, matPath, targetMatPath);

            set_param(sigBlock, 'Filename', targetMatPath);
            DataFile(i) = string(targetMatPath);

            % Filename-dependent parameters refresh only after a Harness
            % reload. Persist the filename after the MAT has passed its
            % standalone Signal Editor Dataset validation.
            save_system(cfg.TopModel);
            st_close_harness_quiet(ownerPath, harnessName);
            sltest.harness.load(ownerPath, harnessName);
            sigBlock = st_find_signal_editor_block(harnessName);
            SignalEditorBlock(i) = string(sigBlock);

            actualFilename = st_resolve_data_file( ...
                get_param(sigBlock, 'Filename'), cfg.TopModel);
            if ~same_file(actualFilename, targetMatPath)
                error(['Signal Editor Filename was not persisted. ' ...
                    'Expected=%s, Actual=%s'], targetMatPath, actualFilename);
            end

            importedOptions = ...
                st_normalize_options( ...
                    get_param( ...
                        sigBlock, ...
                        'options@ActiveScenario'));

            blockScenarioCount = signal_editor_scenario_count(sigBlock);

            missingImportedScenarios = ...
                scenarioNames(~ismember(scenarioNames, importedOptions));

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] imported scenario options=%d | ' ...
                 'NumberOfScenarios=%s | names=[%s]'], ...
                i, n, numel(importedOptions), blockScenarioCount, ...
                strjoin(importedOptions, ', '));

            if ~isempty(missingImportedScenarios)
                error( ...
                    ['Imported SLDV scenarios are not visible after saving ' ...
                     'and reopening the linked Signal Editor MAT file. ' ...
                     'Missing=[%s], Available=[%s], File=%s'], ...
                    strjoin(missingImportedScenarios, ', '), ...
                    strjoin(importedOptions, ', '), ...
                    targetMatPath);
            end

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] switching ActiveScenario before ' ...
                 'other block parameters | %s'], ...
                i, n, scenarioName);

            set_param( ...
                sigBlock, ...
                'ActiveScenario', ...
                scenarioName);

            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] ActiveScenario switched successfully', ...
                i, n);

            st_log(cfg, 'TRACE', ...
                '[SignalEditor %d/%d] applying SampleTime=%s', ...
                i, n, cfg.SignalEditorSampleTime);

            set_param( ...
                sigBlock, ...
                'SampleTime', ...
                cfg.SignalEditorSampleTime);

            st_log(cfg, 'TRACE', ...
                ['[SignalEditor %d/%d] applying ' ...
                 'OutputAfterFinalValue=Holding final value'], ...
                i, n);

            set_param( ...
                sigBlock, ...
                'OutputAfterFinalValue', ...
                'Holding final value');

            st_log(cfg, 'TRACE', ...
                ['[SignalEditor %d/%d] SampleTime=%s | ' ...
                 'OutputAfterFinalValue=Holding final value'], ...
                i, n, cfg.SignalEditorSampleTime);
        end

        % FILE/GENERATE selected the first UT_REQ scenario immediately
        % after the linked MAT refresh. OFF reaches this common point after
        % renaming the existing scenario, regardless of direct CUT Inports.
        if strcmp(profile.Mode, 'OFF')
            st_log(cfg, 'DEBUG', ...
                '[SignalEditor %d/%d] ActiveScenario set start | %s', ...
                i, n, scenarioName);

            set_param( ...
                sigBlock, ...
                'ActiveScenario', ...
                scenarioName);
        end

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] ActiveScenario set; save_system start', ...
            i, n);

        save_system( ...
            cfg.TopModel);

        st_log(cfg, 'DEBUG', ...
            '[SignalEditor %d/%d] save_system done; closing Harness', ...
            i, n);

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        if ~strcmp(profile.Mode, 'OFF')

            st_log(cfg, 'DEBUG', ...
                ['[SignalEditor %d/%d] old scenario cleanup skipped; ' ...
                 'validated SLDV MAT contains only UT_REQ scenarios'], ...
                i, n);
        end

        Status(i) = 'OK';

        if strcmp(profile.Mode, 'OFF')

            Message(i) = ...
                ['SampleTime=' cfg.SignalEditorSampleTime];

        else

            Message(i) = ...
                sprintf( ...
                    ['SampleTime=%s, scenarios=%d, ' ...
                     'Reader=Simulink.io.SLDVMatFile, ' ...
                     'OutputAfterFinalValue=Holding final value'], ...
                    cfg.SignalEditorSampleTime, ...
                    numel(scenarioNames));
        end

        fprintf( ...
            '[%d/%d] OK   %s -> %s\n', ...
            i, n, harnessName, scenarioName);

    catch ME

        st_close_harness_quiet( ...
            ownerPath, ...
            harnessName);

        Status(i) = 'FAIL';
        Message(i) = string(ME.message);

        st_log(cfg, 'ERROR', ...
            '[SignalEditor %d/%d] %s', ...
            i, n, ME.message);

        st_log_exception_details( ...
            cfg, ...
            i, ...
            n, ...
            ME);

        fprintf( ...
            '[%d/%d] FAIL %s: %s\n', ...
            i, n, harnessName, ME.message);
    end

    ElapsedSec(i) = ...
        toc(timerValue);

    Timestamp(i) = ...
        string(datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

    st_log(cfg, 'DEBUG', ...
        ['[SignalEditor %d/%d] finished | status=%s | ' ...
         'elapsed=%.3f sec | total=%.3f sec'], ...
        i, n, char(Status(i)), ...
        ElapsedSec(i), toc(totalTimer));
end

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.HarnessName, ...
    SignalEditorBlock, ...
    DataFile, ...
    OldScenario, ...
    NewScenario, ...
    ScenarioCount, ...
    PreparationAction, ...
    PreparationReason, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'HarnessName', ...
        'SignalEditorBlock', ...
        'DataFile', ...
        'OldScenario', ...
        'NewScenario', ...
        'ScenarioCount', ...
        'PreparationAction', ...
        'PreparationReason', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

st_write_result( ...
    'SignalEditorResult', ...
    R);

st_log(cfg, 'INFO', ...
    'Configure Signal Editor complete | elapsed=%.3f sec', ...
    toc(totalTimer));

end


function templateMatPath = sldv_template_source_mat_path(currentMatPath)
%SLDV_TEMPLATE_SOURCE_MAT_PATH Recover the stable pre-SLDV input template.
%
% A previous failed SLDV run can leave the block pointing at *_sldv.mat.
% That output intentionally contains only UT_REQ scenarios, so it must not
% be used as the next run's InputScenario template. Prefer its original
% sibling whenever it exists; otherwise retain the current path.

currentMatPath = char(currentMatPath);
[parentDir, baseName, extension] = fileparts(currentMatPath);
suffix = '_sldv';

if length(baseName) >= length(suffix) && ...
        strcmpi(baseName(end-length(suffix)+1:end), suffix)
    candidate = fullfile(parentDir, ...
        [baseName(1:end-length(suffix)) extension]);
    if isfile(candidate)
        templateMatPath = char(java.io.File(candidate).getCanonicalPath());
        return;
    end
end

templateMatPath = char(java.io.File(currentMatPath).getCanonicalPath());
end


function scenarioNames = sldv_template_scenario_names( ...
        matPath, preferredName, originalNames, sourceIndices)
%SLDV_TEMPLATE_SCENARIO_NAMES Select Dataset templates for SLDV scenarios.
%
% When a Harness already points at *_sldv.mat, its ActiveScenario is a
% UT_REQ name. The original sibling MAT is intentionally a stable input
% template and normally exposes InputScenario instead, so the prior active
% name cannot be required there. A manually imported SLDV template can
% instead contain TestCase_1, TestCase_2, ...; map those variables by the
% original SLDV source index so each scenario preserves its own external
% Harness-only inputs.

sourceIndices = double(sourceIndices(:));
variables = whos('-file', matPath);
variableNames = {variables.name};

candidateNames = variableNames;

validNames = {};
for i = 1:numel(candidateNames)
    candidateName = candidateNames{i};
    try
        loaded = load(matPath, candidateName);
        value = loaded.(candidateName);
        if isa(value, 'Simulink.SimulationData.Dataset') && ...
                isscalar(value) && value.numElements > 0
            validNames{end + 1} = candidateName; %#ok<AGROW>
        end
    catch
    end
end

scenarioNames = st_select_sldv_template_names( ...
    validNames, preferredName, originalNames, sourceIndices);
if ~isempty(scenarioNames)
    return;
end

normalizedOriginalNames = cellstr(string(originalNames(:)));
error(['Cannot choose a unique Signal Editor template scenario. ' ...
    'Preferred=%s, Original=[%s], SourceIndices=%s, Valid=[%s], File=%s'], ...
    preferredName, strjoin(normalizedOriginalNames, ', '), ...
    mat2str(sourceIndices.'), strjoin(validNames, ', '), matPath);
end


function targetMatPath = prepare_file_signal_editor_file( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        sourceMatPath, ...
        dataFileFormat, ...
        protectedInputPath)
%PREPARE_FILE_SIGNAL_EDITOR_FILE
% Select the MAT file that will become the Signal Editor block Filename.
%
% The actual content is written into a sibling temporary MAT file and only
% replaces this target after round-trip Dataset validation succeeds.
%
% On later runs, a file already ending in the format suffix is reused.
% The selected input file itself is never replaced.

sourceMatPath = ...
    char( ...
        java.io.File( ...
            char(sourceMatPath)).getCanonicalPath());

[sourceDir, sourceBase, sourceExt] = ...
    fileparts(sourceMatPath);

if isempty(sourceExt)
    sourceExt = '.mat';
end

suffix = ['_' lower(char(dataFileFormat))];

preparedSuffix = '_prepared';
hasFormatSuffix = length(sourceBase) >= length(suffix) && ...
    strcmpi(sourceBase(end-length(suffix)+1:end), suffix);
hasPreparedSuffix = length(sourceBase) >= length(preparedSuffix) && ...
    strcmpi(sourceBase(end-length(preparedSuffix)+1:end), preparedSuffix);

if (hasFormatSuffix || hasPreparedSuffix) && ...
        ~same_file(sourceMatPath, protectedInputPath)

    targetMatPath = ...
        sourceMatPath;

    st_log(cfg, 'TRACE', ...
        '[SignalEditor %d/%d] reusing FILE Signal Editor MAT=%s', ...
        targetIndex, targetCount, targetMatPath);

    return;
end

targetMatPath = ...
    fullfile( ...
        sourceDir, ...
        [sourceBase suffix sourceExt]);

targetMatPath = ...
    char( ...
        java.io.File( ...
            targetMatPath).getCanonicalPath());

if same_file(targetMatPath, protectedInputPath)
    [targetDir, targetBase, targetExt] = fileparts(targetMatPath);
    targetMatPath = char(java.io.File(fullfile(targetDir, ...
        [targetBase '_prepared' targetExt])).getCanonicalPath());
end

st_log(cfg, 'DEBUG', ...
    ['[SignalEditor %d/%d] preparing dedicated Signal Editor MAT | ' ...
     'source=%s | target=%s'], ...
    targetIndex, targetCount, ...
    sourceMatPath, targetMatPath);

if ~isfile(sourceMatPath)
    error('Source Signal Editor MAT file not found: %s', sourceMatPath);
end

end


function replace_with_sldv_scenarios( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        matPath, ...
        newScenarioNames, ...
        dataFile, ...
        sourceIndices, ...
        templateDatasets, ...
        harnessInputNames, ...
        harnessInputTypes, ...
        harnessInputDimensions, ...
        ignoreUnexpectedSldvInputs)
%REPLACE_WITH_SLDV_SCENARIOS
% Import sldvData through the official Simulink.io.SLDVMatFile reader, then
% write selected TestCase Datasets into the Signal Editor MAT file.
%
% sourceIndices refers to the original SLDV TestCases order recorded during
% st_prepare_sldv_targets.

if numel(newScenarioNames) ~= numel(sourceIndices)

    error( ...
        ['SLDV Scenario/source-index count mismatch. ' ...
         'Scenarios=%d, SourceIndices=%d'], ...
        numel(newScenarioNames), ...
        numel(sourceIndices));
end

if ~iscell(templateDatasets) || ...
        numel(templateDatasets) ~= numel(newScenarioNames)
    error( ...
        ['SLDV Scenario/template count mismatch. ' ...
         'Scenarios=%d, Templates=%d'], ...
        numel(newScenarioNames), numel(templateDatasets));
end

reader = ...
    Simulink.io.SLDVMatFile( ...
        dataFile);

st_log(cfg, 'TRACE', ...
    '[SignalEditor %d/%d] SLDVMatFile whos start', ...
    targetIndex, targetCount);

fileInfo = ...
    whos(reader);

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile test cases=%d', ...
    targetIndex, targetCount, numel(fileInfo));

if isempty(fileInfo)

    error( ...
        'Simulink.io.SLDVMatFile found no TestCases: %s', ...
        dataFile);
end

sourceIndices = ...
    double(sourceIndices(:));

if any(~isfinite(sourceIndices)) || ...
        any(sourceIndices < 1) || ...
        any(mod(sourceIndices, 1) ~= 0) || ...
        any(sourceIndices > numel(fileInfo))

    error( ...
        ['Invalid SLDV source indices for imported file. ' ...
         'SourceIndices=%s, AvailableTestCases=%d'], ...
        mat2str(sourceIndices.'), ...
        numel(fileInfo));
end

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile import() start', ...
    targetIndex, targetCount);

[imported, warningText] = ...
    import(reader);

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] SLDVMatFile import() returned', ...
    targetIndex, targetCount);

log_reader_warning( ...
    cfg, ...
    targetIndex, ...
    targetCount, ...
    warningText);

if ~isstruct(imported) || ...
        ~isfield(imported, 'Data')

    error( ...
        ['Unexpected Simulink.io.SLDVMatFile import result. ' ...
         'Expected a structure containing Data.']);
end

importedData = ...
    imported.Data;

if ~iscell(importedData)

    importedData = ...
        num2cell(importedData);
end

if numel(importedData) < numel(fileInfo)

    error( ...
        ['SLDVMatFile import returned fewer datasets than whos reported. ' ...
         'Imported=%d, Whos=%d'], ...
        numel(importedData), ...
        numel(fileInfo));
end

sourceNames = ...
    reader_source_names( ...
        imported, ...
        fileInfo);

datasets = ...
    cell(size(newScenarioNames));

for i = 1:numel(newScenarioNames)

    sourceIndex = ...
        sourceIndices(i);

    dataset = ...
        importedData{sourceIndex};

    if ~isa( ...
            dataset, ...
            'Simulink.SimulationData.Dataset')

        error( ...
            ['SLDVMatFile TestCase %d did not import as ' ...
             'Simulink.SimulationData.Dataset. Class=%s'], ...
            sourceIndex, ...
            class(dataset));
    end

    newName = ...
        newScenarioNames{i};

    dataset = ...
        merge_sldv_dataset_with_harness_template( ...
            dataset, ...
            templateDatasets{i}, ...
            harnessInputNames, ...
            ignoreUnexpectedSldvInputs);

    assert_dataset_matches_interface( ...
        dataset, ...
        harnessInputNames, ...
        harnessInputTypes, ...
        harnessInputDimensions, ...
        sprintf('Merged SLDV TestCase %d', sourceIndex));

    dataset.Name = ...
        newName;

    datasets{i} = ...
        dataset;

    st_log(cfg, 'TRACE', ...
        ['[SignalEditor %d/%d] SLDV source #%d (%s) ' ...
         '-> scenario=%s | elements=%d'], ...
        targetIndex, ...
        targetCount, ...
        sourceIndex, ...
        sourceNames{sourceIndex}, ...
        newName, ...
        dataset.numElements);
end

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] Signal Editor MAT write start | %s', ...
    targetIndex, targetCount, matPath);

write_signal_editor_scenario_mat( ...
    cfg, targetIndex, targetCount, matPath, newScenarioNames, datasets);

st_log(cfg, 'DEBUG', ...
    '[SignalEditor %d/%d] Signal Editor MAT write done', ...
    targetIndex, targetCount);

end


function replace_with_mat_scenarios( ...
        cfg, targetIndex, targetCount, matPath, newScenarioNames, ...
        dataFile, sourceVariableNames, harnessInputNames, ...
        harnessInputTypes, harnessInputDimensions)
%REPLACE_WITH_MAT_SCENARIOS Copy ordinary Dataset variables by exact name.
sourceVariableNames = cellstr(string(sourceVariableNames(:)));
if isempty(newScenarioNames) || ...
        numel(newScenarioNames) ~= numel(sourceVariableNames)
    error('simtest:MatScenarioCountMismatch', ...
        ['MAT Scenario/source-variable count mismatch. ' ...
         'Scenarios=%d, Variables=%d'], ...
        numel(newScenarioNames), numel(sourceVariableNames));
end

st_log(cfg, 'INFO', ...
    '[MAT] Signal Editor scenario copy start | File=%s | Variables=[%s]', ...
    dataFile, strjoin(sourceVariableNames, ', '));
datasets = cell(size(newScenarioNames));
for i = 1:numel(newScenarioNames)
    sourceName = sourceVariableNames{i};
    st_log(cfg, 'DEBUG', ...
        '[MAT %d/%d] Dataset load start | Variable=%s', ...
        i, numel(newScenarioNames), sourceName);
    loaded = load(dataFile, sourceName);
    st_log(cfg, 'DEBUG', ...
        '[MAT %d/%d] Dataset load end | Variable=%s', ...
        i, numel(newScenarioNames), sourceName);
    if ~isfield(loaded, sourceName)
        error('simtest:MatVariableMissing', ...
            'Prepared MAT Dataset variable is missing: %s', sourceName);
    end
    dataset = loaded.(sourceName);
    if ~isa(dataset, 'Simulink.SimulationData.Dataset') || ...
            ~isscalar(dataset) || dataset.numElements == 0
        error('simtest:MatVariableNotDataset', ...
            'Prepared MAT variable is not a nonempty scalar Dataset: %s', ...
            sourceName);
    end
    assert_dataset_matches_interface( ...
        dataset, harnessInputNames, harnessInputTypes, ...
        harnessInputDimensions, sprintf('MAT variable %s', sourceName));
    dataset.Name = newScenarioNames{i};
    datasets{i} = dataset;
    st_log(cfg, 'DEBUG', ...
        '[MAT %d/%d] Variable=%s -> scenario=%s | elements=%d', ...
        i, numel(newScenarioNames), sourceName, newScenarioNames{i}, ...
        dataset.numElements);
end
write_signal_editor_scenario_mat( ...
    cfg, targetIndex, targetCount, matPath, newScenarioNames, datasets);
st_log(cfg, 'INFO', ...
    '[MAT] Signal Editor scenario copy end | Count=%d | File=%s', ...
    numel(datasets), matPath);
end


function write_signal_editor_scenario_mat( ...
        cfg, targetIndex, targetCount, matPath, scenarioNames, datasets)
%WRITE_SIGNAL_EDITOR_SCENARIO_MAT Write ordinary scalar Dataset variables.
%
% Signal Editor reads normal MAT variables whose values are scalar
% Simulink.SimulationData.Dataset objects.  Use save instead of
% Simulink.data.connect so the file has the same representation as a MAT
% file authored from the Signal Editor UI.  Write a sibling temporary file,
% validate it by loading it back, then replace the target only on success.

if numel(scenarioNames) ~= numel(datasets) || isempty(scenarioNames)
    error('Signal Editor MAT writer requires one or more named Datasets.');
end

[parentDir, ~, ~] = fileparts(matPath);
if isempty(parentDir)
    parentDir = pwd;
end

if ~isfolder(parentDir)
    error('Signal Editor MAT output directory does not exist: %s', parentDir);
end

tempMatPath = [tempname(parentDir) '.mat'];
temporaryFile = onCleanup(@() delete_file_quiet(tempMatPath));

for i = 1:numel(scenarioNames)
    scenarioName = scenarioNames{i};
    dataset = datasets{i};
    assert_signal_editor_dataset(dataset, scenarioName, tempMatPath);

    payload = struct;
    payload.(scenarioName) = dataset;

    if i == 1
        save(tempMatPath, '-struct', 'payload');
    else
        save(tempMatPath, '-struct', 'payload', '-append');
    end
end

validate_signal_editor_scenario_mat( ...
    cfg, targetIndex, targetCount, tempMatPath, scenarioNames);

[moved, moveMessage] = movefile(tempMatPath, matPath, 'f');
if ~moved
    error(['Validated Signal Editor MAT could not replace the target. ' ...
        'Temporary=%s, Target=%s, Reason=%s'], ...
        tempMatPath, matPath, moveMessage);
end

validate_signal_editor_scenario_mat( ...
    cfg, targetIndex, targetCount, matPath, scenarioNames);
clear temporaryFile;
end


function validate_signal_editor_scenario_mat( ...
        cfg, targetIndex, targetCount, matPath, expectedScenarioNames)
%VALIDATE_SIGNAL_EDITOR_SCENARIO_MAT Fail before linking an invalid source.

fileVariables = whos('-file', matPath);
actualNames = {fileVariables.name};
missing = expectedScenarioNames(~ismember(expectedScenarioNames, actualNames));

st_log(cfg, 'DEBUG', ...
    ['[SignalEditor %d/%d] MAT round-trip variables | expected=[%s] | ' ...
     'actual=[%s] | file=%s'], ...
    targetIndex, targetCount, strjoin(expectedScenarioNames, ', '), ...
    strjoin(actualNames, ', '), matPath);

if ~isempty(missing)
    error(['Signal Editor MAT round-trip is missing scenario variables. ' ...
        'Missing=[%s], File=%s'], strjoin(missing, ', '), matPath);
end

for i = 1:numel(expectedScenarioNames)
    scenarioName = expectedScenarioNames{i};
    loaded = load(matPath, scenarioName);
    scenario = loaded.(scenarioName);
    assert_signal_editor_dataset(scenario, scenarioName, matPath);

    elementClasses = cell(scenario.numElements, 1);
    valueClasses = cell(scenario.numElements, 1);
    for elementIndex = 1:scenario.numElements
        element = scenario.getElement(elementIndex);
        elementClasses{elementIndex} = class(element);
        if isa(element, 'Simulink.SimulationData.Signal')
            valueClasses{elementIndex} = class(element.Values);
        else
            valueClasses{elementIndex} = class(element);
        end
    end

    st_log(cfg, 'DEBUG', ...
        ['[SignalEditor %d/%d] MAT round-trip scenario=%s | class=%s | ' ...
         'elements=%d | elementClasses=[%s] | valueClasses=[%s]'], ...
        targetIndex, targetCount, scenarioName, class(scenario), ...
        scenario.numElements, strjoin(elementClasses, ', '), ...
        strjoin(valueClasses, ', '));
end
end


function assert_signal_editor_dataset(dataset, scenarioName, matPath)
%ASSERT_SIGNAL_EDITOR_DATASET Validate the documented Signal Editor format.

if ~isa(dataset, 'Simulink.SimulationData.Dataset') || ~isscalar(dataset)
    error(['Signal Editor scenario must be a scalar ' ...
        'Simulink.SimulationData.Dataset. Scenario=%s, Class=%s, File=%s'], ...
        scenarioName, class(dataset), matPath);
end

if dataset.numElements == 0
    error('Signal Editor scenario has no input elements. Scenario=%s, File=%s', ...
        scenarioName, matPath);
end

dataset_element_names(dataset);

for elementIndex = 1:dataset.numElements
    element = dataset.getElement(elementIndex);
    value = element;
    if isa(element, 'Simulink.SimulationData.Signal')
        value = element.Values;
    end

    if ~(isa(value, 'timeseries') || isstruct(value))
        error(['Signal Editor scenario element must be a timeseries or ' ...
            'MATLAB struct. Scenario=%s, Element=%d, Class=%s, File=%s'], ...
            scenarioName, elementIndex, class(value), matPath);
    end
end
end


function countText = signal_editor_scenario_count(sigBlock)
%SIGNAL_EDITOR_SCENARIO_COUNT Log the block's independent scenario count.

try
    countText = char(string(get_param(sigBlock, 'NumberOfScenarios')));
catch ME
    countText = ['unavailable:' ME.identifier];
end
end


function delete_file_quiet(filePath)

if isfile(filePath)
    delete(filePath);
end
end


function dataset = load_scenario_dataset(matPath, scenarioName)
%LOAD_SCENARIO_DATASET Load one named Signal Editor scenario Dataset.

loaded = load(matPath, scenarioName);

if ~isfield(loaded, scenarioName)
    error( ...
        'Signal Editor scenario is missing from MAT file: %s', ...
        scenarioName);
end

dataset = loaded.(scenarioName);

if ~isa(dataset, 'Simulink.SimulationData.Dataset') || ...
        dataset.numElements == 0
    error( ...
        ['Signal Editor scenario must be a nonempty ' ...
         'Simulink.SimulationData.Dataset: %s'], ...
        scenarioName);
end

end


function merged = merge_sldv_dataset_with_harness_template( ...
        sldvDataset, ...
        templateDataset, ...
        harnessInputNames, ...
        ignoreUnexpectedSldvInputs)
%MERGE_SLDV_DATASET_WITH_HARNESS_TEMPLATE
% Build a Dataset in Harness input order. SLDV-provided elements replace
% matching template elements; every omitted external Harness input remains
% unchanged from the template scenario.

if ~isa(templateDataset, 'Simulink.SimulationData.Dataset') || ...
        templateDataset.numElements == 0
    error('Harness input template Dataset is empty or invalid.');
end

templateNames = dataset_element_names(templateDataset);
sldvNames = dataset_element_names(sldvDataset);
expectedNames = cellstr(string(harnessInputNames(:)));

if ~isequal(string(templateNames(:)), string(expectedNames(:)))
    error( ...
        ['Harness input template no longer matches the prepared SLDV ' ...
         'profile. Template=[%s], Expected=[%s]'], ...
        strjoin(templateNames, ', '), ...
        strjoin(expectedNames, ', '));
end

[selectedIndices, sldvNames] = ...
    st_select_sldv_input_indices( ...
        sldvNames, ...
        templateNames, ...
        ignoreUnexpectedSldvInputs);

selectedSldvDataset = Simulink.SimulationData.Dataset;
for i = 1:numel(selectedIndices)
    selectedSldvDataset = addElement( ...
        selectedSldvDataset, ...
        sldvDataset.getElement(selectedIndices(i)));
end

merged = Simulink.SimulationData.Dataset;

for templateIndex = 1:numel(templateNames)
    name = templateNames{templateIndex};
    sldvIndex = find(strcmp(sldvNames, name), 1, 'first');

    if isempty(sldvIndex)
        element = templateDataset.getElement(templateIndex);
    else
        element = selectedSldvDataset.getElement(sldvIndex);
    end

    merged = addElement(merged, element);
end

end


function assert_dataset_matches_interface( ...
        dataset, ...
        expectedNames, ...
        expectedTypes, ...
        expectedDimensions, ...
        label)
%ASSERT_DATASET_MATCHES_INTERFACE Validate names, order, types and dims.

[~, actualNames, actualTypes, actualDimensions] = ...
    st_dataset_signature(dataset);
expectedNames = cellstr(string(expectedNames(:)));

if numel(actualTypes) ~= numel(actualNames) || ...
        numel(actualDimensions) ~= numel(actualNames) || ...
        numel(expectedTypes) ~= numel(expectedNames) || ...
        numel(expectedDimensions) ~= numel(expectedNames)
    error(['%s interface metadata is incomplete. ' ...
        'Actual names/types/dims=%d/%d/%d, Expected=%d/%d/%d'], ...
        label, numel(actualNames), numel(actualTypes), ...
        numel(actualDimensions), numel(expectedNames), ...
        numel(expectedTypes), numel(expectedDimensions));
end

if ~isequal(string(actualNames(:)), string(expectedNames(:)))
    error( ...
        '%s input names/order mismatch. Actual=[%s], Expected=[%s]', ...
        label, ...
        strjoin(actualNames, ', '), ...
        strjoin(expectedNames, ', '));
end

for i = 1:numel(expectedNames)
    if ~strcmpi(actualTypes{i}, expectedTypes{i})
        error( ...
            '%s data type mismatch at input %d (%s). Actual=%s, Expected=%s', ...
            label, i, expectedNames{i}, actualTypes{i}, expectedTypes{i});
    end

    if ~st_signal_dimensions_match( ...
            actualDimensions{i}, expectedDimensions{i}, actualTypes{i})
        error( ...
            '%s dimensions mismatch at input %d (%s). Actual=%s, Expected=%s', ...
            label, i, expectedNames{i}, ...
            mat2str(actualDimensions{i}), mat2str(expectedDimensions{i}));
    end
end

end


function names = dataset_element_names(dataset)
[~, names] = st_dataset_signature(dataset);
end


function st_log_exception_details( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        ME)

if ~isempty(ME.identifier)

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Identifier=%s', ...
        targetIndex, targetCount, ME.identifier);
end

if ~isempty(ME.stack)

    top = ...
        ME.stack(1);

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Stack=%s:%d', ...
        targetIndex, targetCount, ...
        top.name, top.line);
end

for causeIndex = 1:numel(ME.cause)

    cause = ...
        ME.cause{causeIndex};

    st_log(cfg, 'ERROR', ...
        '[SignalEditor %d/%d] Cause #%d: %s', ...
        targetIndex, targetCount, ...
        causeIndex, cause.message);
end

end


function sourceNames = reader_source_names(imported, fileInfo)

sourceNames = ...
    cell(numel(fileInfo),1);

for i = 1:numel(fileInfo)

    try
        sourceNames{i} = ...
            char(fileInfo(i).name);
    catch
        sourceNames{i} = ...
            sprintf( ...
                'SLDV TestCase %d', ...
                i);
    end
end

% Different FileType documentation pages historically used Name/Names.
% Use either when provided, but do not depend on them for indexing.
if isfield(imported, 'Name')

    names = ...
        imported.Name;

elseif isfield(imported, 'Names')

    names = ...
        imported.Names;

else

    return;
end

if ischar(names)

    names = ...
        {names};

elseif isstring(names)

    names = ...
        cellstr(names(:));
end

if iscell(names) && ...
        numel(names) == numel(sourceNames)

    for i = 1:numel(names)

        if ~isempty(names{i})

            sourceNames{i} = ...
                char(string(names{i}));
        end
    end
end

end


function log_reader_warning( ...
        cfg, ...
        targetIndex, ...
        targetCount, ...
        warningText)

if isempty(warningText)
    return;
end

if iscell(warningText)

    warningText = ...
        strjoin( ...
            string(warningText(:)), ...
            ' | ');

else

    warningText = ...
        string(warningText);
end

warningText = ...
    strtrim(warningText);

if strlength(warningText) == 0
    return;
end

st_log(cfg, 'WARN', ...
    '[SignalEditor %d/%d] SLDVMatFile import warning: %s', ...
    targetIndex, ...
    targetCount, ...
    char(warningText));

end


function tf = same_file(a, b)

a = ...
    char( ...
        java.io.File( ...
            char(a)).getCanonicalPath());

b = ...
    char( ...
        java.io.File( ...
            char(b)).getCanonicalPath());

if ispc
    tf = strcmpi(a, b);
else
    tf = strcmp(a, b);
end

end


function st_close_harness_quiet(ownerPath, harnessName)

try
    sltest.harness.close( ...
        ownerPath, ...
        harnessName);
catch
end

end
