function options = st_parse_workflow_options(varargin)
%ST_PARSE_WORKFLOW_OPTIONS Parse optional workflow execution overrides.

p = inputParser;
p.FunctionName = 'Simulink Test workflow';
addParameter(p, 'PreparationMode', '', @(v) ischar(v) || isstring(v));
addParameter(p, 'FromStage', '', @(v) ischar(v) || isstring(v));
addParameter(p, 'ExecutionMode', '', @(v) ischar(v) || isstring(v));
addParameter(p, 'ContinueOnFailure', [], ...
    @(v) isempty(v) || (islogical(v) && isscalar(v)));
addParameter(p, 'ReportMode', '', @(v) ischar(v) || isstring(v));
addParameter(p, 'FailOnNonPass', [], ...
    @(v) isempty(v) || (islogical(v) && isscalar(v)));
addParameter(p, 'ExecuteTests', [], ...
    @(v) isempty(v) || (islogical(v) && isscalar(v)));
addParameter(p, 'StrictRestart', false, @(v) islogical(v) && isscalar(v));
parse(p, varargin{:});

options = struct();
options.PreparationMode = upper(strtrim(char(string( ...
    p.Results.PreparationMode))));
options.FromStage = upper(strtrim(char(string(p.Results.FromStage))));
options.ExecutionMode = upper(strtrim(char(string( ...
    p.Results.ExecutionMode))));
options.ContinueOnFailure = p.Results.ContinueOnFailure;
options.ReportMode = upper(strtrim(char(string(p.Results.ReportMode))));
options.FailOnNonPass = p.Results.FailOnNonPass;
options.ExecuteTests = p.Results.ExecuteTests;
options.StrictRestart = p.Results.StrictRestart;

if ~isempty(options.PreparationMode) && ...
        ~ismember(options.PreparationMode, {'AUTO','FORCE'})
    error('simtest:InvalidPreparationMode', ...
        'PreparationMode override must be AUTO or FORCE.');
end

% EXECUTE is not a preparation stage. It is the caller saying preparation is
% already done: no stage runs and the tests execute against what exists.
validStages = {'START','HARNESS','SLDV','HARNESS_CONFIG', ...
    'SIGNAL_EDITOR','ASSESSMENT','TEST_MANAGER','ALIGNMENT','EXECUTE'};
if strcmp(options.FromStage, 'COVERAGE_FILTER')
    error('simtest:RemovedPreparationStage', ...
        ['COVERAGE_FILTER is no longer a preparation stage. Coverage ' ...
         'filters are generated by whoever executes. Use TEST_MANAGER ' ...
         'to rebuild the Test File, or run the execution command.']);
end
if ~isempty(options.FromStage) && ...
        ~ismember(options.FromStage, validStages)
    error('simtest:InvalidPreparationFromStage', ...
        'Invalid FromStage override: %s', options.FromStage);
end

if strcmp(options.FromStage, 'EXECUTE') && isequal(options.ExecuteTests, false)
    error('simtest:ExecuteOnlyWithoutExecution', ...
        ['FromStage=EXECUTE exists to run the tests; it cannot be ' ...
         'combined with ExecuteTests=false.']);
end

if strcmp(options.ExecutionMode, 'AUTO')
    error('simtest:RemovedExecutionMode', ...
        ['AUTO is gone. It chose PER_CUT whenever a target carried a ' ...
         'coverage filter, which stopped being a reason once filters ' ...
         'moved to the artifact stage. Pass BATCH or PER_CUT.']);
end
if ~isempty(options.ExecutionMode) && ...
        ~ismember(options.ExecutionMode, {'BATCH','PER_CUT'})
    error('simtest:InvalidExecutionMode', ...
        'ExecutionMode override must be BATCH or PER_CUT.');
end
if ~isempty(options.ReportMode) && ...
        ~ismember(options.ReportMode, {'SUMMARY','FULL'})
    error('simtest:InvalidPerCutReportMode', ...
        'ReportMode override must be SUMMARY or FULL.');
end
end
