function inputs = st_stage_inputs(row, cfg)
%ST_STAGE_INPUTS Independent policy fingerprints (not downstream file hashes).
inputs = struct();
inputs.HARNESS = st_hash_value(struct('ModelFile',cfg.ModelFile, ...
    'CUTPath',char(row.CUTPath),'HarnessName',char(row.HarnessName)));
source = struct();
if row.SldvMode == "FILE"
    file = char(row.SldvDataFile);
    if ~isfile(file), file = fullfile(fileparts(cfg.ManagementExcel),file); end
    source = st_file_signature(file);
end
inputs.SLDV = st_hash_value(struct('Mode',char(row.SldvMode), ...
    'Format',char(row.DataFileFormat),'Variable',char(row.MatVariableName), ...
    'Source',source,'Resolution',cfg.SldvTmaxResolution, ...
    'AutoConvertAtomic',cfg.AutoConvertSldvTargetsToAtomic, ...
    'IgnoreUnexpectedInputs',cfg.IgnoreUnexpectedSldvInputs, ...
    'AllowSubsystemPathMismatch',cfg.AllowSldvSubsystemPathMismatch));
inputs.HARNESS_CONFIG = st_hash_value(cfg.HarnessStopTime);
inputs.SIGNAL_EDITOR = st_hash_value(cfg.SignalEditorSampleTime);
inputs.ASSESSMENT = st_hash_value(struct('Outports',cfg.VerifyHarnessOutportsOnly, ...
    'FirstBus',cfg.VerifyFirstBusElementOnly,'AtSample',cfg.VerifyAtSampleTimeOnly, ...
    'Sample',cfg.ExpectedValueSampleTime));
% Coverage filters have no preparation stage of their own. PERSIST writes
% them into the Test File, so the policy belongs to TEST_MANAGER.
inputs.TEST_MANAGER = st_hash_value(struct('File',cfg.TestFile, ...
    'Suite',cfg.TestSuiteName,'Case',char(row.TestCaseName), ...
    'Metrics',cfg.CoverageMetricSettings,'StructuralLevel',cfg.CoverageStructuralLevel, ...
    'Referenced',cfg.CoverageIncludeReferencedModels, ...
    'FilterMode',char(row.CoverageFilterMode), ...
    'FilterBoundary',char(row.CoverageBoundaryMode), ...
    'FilterAction',char(row.CoverageFilterAction), ...
    'FilterRationale',char(row.CoverageFilterRationale), ...
    'FilterExecution',cfg.ExecutionMode, ...
    'FilterApplication',cfg.CoverageFilterApplicationMode, ...
    'FilterExistingPolicy',cfg.CoverageFilterExistingPolicy));
inputs.ALIGNMENT = st_hash_value('SCENARIO_BINDINGS_V1');
end
