function profile = st_empty_sldv_profile()
%ST_EMPTY_SLDV_PROFILE Return the canonical SLDV profile schema.

profile = struct( ...
    'No', NaN, ...
    'CUTName', '', ...
    'CUTPath', '', ...
    'HarnessName', '', ...
    'TestCaseName', '', ...
    'Mode', 'OFF', ...
    'RequestedDataFile', '', ...
    'SourceDataFile', '', ...
    'EffectiveDataFile', '', ...
    'SignalEditorDataFile', '', ...
    'SldvRunStatus', NaN, ...
    'SldvRunMessage', '', ...
    'SldvRunElapsedSec', NaN, ...
    'ScenarioNames', {{}}, ...
    'SourceIndices', [], ...
    'OriginalNames', {{}}, ...
    'EndTimes', [], ...
    'RawTmax', NaN, ...
    'Tmax', NaN, ...
    'ParameterCounts', [], ...
    'InputNames', {{}}, ...
    'InputTypes', {{}}, ...
    'InputDimensions', {{}}, ...
    'HarnessScenarioName', '', ...
    'HarnessInputNames', {{}}, ...
    'HarnessInputTypes', {{}}, ...
    'HarnessInputDimensions', {{}}, ...
    'IgnoreUnexpectedSldvInputs', false, ...
    'SldvDrivenInputNames', {{}}, ...
    'PreservedHarnessInputNames', {{}}, ...
    'IgnoredSldvInputNames', {{}}, ...
    'SldvDrivenInputCount', 0, ...
    'PreservedHarnessInputCount', 0, ...
    'IgnoredSldvInputCount', 0, ...
    'AtomicAction', '', ...
    'Status', '', ...
    'Message', '', ...
    'ErrorMessage', '');
end
