function [R, ScenarioR] = st_prepare_sldv_targets(stageSelection)
%ST_PREPARE_SLDV_TARGETS Generate or validate per-target SLDV test data.
% The resulting manifest is consumed by all later workflow stages.
%
% SLDV input-interface validation uses the target Harness Signal Editor
% ActiveScenario Dataset as the source of truth. This is intentional:
% runtime Harness inputs can include upstream/external signals that are not
% represented as direct CUT Inport blocks.

cfg = st_require_runtime_target();
T = st_load_targets(cfg.OnlyEnabled);
if nargin < 1
    stageSelection = [];
end
selection = st_normalize_stage_selection(T, stageSelection);

if ~isfolder(cfg.SldvDir)
    mkdir(cfg.SldvDir);
end

if ~bdIsLoaded(cfg.TopModel)
    load_system(cfg.TopModel);
end
st_force_model_stopped(cfg.TopModel);

n = height(T);
profiles = repmat(empty_profile(), n, 1);

SourceDataFile = strings(n,1);
EffectiveDataFile = strings(n,1);
SldvRunStatus = nan(n,1);
SldvRunMessage = strings(n,1);
SldvRunElapsedSec = nan(n,1);
ScenarioCount = zeros(n,1);
RawTmax = nan(n,1);
Tmax = nan(n,1);
ParameterCount = zeros(n,1);
SldvDrivenInputs = strings(n,1);
PreservedHarnessInputs = strings(n,1);
IgnoredSldvInputs = strings(n,1);
SldvDrivenInputCount = zeros(n,1);
PreservedHarnessInputCount = zeros(n,1);
IgnoredSldvInputCount = zeros(n,1);
AtomicAction = strings(n,1);
Status = strings(n,1);
Message = strings(n,1);
ElapsedSec = zeros(n,1);
Timestamp = strings(n,1);
PreparationAction = selection.Action;
PreparationReason = selection.Reason;

scenarioTargetRow = zeros(0,1);
scenarioNo = zeros(0,1);
scenarioCUTName = strings(0,1);
scenarioMode = strings(0,1);
scenarioSourceIndex = zeros(0,1);
scenarioOriginalName = strings(0,1);
scenarioName = strings(0,1);
scenarioEndTime = zeros(0,1);
scenarioTmax = zeros(0,1);
scenarioParamCount = zeros(0,1);
scenarioStatus = strings(0,1);
scenarioMessage = strings(0,1);

fprintf('\n============================================\n');
fprintf('Prepare Simulink Design Verifier Data\n');
fprintf('============================================\n');

for i = 1:n
    timerValue = tic;
    ownerPath = st_normalize_cut_path(T.CUTPath(i), cfg.TopModel);
    mode = upper(strtrim(char(T.SldvMode(i))));
    if isempty(mode)
        mode = 'OFF';
    end

    profile = empty_profile();
    profile.No = double(T.No(i));
    profile.CUTName = char(T.CUTName(i));
    profile.CUTPath = ownerPath;
    profile.HarnessName = char(T.HarnessName(i));
    profile.TestCaseName = char(T.TestCaseName(i));
    profile.Mode = mode;
    profile.RequestedDataFile = char(T.SldvDataFile(i));
    profile.SourceDataFile = char(T.SldvDataFile(i));

    if ~selection.Run(i)
        try
            profile = st_get_sldv_profile(T(i,:), cfg);
            if ~isfield(profile, 'AtomicAction')
                profile.AtomicAction = 'UNKNOWN';
            end
            SourceDataFile(i) = string(profile_field( ...
                profile, 'SourceDataFile', ''));
            EffectiveDataFile(i) = string(profile_field( ...
                profile, 'EffectiveDataFile', ''));
            SldvRunStatus(i) = profile_field( ...
                profile, 'SldvRunStatus', NaN);
            SldvRunMessage(i) = string(profile_field( ...
                profile, 'SldvRunMessage', ''));
            SldvRunElapsedSec(i) = profile_field( ...
                profile, 'SldvRunElapsedSec', NaN);
            ScenarioCount(i) = numel(profile.ScenarioNames);
            RawTmax(i) = profile_field(profile, 'RawTmax', NaN);
            Tmax(i) = profile_field(profile, 'Tmax', NaN);
            parameterCounts = profile_field( ...
                profile, 'ParameterCounts', []);
            ParameterCount(i) = sum(parameterCounts);
            drivenNames = profile_field( ...
                profile, 'SldvDrivenInputNames', {});
            preservedNames = profile_field( ...
                profile, 'PreservedHarnessInputNames', {});
            ignoredNames = profile_field( ...
                profile, 'IgnoredSldvInputNames', {});
            SldvDrivenInputs(i) = string(strjoin(drivenNames, ', '));
            PreservedHarnessInputs(i) = ...
                string(strjoin(preservedNames, ', '));
            IgnoredSldvInputs(i) = string(strjoin(ignoredNames, ', '));
            SldvDrivenInputCount(i) = numel(drivenNames);
            PreservedHarnessInputCount(i) = numel(preservedNames);
            IgnoredSldvInputCount(i) = numel(ignoredNames);
            AtomicAction(i) = string(profile_field( ...
                profile, 'AtomicAction', 'UNKNOWN'));
            Status(i) = 'CACHED';
            Message(i) = selection.Reason(i);

            [scenarioTargetRow, scenarioNo, scenarioCUTName, ...
                scenarioMode, scenarioSourceIndex, scenarioOriginalName, ...
                scenarioName, scenarioEndTime, scenarioTmax, ...
                scenarioParamCount, scenarioStatus, scenarioMessage] = ...
                append_cached_scenarios(profile, i, T(i,:), ...
                    scenarioTargetRow, scenarioNo, scenarioCUTName, ...
                    scenarioMode, scenarioSourceIndex, ...
                    scenarioOriginalName, scenarioName, scenarioEndTime, ...
                    scenarioTmax, scenarioParamCount, scenarioStatus, ...
                    scenarioMessage);
        catch ME
            Status(i) = 'FAIL';
            Message(i) = "Cached SLDV profile is invalid: " + ...
                string(ME.message);
            profile.ErrorMessage = char(Message(i));
        end

        % CACHED is a stage-reporting state, not a runtime-profile state.
        % Keep the reusable manifest profile successful. Only cache lookup
        % failures are written back as failed profiles.
        if ~strcmp(Status(i), 'CACHED')
            profile.Status = char(Status(i));
            profile.Message = char(Message(i));
        end
        profiles(i) = profile;
        ElapsedSec(i) = toc(timerValue);
        Timestamp(i) = current_timestamp();
        fprintf('[%d/%d] %-6s %s | Mode=%s | %s\n', ...
            i, n, char(Status(i)), char(T.CUTName(i)), mode, ...
            char(Message(i)));
        continue;
    end

    try
        if ~ismember(mode, {'OFF','FILE','GENERATE'})
            error('SldvMode must be OFF, FILE, or GENERATE: %s', mode);
        end

        if strcmp(mode, 'OFF')
            profile.AtomicAction = 'NOT_APPLICABLE';
            AtomicAction(i) = string(profile.AtomicAction);
            profile.ScenarioNames = {st_scenario_name(T.CUTName(i), 1)};
            profile.SourceIndices = [];
            profile.EndTimes = [];
            profile.Tmax = NaN;
            profile.ParameterCounts = 0;

            ScenarioCount(i) = 1;
            ParameterCount(i) = 0;
            Status(i) = 'SKIP';
            Message(i) = 'Legacy single-scenario workflow';

        else
            profile.AtomicAction = ensure_atomic_sldv_cut(cfg, ownerPath);
            AtomicAction(i) = string(profile.AtomicAction);

            % Runtime input interface is defined by the target Harness
            % Signal Editor ActiveScenario, not by direct CUT Inport blocks.
            harnessInput = inspect_harness_input_interface( ...
                cfg, ownerPath, profile.HarnessName);

            profile.HarnessScenarioName = harnessInput.ScenarioName;
            profile.SignalEditorDataFile = harnessInput.DataFile;
            profile.HarnessInputNames = harnessInput.Names;
            profile.HarnessInputTypes = harnessInput.Types;
            profile.HarnessInputDimensions = harnessInput.Dimensions;

            st_log(cfg, 'DEBUG', ...
                '[SLDV %d/%d] Harness ActiveScenario=%s | inputs=[%s]', ...
                i, n, harnessInput.ScenarioName, ...
                strjoin(harnessInput.Names, ', '));

            if strcmp(mode, 'FILE')
                dataFile = resolve_sldv_data_file(T.SldvDataFile(i), cfg);
                SourceDataFile(i) = string(dataFile);
                profile.SourceDataFile = dataFile;
                meta = inspect_sldv_data( ...
                    dataFile, ownerPath, T.CUTName(i), ...
                    cfg.SldvTmaxResolution, harnessInput, ...
                    cfg.IgnoreUnexpectedSldvInputs);

                validate_harness_input_interface( ...
                    harnessInput, ...
                    meta.InputNames, ...
                    meta.InputTypes, ...
                    meta.InputDimensions, ...
                    cfg.IgnoreUnexpectedSldvInputs);

                effectiveFile = dataFile;
            else
                [effectiveFile, runStatus, runMessage, runElapsed, meta] = ...
                    generate_sldv_data( ...
                        cfg, T(i,:), ownerPath, harnessInput);

                SldvRunStatus(i) = runStatus;
                SldvRunMessage(i) = string(runMessage);
                SldvRunElapsedSec(i) = runElapsed;
                profile.SldvRunStatus = runStatus;
                profile.SldvRunMessage = runMessage;
                profile.SldvRunElapsedSec = runElapsed;

                if double(runStatus) ~= 1 || ...
                        isempty(effectiveFile) || ...
                        isempty(meta)

                    error( ...
                        'SLDV generation failed (status=%g): %s', ...
                        double(runStatus), ...
                        runMessage);
                end

                SourceDataFile(i) = string(effectiveFile);
                profile.SourceDataFile = effectiveFile;
            end

            profile.EffectiveDataFile = effectiveFile;
            profile.ScenarioNames = meta.ScenarioNames;
            profile.SourceIndices = meta.SourceIndices;
            profile.OriginalNames = meta.OriginalNames;
            profile.EndTimes = meta.EndTimes;
            profile.RawTmax = meta.RawTmax;
            profile.Tmax = meta.Tmax;
            profile.ParameterCounts = meta.ParameterCounts;
            profile.InputNames = meta.InputNames;
            profile.InputTypes = meta.InputTypes;
            profile.InputDimensions = meta.InputDimensions;
            profile.IgnoreUnexpectedSldvInputs = ...
                logical(cfg.IgnoreUnexpectedSldvInputs);
            profile.IgnoredSldvInputNames = meta.IgnoredInputNames;

            if ~isempty(meta.IgnoredInputNames)
                st_log( ...
                    cfg, ...
                    'WARN', ...
                    ['[SLDV %d/%d] ignoring inputs not present in Harness ' ...
                     'ActiveScenario | inputs=[%s]'], ...
                    i, ...
                    n, ...
                    strjoin(meta.IgnoredInputNames, ', '));
            end

            % An SLDV Dataset may omit inputs that are driven elsewhere in
            % the Harness.  The missing Harness scenario elements are kept
            % when the UT_REQ Dataset is assembled later.
            [sldvDrivenNames, preservedHarnessNames] = ...
                validate_harness_input_interface( ...
                    harnessInput, ...
                    meta.InputNames, ...
                    meta.InputTypes, ...
                    meta.InputDimensions, ...
                    cfg.IgnoreUnexpectedSldvInputs);

            profile.SldvDrivenInputNames = sldvDrivenNames;
            profile.PreservedHarnessInputNames = preservedHarnessNames;
            profile.SldvDrivenInputCount = numel(sldvDrivenNames);
            profile.PreservedHarnessInputCount = numel(preservedHarnessNames);
            profile.IgnoredSldvInputCount = numel(meta.IgnoredInputNames);
            SldvDrivenInputs(i) = string(strjoin(sldvDrivenNames, ', '));
            PreservedHarnessInputs(i) = ...
                string(strjoin(preservedHarnessNames, ', '));
            IgnoredSldvInputs(i) = ...
                string(strjoin(meta.IgnoredInputNames, ', '));
            SldvDrivenInputCount(i) = numel(sldvDrivenNames);
            PreservedHarnessInputCount(i) = numel(preservedHarnessNames);
            IgnoredSldvInputCount(i) = numel(meta.IgnoredInputNames);

            EffectiveDataFile(i) = string(effectiveFile);
            ScenarioCount(i) = numel(meta.ScenarioNames);
            RawTmax(i) = meta.RawTmax;
            Tmax(i) = meta.Tmax;
            ParameterCount(i) = sum(meta.ParameterCounts);
            Status(i) = 'OK';
            Message(i) = sprintf( ...
                ['scenarios=%d, RawTmax=%.17g, Tmax=%.17g, ' ...
                 'sldvInputs=%d, ' ...
                 'preservedHarnessInputs=%d, ignoredSldvInputs=%d'], ...
                ScenarioCount(i), ...
                meta.RawTmax, ...
                meta.Tmax, ...
                SldvDrivenInputCount(i), ...
                PreservedHarnessInputCount(i), ...
                IgnoredSldvInputCount(i));

            for k = 1:numel(meta.ScenarioNames)
                scenarioTargetRow(end+1,1) = i; %#ok<AGROW>
                scenarioNo(end+1,1) = double(T.No(i)); %#ok<AGROW>
                scenarioCUTName(end+1,1) = string(T.CUTName(i)); %#ok<AGROW>
                scenarioMode(end+1,1) = string(mode); %#ok<AGROW>
                scenarioSourceIndex(end+1,1) = meta.SourceIndices(k); %#ok<AGROW>
                scenarioOriginalName(end+1,1) = string(meta.OriginalNames{k}); %#ok<AGROW>
                scenarioName(end+1,1) = string(meta.ScenarioNames{k}); %#ok<AGROW>
                scenarioEndTime(end+1,1) = meta.EndTimes(k); %#ok<AGROW>
                scenarioTmax(end+1,1) = meta.Tmax; %#ok<AGROW>
                scenarioParamCount(end+1,1) = meta.ParameterCounts(k); %#ok<AGROW>
                scenarioStatus(end+1,1) = 'OK'; %#ok<AGROW>
                scenarioMessage(end+1,1) = ''; %#ok<AGROW>
            end
        end

    catch ME
        Status(i) = 'FAIL';
        Message(i) = string(ME.message);
        profile.ErrorMessage = ME.message;

        st_log( ...
            cfg, ...
            'ERROR', ...
            '[SLDV %d/%d] %s', ...
            i, ...
            n, ...
            ME.message);
    end

    profile.Status = char(Status(i));
    profile.Message = char(Message(i));
    profiles(i) = profile;
    ElapsedSec(i) = toc(timerValue);
    Timestamp(i) = current_timestamp();

    fprintf( ...
        '[%d/%d] %-4s %s | Mode=%s | %s\n', ...
        i, ...
        n, ...
        char(Status(i)), ...
        char(T.CUTName(i)), ...
        mode, ...
        char(Message(i)));
end

% Signal Editor MAT ownership is checked only after every target data file
% has passed its source-side validation. This stage does not modify models.
checkSharedSignalEditorDataFile = ...
    isfield(cfg, 'CheckSharedSignalEditorDataFile') && ...
    logical(cfg.CheckSharedSignalEditorDataFile);

executedSldvRows = selection.Run & ~strcmp(T.SldvMode, 'OFF');
if ~any(Status == 'FAIL') && ...
        any(executedSldvRows) && ...
        checkSharedSignalEditorDataFile
    usersReady = false;

    try
        users = collect_signal_editor_data_users(cfg);
        usersReady = true;

    catch ME
        users = [];
        affected = find(executedSldvRows);

        for j = affected(:).'
            [Status, Message, profiles, scenarioStatus, scenarioMessage] = ...
                mark_target_failure( ...
                    j, ...
                    ME.message, ...
                    Status, ...
                    Message, ...
                    profiles, ...
                    scenarioTargetRow, ...
                    scenarioStatus, ...
                    scenarioMessage);
        end
    end

    if usersReady
        for i = find(executedSldvRows).'
            try
                [matPath, matchingUsers] = ...
                    target_signal_editor_data_file( ...
                        users, ...
                        profiles(i).CUTPath, ...
                        profiles(i).HarnessName);

                profiles(i).SignalEditorDataFile = matPath;

                if numel(matchingUsers) > 1
                    error( ...
                        ['Signal Editor MAT file is shared by multiple ' ...
                         'harnesses: %s | %s'], ...
                        matPath, ...
                        strjoin(matchingUsers, ', '));
                end

            catch ME
                [Status, Message, profiles, scenarioStatus, scenarioMessage] = ...
                    mark_target_failure( ...
                        i, ...
                        ME.message, ...
                        Status, ...
                        Message, ...
                        profiles, ...
                        scenarioTargetRow, ...
                        scenarioStatus, ...
                        scenarioMessage);
            end
        end
    end

elseif ~any(Status == 'FAIL') && any(executedSldvRows)
    st_log(cfg, 'INFO', ...
        ['Signal Editor MAT sharing check skipped ' ...
         '(cfg.CheckSharedSignalEditorDataFile=false)']);
end

manifest = struct();
manifest.Version = 4;
manifest.TopModel = cfg.TopModel;
manifest.ManagementExcel = cfg.ManagementExcel;
manifest.CreatedAt = char(current_timestamp());
manifest.Profiles = profiles;
save_manifest_atomic(cfg.SldvManifestFile, manifest);

R = table( ...
    T.No, ...
    T.CUTName, ...
    T.CUTPath, ...
    T.HarnessName, ...
    T.TestCaseName, ...
    T.SldvMode, ...
    SourceDataFile, ...
    EffectiveDataFile, ...
    SldvRunStatus, ...
    SldvRunMessage, ...
    SldvRunElapsedSec, ...
    ScenarioCount, ...
    RawTmax, ...
    Tmax, ...
    ParameterCount, ...
    SldvDrivenInputs, ...
    PreservedHarnessInputs, ...
    IgnoredSldvInputs, ...
    SldvDrivenInputCount, ...
    PreservedHarnessInputCount, ...
    IgnoredSldvInputCount, ...
    AtomicAction, ...
    PreparationAction, ...
    PreparationReason, ...
    Status, ...
    Message, ...
    ElapsedSec, ...
    Timestamp, ...
    'VariableNames', { ...
        'No', ...
        'CUTName', ...
        'CUTPath', ...
        'HarnessName', ...
        'TestCaseName', ...
        'SldvMode', ...
        'SourceDataFile', ...
        'EffectiveDataFile', ...
        'SldvRunStatus', ...
        'SldvRunMessage', ...
        'SldvRunElapsedSec', ...
        'ScenarioCount', ...
        'RawTmax', ...
        'Tmax', ...
        'ParameterCount', ...
        'SldvDrivenInputs', ...
        'PreservedHarnessInputs', ...
        'IgnoredSldvInputs', ...
        'SldvDrivenInputCount', ...
        'PreservedHarnessInputCount', ...
        'IgnoredSldvInputCount', ...
        'AtomicAction', ...
        'PreparationAction', ...
        'PreparationReason', ...
        'Status', ...
        'Message', ...
        'ElapsedSec', ...
        'Timestamp'});

ScenarioR = table( ...
    scenarioTargetRow, ...
    scenarioNo, ...
    scenarioCUTName, ...
    scenarioMode, ...
    scenarioSourceIndex, ...
    scenarioOriginalName, ...
    scenarioName, ...
    scenarioEndTime, ...
    scenarioTmax, ...
    scenarioParamCount, ...
    scenarioStatus, ...
    scenarioMessage, ...
    'VariableNames', { ...
        'TargetRow', ...
        'No', ...
        'CUTName', ...
        'SldvMode', ...
        'SourceIndex', ...
        'OriginalName', ...
        'ScenarioName', ...
        'OriginalEndTime', ...
        'Tmax', ...
        'ParameterCount', ...
        'Status', ...
        'Message'});

st_write_result('SldvGenerationResult', R);
st_write_result('SldvScenarioResult', ScenarioR);

end


function profile = empty_profile()

profile = struct( ...
    'No', NaN, ...
    'CUTName', '', ...
    'CUTPath', '', ...
    'HarnessName', '', ...
    'TestCaseName', '', ...
    'Mode', 'OFF', ...
    'RequestedDataFile', '', ...
    'SourceDataFile', '', ...
    'EffectiveDataFile', '', ...
    'SignalEditorDataFile', '', ...
    'SldvRunStatus', NaN, ...
    'SldvRunMessage', '', ...
    'SldvRunElapsedSec', NaN, ...
    'ScenarioNames', {{}}, ...
    'SourceIndices', [], ...
    'OriginalNames', {{}}, ...
    'EndTimes', [], ...
    'RawTmax', NaN, ...
    'Tmax', NaN, ...
    'ParameterCounts', [], ...
    'InputNames', {{}}, ...
    'InputTypes', {{}}, ...
    'InputDimensions', {{}}, ...
    'HarnessScenarioName', '', ...
    'HarnessInputNames', {{}}, ...
    'HarnessInputTypes', {{}}, ...
    'HarnessInputDimensions', {{}}, ...
    'IgnoreUnexpectedSldvInputs', false, ...
    'SldvDrivenInputNames', {{}}, ...
    'PreservedHarnessInputNames', {{}}, ...
    'IgnoredSldvInputNames', {{}}, ...
    'SldvDrivenInputCount', 0, ...
    'PreservedHarnessInputCount', 0, ...
    'IgnoredSldvInputCount', 0, ...
    'AtomicAction', '', ...
    'Status', '', ...
    'Message', '', ...
    'ErrorMessage', '');

end


function [status, message, profiles, scenarioStatus, scenarioMessage] = ...
        mark_target_failure( ...
            targetIndex, ...
            errorMessage, ...
            status, ...
            message, ...
            profiles, ...
            scenarioTargetRow, ...
            scenarioStatus, ...
            scenarioMessage)

status(targetIndex) = 'FAIL';
message(targetIndex) = string(errorMessage);
profiles(targetIndex).Status = 'FAIL';
profiles(targetIndex).Message = errorMessage;
profiles(targetIndex).ErrorMessage = errorMessage;

scenarioAffected = scenarioTargetRow == targetIndex;
scenarioStatus(scenarioAffected) = 'FAIL';
scenarioMessage(scenarioAffected) = string(errorMessage);

end


function validate_subsystem_cut(ownerPath)

if ~strcmp(get_param(ownerPath, 'BlockType'), 'SubSystem')
    error( ...
        'SLDV mode requires a Subsystem CUT: %s', ...
        ownerPath);
end

end


function action = ensure_atomic_sldv_cut(cfg, ownerPath)

validate_subsystem_cut(ownerPath);

if strcmp(get_param(ownerPath, 'TreatAsAtomicUnit'), 'on')
    action = 'ALREADY_ATOMIC';
    return;
end

if ~isfield(cfg, 'AutoConvertSldvTargetsToAtomic') || ...
        ~cfg.AutoConvertSldvTargetsToAtomic

    error( ...
        ['SLDV FILE/GENERATE requires an atomic subsystem ' ...
         '(TreatAsAtomicUnit=on), and automatic conversion is disabled: %s'], ...
        ownerPath);
end

set_param( ...
    ownerPath, ...
    'TreatAsAtomicUnit', ...
    'on');

action = 'CONVERTED';

st_log( ...
    cfg, ...
    'INFO', ...
    ['[SLDV] Converted target to an atomic Subsystem and kept the change ' ...
     '| CUT=%s'], ...
    ownerPath);

end


function fullPath = resolve_sldv_data_file(value, cfg)

textValue = strtrim(char(string(value)));

if isempty(textValue)
    error( ...
        'SldvDataFile is required when SldvMode=FILE.');
end

fileObj = java.io.File(textValue);

if fileObj.isAbsolute()
    fullPath = char(fileObj.getCanonicalPath());
else
    fullPath = char( ...
        java.io.File( ...
            fileparts(cfg.ManagementExcel), ...
            textValue).getCanonicalPath());
end

if ~isfile(fullPath)
    error( ...
        'SLDV data file not found: %s', ...
        fullPath);
end

end


function [latestFile, status, message, runElapsed, meta] = ...
        generate_sldv_data( ...
            cfg, ...
            targetRow, ...
            ownerPath, ...
            harnessInput)

targetId = safe_target_id(targetRow.No, targetRow.CUTName);
targetDir = fullfile(cfg.SldvDir, targetId);

if ~isfolder(targetDir)
    mkdir(targetDir);
end

stagingDir = tempname(targetDir);
mkdir(stagingDir);

cleanup = onCleanup( ...
    @() cleanup_staging_dir(stagingDir)); %#ok<NASGU>

modelOptions = sldvoptions(cfg.TopModel);
opts = modelOptions.deepCopy;
opts.Mode = 'TestGeneration';
opts.OutputDir = stagingDir;
opts.MakeOutputFilesUnique = 'off';
opts.DataFileName = 'candidate_sldvdata';
opts.SaveReport = 'off';
opts.SaveHarnessModel = 'off';

st_log( ...
    cfg, ...
    'INFO', ...
    '[SLDV] sldvrun start | CUT=%s', ...
    ownerPath);

runTimer = tic;

try
    [status, files, msg] = ...
        sldvrun(ownerPath, opts, false);

    runElapsed = toc(runTimer);
    message = flatten_sldv_messages(msg);

catch ME
    runElapsed = toc(runTimer);
    status = 0;
    files = struct();
    message = ME.message;
end

st_log( ...
    cfg, ...
    'INFO', ...
    '[SLDV] sldvrun returned | CUT=%s | Status=%g', ...
    ownerPath, ...
    double(status));

latestFile = '';
meta = [];

if double(status) ~= 1
    return;
end

if ~isstruct(files) || ...
        ~isfield(files, 'DataFile') || ...
        isempty(files.DataFile)

    message = append_message( ...
        message, ...
        'SLDV generation returned no valid DataFile.');

    return;
end

candidateFile = resolve_generated_data_file( ...
    files.DataFile, ...
    stagingDir);

if isempty(candidateFile)
    message = append_message( ...
        message, ...
        sprintf( ...
            'SLDV generation DataFile does not exist: %s', ...
            char(string(files.DataFile))));

    return;
end

try
    meta = inspect_sldv_data( ...
        candidateFile, ...
        ownerPath, ...
        targetRow.CUTName, ...
        cfg.SldvTmaxResolution, ...
        harnessInput, ...
        cfg.IgnoreUnexpectedSldvInputs);

    validate_harness_input_interface( ...
        harnessInput, ...
        meta.InputNames, ...
        meta.InputTypes, ...
        meta.InputDimensions, ...
        cfg.IgnoreUnexpectedSldvInputs);

    latestFile = ...
        fullfile(targetDir, 'latest_sldvdata.mat');

    temporaryLatest = ...
        [latestFile '.tmp'];

    if isfile(temporaryLatest)
        delete(temporaryLatest);
    end

    copyfile( ...
        candidateFile, ...
        temporaryLatest, ...
        'f');

    movefile( ...
        temporaryLatest, ...
        latestFile, ...
        'f');

    latestFile = char( ...
        java.io.File(latestFile).getCanonicalPath());

catch ME
    latestFile = '';
    meta = [];
    message = append_message(message, ME.message);
end

end


function dataFile = resolve_generated_data_file(value, stagingDir)

reported = char(string(value));

if isfile(reported)
    dataFile = canonical_path(reported);
    return;
end

relativeToStaging = ...
    fullfile(stagingDir, reported);

if isfile(relativeToStaging)
    dataFile = canonical_path(relativeToStaging);
else
    dataFile = '';
end

end


function meta = inspect_sldv_data( ...
        dataFile, ownerPath, cutName, tmaxResolution, ...
        harnessInput, ignoreUnexpectedSldvInputs)

loaded = load(dataFile, 'sldvData');

if ~isfield(loaded, 'sldvData') || ...
        ~isstruct(loaded.sldvData)

    error( ...
        'MAT file does not contain a valid sldvData structure: %s', ...
        dataFile);
end

data = loaded.sldvData;

if ~isfield(data, 'ModelInformation') || ...
        ~isfield(data.ModelInformation, 'SubsystemPath')

    error( ...
        'sldvData.ModelInformation.SubsystemPath is missing.');
end

actualPath = ...
    strtrim( ...
        char(string(data.ModelInformation.SubsystemPath)));

if ~same_simulink_path(actualPath, ownerPath)
    error( ...
        'SLDV subsystem mismatch. Expected=%s, Actual=%s', ...
        ownerPath, ...
        actualPath);
end

if ~isfield(data, 'TestCases') || ...
        isempty(data.TestCases)

    error( ...
        'SLDV data contains no TestCases: %s', ...
        dataFile);
end

sourceIndices = zeros(0,1);
endTimes = zeros(0,1);
parameterCounts = zeros(0,1);
scenarioNames = cell(0,1);
originalNames = cell(0,1);
referenceSignature = strings(0,1);
hasReferenceSignature = false;
inputNames = cell(0,1);
inputTypes = cell(0,1);
inputDimensions = cell(0,1);
ignoredInputNames = cell(0,1);

for sourceIndex = 1:numel(data.TestCases)
    tc = data.TestCases(sourceIndex);

    if testcase_has_no_effect(tc)
        continue;
    end

    if ~isfield(tc, 'timeValues') || ...
            isempty(tc.timeValues)

        error( ...
            'SLDV TestCase %d has no timeValues.', ...
            sourceIndex);
    end

    timeValues = double(tc.timeValues(:));

    if any(~isfinite(timeValues)) || ...
            any(timeValues < 0) || ...
            any(diff(timeValues) < 0)

        error( ...
            'SLDV TestCase %d has invalid timeValues.', ...
            sourceIndex);
    end

    [dataset, params] = ...
        sldvsimdata(dataFile, sourceIndex);

    if ~isa(dataset, 'Simulink.SimulationData.Dataset') || ...
            dataset.numElements == 0

        error( ...
            ['SLDV TestCase %d did not produce ' ...
             'a nonempty Dataset.'], ...
            sourceIndex);
    end

    [signature, names, types, dimensions] = ...
        dataset_signature(dataset);

    [selectedIndices, names, ignoredNames] = ...
        st_select_sldv_input_indices( ...
            names, ...
            harnessInput.Names, ...
            ignoreUnexpectedSldvInputs);

    signature = signature(selectedIndices);
    types = types(selectedIndices);
    dimensions = dimensions(selectedIndices);
    ignoredInputNames = unique( ...
        [ignoredInputNames; ignoredNames], ...
        'stable');

    normalizedParams = ...
        st_normalize_sldv_parameters( ...
            params, ...
            sourceIndex);

    validationIteration = ...
        sltest.testmanager.TestIteration;

    st_apply_sldv_parameters( ...
        validationIteration, ...
        params, ...
        sourceIndex);

    if ~hasReferenceSignature
        referenceSignature = signature;
        inputNames = names;
        inputTypes = types;
        inputDimensions = dimensions;
        hasReferenceSignature = true;

    elseif ~isequal(signature, referenceSignature)
        error( ...
            ['SLDV TestCase %d input interface ' ...
             'differs from earlier cases.'], ...
            sourceIndex);
    end

    outputIndex = ...
        numel(sourceIndices) + 1;

    sourceIndices(outputIndex,1) = sourceIndex;
    endTimes(outputIndex,1) = timeValues(end);
    parameterCounts(outputIndex,1) = numel(normalizedParams);
    scenarioNames{outputIndex,1} = ...
        st_scenario_name(cutName, outputIndex);
    originalNames{outputIndex,1} = ...
        testcase_info_name(tc, sourceIndex);
end

if isempty(sourceIndices)
    error( ...
        'SLDV data contains no effective TestCases.');
end

meta = struct();
meta.SourceIndices = sourceIndices;
meta.EndTimes = endTimes;
meta.RawTmax = max(endTimes);
meta.Tmax = st_quantize_sldv_tmax(meta.RawTmax, tmaxResolution);
meta.ParameterCounts = parameterCounts;
meta.ScenarioNames = scenarioNames;
meta.OriginalNames = originalNames;
meta.InputNames = inputNames;
meta.InputTypes = inputTypes;
meta.InputDimensions = inputDimensions;
meta.IgnoredInputNames = ignoredInputNames;

end


function name = testcase_info_name(tc, sourceIndex)

name = sprintf( ...
    'SLDV Test Case %d', ...
    sourceIndex);

if ~isfield(tc, 'info') || ...
        isempty(tc.info) || ...
        ~isstruct(tc.info)

    return;
end

candidateFields = { ...
    'name', ...
    'Name', ...
    'testCaseName', ...
    'TestCaseName', ...
    'label', ...
    'Label'};

for i = 1:numel(candidateFields)
    fieldName = candidateFields{i};

    if isfield(tc.info, fieldName) && ...
            ~isempty(tc.info.(fieldName))

        name = char( ...
            string(tc.info.(fieldName)));

        return;
    end
end

end


function tf = testcase_has_no_effect(tc)

tf = false;

if ~isfield(tc, 'dataNoEffect') || ...
        isempty(tc.dataNoEffect)

    return;
end

values = tc.dataNoEffect;

if ~iscell(values)
    values = {values};
end

hasValue = false;
allNoEffect = true;

for i = 1:numel(values)
    if isempty(values{i})
        continue;
    end

    hasValue = true;
    allNoEffect = ...
        allNoEffect && ...
        all(logical(values{i}(:)));
end

tf = ...
    hasValue && ...
    allNoEffect;

end


function [signature, names, types, dimensions] = ...
        dataset_signature(dataset)

n = dataset.numElements;

signature = strings(n,1);
names = cell(n,1);
types = cell(n,1);
dimensions = cell(n,1);

for i = 1:n
    element = dataset.getElement(i);

    name = strtrim( ...
        char(string(element.Name)));

    if isempty(name)
        error( ...
            'Dataset element %d has an empty Name.', ...
            i);
    end

    names{i} = name;
    value = element;

    if isa(element, 'Simulink.SimulationData.Signal')
        value = element.Values;
    end

    [valueText, valueType, valueDimensions] = ...
        value_signature(value);

    signature(i) = string( ...
        sprintf( ...
            '%s|%s', ...
            name, ...
            valueText));

    types{i} = valueType;
    dimensions{i} = valueDimensions;
end

end


function [text, dataType, dimensions] = value_signature(value)

if isa(value, 'timeseries')
    data = value.Data;
    dims = size(data);

    if ~isempty(value.Time) && ...
            isprop(value, 'IsTimeFirst') && ...
            value.IsTimeFirst && ...
            ~isempty(dims)

        dims = dims(2:end);

    elseif ~isempty(value.Time) && ...
            ~isempty(dims) && ...
            dims(end) == numel(value.Time)

        dims = dims(1:end-1);

    elseif ~isempty(value.Time) && ...
            ~isempty(dims) && ...
            dims(1) == numel(value.Time)

        dims = dims(2:end);
    end

    dataType = value_data_type(data);
    dimensions = normalize_signal_dimensions(dims);

    text = sprintf( ...
        'timeseries|%s|%s', ...
        dataType, ...
        mat2str(dimensions));

elseif istimetable(value)
    data = value.Variables;
    dims = size(data);
    dims = dims(2:end);

    dataType = value_data_type(data);
    dimensions = normalize_signal_dimensions(dims);

    text = sprintf( ...
        'timetable|%s|%s', ...
        dataType, ...
        mat2str(dimensions));

else
    dataType = value_data_type(value);
    dimensions = normalize_signal_dimensions(size(value));

    text = sprintf( ...
        '%s|%s', ...
        dataType, ...
        mat2str(dimensions));
end

end


function type = value_data_type(value)

if isa(value, 'embedded.fi')
    type = 'fixed';

elseif isstruct(value)
    type = 'bus';

else
    type = class(value);
end

end


function dims = normalize_signal_dimensions(dims)

dims = double(dims(:).');

if isempty(dims)
    dims = 1;

elseif all(dims == 1)
    dims = 1;
end

end


function interface = inspect_harness_input_interface( ...
        cfg, ...
        ownerPath, ...
        harnessName)
%INSPECT_HARNESS_INPUT_INTERFACE
% Read the actual runtime input interface from the target Harness Signal
% Editor ActiveScenario Dataset.
%
% This deliberately does not inspect direct CUT Inport blocks.

harnessName = char(harnessName);

st_force_model_stopped(cfg.TopModel);

sltest.harness.load( ...
    ownerPath, ...
    harnessName);

cleanup = onCleanup( ...
    @() close_harness_quiet( ...
        ownerPath, ...
        harnessName)); %#ok<NASGU>

signalEditorBlock = ...
    st_find_signal_editor_block(harnessName);

scenarioName = ...
    strtrim( ...
        char( ...
            get_param( ...
                signalEditorBlock, ...
                'ActiveScenario')));

if isempty(scenarioName)
    error( ...
        'Signal Editor ActiveScenario is empty: %s', ...
        signalEditorBlock);
end

matPath = ...
    st_resolve_data_file( ...
        get_param( ...
            signalEditorBlock, ...
            'Filename'), ...
        cfg.TopModel);

if ~isfile(matPath)
    error( ...
        'Signal Editor data file not found: %s', ...
        matPath);
end

loaded = ...
    load( ...
        matPath, ...
        scenarioName);

if ~isfield(loaded, scenarioName)
    error( ...
        'Active scenario variable not found in MAT file: %s', ...
        scenarioName);
end

scenario = ...
    loaded.(scenarioName);

if ~isa( ...
        scenario, ...
        'Simulink.SimulationData.Dataset') || ...
        scenario.numElements == 0

    error( ...
        ['Harness Signal Editor ActiveScenario must be a nonempty ' ...
         'Simulink.SimulationData.Dataset: %s'], ...
        scenarioName);
end

[~, names, types, dimensions] = ...
    dataset_signature(scenario);

interface = struct();
interface.ScenarioName = scenarioName;
interface.DataFile = canonical_path(matPath);
interface.Names = names;
interface.Types = types;
interface.Dimensions = dimensions;

end


function [sldvDrivenNames, preservedHarnessNames] = ...
        validate_harness_input_interface( ...
        harnessInput, ...
        datasetNames, ...
        datasetTypes, ...
        datasetDimensions, ...
        ignoreUnexpectedSldvInputs)
%VALIDATE_HARNESS_INPUT_INTERFACE
% Validate an SLDV Dataset against the Harness ActiveScenario input
% interface. SLDV inputs must be a subset of the Harness inputs. Harness
% inputs omitted by SLDV are retained from the original ActiveScenario when
% the per-TestCase Signal Editor Dataset is assembled.

harnessNames = ...
    harnessInput.Names;

datasetNames = cellstr(string(datasetNames(:)));

if numel(unique(string(harnessNames(:)))) ~= numel(harnessNames)

    error( ...
        'Harness ActiveScenario contains duplicate input names: [%s]', ...
        strjoin(harnessNames, ', '));
end

[selectedIndices, datasetNames] = ...
    st_select_sldv_input_indices( ...
        datasetNames, ...
        harnessNames, ...
        ignoreUnexpectedSldvInputs);
datasetTypes = datasetTypes(selectedIndices);
datasetDimensions = datasetDimensions(selectedIndices);

for i = 1:numel(datasetNames)

    datasetName = datasetNames{i};
    harnessIndex = find(strcmp(harnessNames, datasetName), 1, 'first');

    if ~strcmpi( ...
            harnessInput.Types{harnessIndex}, ...
            datasetTypes{i})

        error( ...
            ['SLDV Dataset/Harness ActiveScenario data type mismatch at ' ...
             'input %d (%s). Harness=%s, SLDV=%s'], ...
            i, ...
            datasetName, ...
            harnessInput.Types{harnessIndex}, ...
            datasetTypes{i});
    end

    if ~isequal( ...
            harnessInput.Dimensions{harnessIndex}, ...
            datasetDimensions{i})

        error( ...
            ['SLDV Dataset/Harness ActiveScenario dimensions mismatch at ' ...
             'input %d (%s). Harness=%s, SLDV=%s'], ...
            i, ...
            datasetName, ...
            mat2str(harnessInput.Dimensions{harnessIndex}), ...
            mat2str(datasetDimensions{i}));
    end
end

sldvDrivenNames = datasetNames;
preservedHarnessNames = ...
    harnessNames(~ismember(string(harnessNames), string(datasetNames)));

end


function users = collect_signal_editor_data_users(cfg)

harnesses = ...
    sltest.harness.find(cfg.TopModel);

users = ...
    struct( ...
        'Owner', {}, ...
        'Harness', {}, ...
        'DataFile', {}, ...
        'Label', {});

for i = 1:numel(harnesses)
    owner = ...
        char(harnesses(i).ownerFullPath);

    harnessName = ...
        char(harnesses(i).name);

    try
        sltest.harness.load( ...
            owner, ...
            harnessName);

        block = ...
            st_find_signal_editor_block(harnessName);

        matPath = ...
            st_resolve_data_file( ...
                get_param(block, 'Filename'), ...
                cfg.TopModel);

        entry.Owner = owner;
        entry.Harness = harnessName;
        entry.DataFile = canonical_path(matPath);
        entry.Label = [owner '::' harnessName];

        users(end+1) = entry; %#ok<AGROW>

    catch
        % Harnesses without a Signal Editor are not data-file users.
    end

    close_harness_quiet( ...
        owner, ...
        harnessName);
end

end


function [matPath, matchingLabels] = ...
        target_signal_editor_data_file( ...
            users, ...
            ownerPath, ...
            harnessName)

row = find( ...
    strcmp({users.Owner}, ownerPath) & ...
    strcmp({users.Harness}, harnessName), ...
    1, ...
    'first');

if isempty(row)
    error( ...
        ['Target harness Signal Editor data file ' ...
         'could not be resolved: %s'], ...
        harnessName);
end

matPath = ...
    users(row).DataFile;

if ispc
    matching = ...
        strcmpi( ...
            {users.DataFile}, ...
            matPath);
else
    matching = ...
        strcmp( ...
            {users.DataFile}, ...
            matPath);
end

matchingLabels = ...
    {users(matching).Label};

end


function tf = same_simulink_path(a, b)

a = ...
    strrep( ...
        strtrim(char(a)), ...
        '\', ...
        '/');

b = ...
    strrep( ...
        strtrim(char(b)), ...
        '\', ...
        '/');

if ispc
    tf = strcmpi(a, b);
else
    tf = strcmp(a, b);
end

end


function id = safe_target_id(no, cutName)

noText = ...
    regexprep( ...
        sprintf('%.17g', double(no)), ...
        '[^A-Za-z0-9_-]', ...
        '_');

cutText = ...
    regexprep( ...
        char(string(cutName)), ...
        '[^A-Za-z0-9_-]', ...
        '_');

if isempty(cutText)
    cutText = 'CUT';
end

id = ...
    [noText '_' cutText];

end


function textValue = flatten_sldv_messages(msg)

if isempty(msg)
    textValue = '';
    return;
end

if ischar(msg) || ...
        (isstring(msg) && isscalar(msg))

    textValue = ...
        char(string(msg));

    return;
end

if iscell(msg)
    parts = strings(0,1);

    for i = 1:numel(msg)
        current = ...
            flatten_sldv_messages(msg{i});

        if ~isempty(current)
            parts(end+1,1) = string(current); %#ok<AGROW>
        end
    end

    textValue = ...
        char(strjoin(parts, ' | '));

    return;
end

if ~isstruct(msg)
    textValue = ...
        char(string(msg));

    return;
end

parts = strings(0,1);

for i = 1:numel(msg)
    if isfield(msg, 'msgid') && ...
            ~isempty(msg(i).msgid)

        parts(end+1,1) = ...
            string(msg(i).msgid); %#ok<AGROW>
    end

    if isfield(msg, 'msg') && ...
            ~isempty(msg(i).msg)

        parts(end+1,1) = ...
            string(msg(i).msg); %#ok<AGROW>

    elseif isfield(msg, 'message') && ...
            ~isempty(msg(i).message)

        parts(end+1,1) = ...
            string(msg(i).message); %#ok<AGROW>
    end
end

textValue = ...
    char(strjoin(parts, ' | '));

end


function value = append_message(existing, addition)

if isempty(existing)
    value = ...
        char(string(addition));

elseif isempty(addition)
    value = ...
        char(string(existing));

else
    value = ...
        char( ...
            strjoin( ...
                [string(existing); string(addition)], ...
                ' | '));
end

end


function cleanup_staging_dir(stagingDir)

if isfolder(stagingDir)
    rmdir(stagingDir, 's');
end

end


function path = canonical_path(path)

path = ...
    char( ...
        java.io.File( ...
            char(path)).getCanonicalPath());

end


function close_harness_quiet(ownerPath, harnessName)

try
    sltest.harness.close( ...
        ownerPath, ...
        harnessName);
catch
end

end


function value = current_timestamp()

value = ...
    string( ...
        datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd HH:mm:ss'));

end


function value = profile_field(profile, field, defaultValue)

if isfield(profile, field)
    value = profile.(field);
else
    value = defaultValue;
end

end


function save_manifest_atomic(filePath, manifest)

folder = fileparts(filePath);
if ~isfolder(folder)
    mkdir(folder);
end
temporaryPath = [tempname(folder) '.mat'];
cleanupFile = onCleanup(@() delete_file_quiet(temporaryPath)); %#ok<NASGU>
save(temporaryPath, 'manifest');
[ok, message] = movefile(temporaryPath, filePath, 'f');
if ~ok
    error('simtest:SldvManifestWriteFailed', ...
        'Cannot replace SLDV manifest %s: %s', filePath, message);
end
end


function delete_file_quiet(filePath)

if isfile(filePath)
    delete(filePath);
end
end


function [targetRows, nos, cutNames, modes, sourceIndices, ...
        originalNames, scenarioNames, endTimes, tmaxValues, ...
        parameterCounts, statuses, messages] = ...
    append_cached_scenarios(profile, targetRow, target, ...
        targetRows, nos, cutNames, modes, sourceIndices, ...
        originalNames, scenarioNames, endTimes, tmaxValues, ...
        parameterCounts, statuses, messages)

names = profile_field(profile, 'ScenarioNames', {});
sources = profile_field(profile, 'SourceIndices', []);
originals = profile_field(profile, 'OriginalNames', {});
times = profile_field(profile, 'EndTimes', []);
counts = profile_field(profile, 'ParameterCounts', []);
tmax = profile_field(profile, 'Tmax', NaN);
mode = profile_field(profile, 'Mode', char(target.SldvMode));

for k = 1:numel(names)
    targetRows(end+1,1) = targetRow; %#ok<AGROW>
    nos(end+1,1) = double(target.No); %#ok<AGROW>
    cutNames(end+1,1) = string(target.CUTName); %#ok<AGROW>
    modes(end+1,1) = string(mode); %#ok<AGROW>
    sourceIndices(end+1,1) = numeric_at(sources, k, k); %#ok<AGROW>
    originalNames(end+1,1) = string(cell_at(originals, k, names{k})); %#ok<AGROW>
    scenarioNames(end+1,1) = string(names{k}); %#ok<AGROW>
    endTimes(end+1,1) = numeric_at(times, k, NaN); %#ok<AGROW>
    tmaxValues(end+1,1) = tmax; %#ok<AGROW>
    parameterCounts(end+1,1) = numeric_at(counts, k, 0); %#ok<AGROW>
    statuses(end+1,1) = "CACHED"; %#ok<AGROW>
    messages(end+1,1) = "Reused from SLDV manifest"; %#ok<AGROW>
end

end


function value = numeric_at(values, index, defaultValue)

if numel(values) >= index
    value = double(values(index));
else
    value = defaultValue;
end

end


function value = cell_at(values, index, defaultValue)

if numel(values) >= index
    if iscell(values)
        value = values{index};
    else
        value = values(index);
    end
else
    value = defaultValue;
end

end
