function [selectedIndices, selectedNames, ignoredNames] = ...
        st_select_sldv_input_indices( ...
            datasetNames, harnessNames, ignoreUnexpected)
%ST_SELECT_SLDV_INPUT_INDICES Select SLDV inputs present in the Harness.

datasetNames = cellstr(string(datasetNames(:)));
harnessNames = cellstr(string(harnessNames(:)));
ignoreUnexpected = logical(ignoreUnexpected);

if ~isscalar(ignoreUnexpected)
    error( ...
        'simtest:InvalidIgnoreUnexpectedSldvInputs', ...
        'IgnoreUnexpectedSldvInputs must be a logical scalar.');
end

if numel(unique(string(datasetNames))) ~= numel(datasetNames)
    error( ...
        'simtest:DuplicateSldvInputNames', ...
        'SLDV Dataset contains duplicate input names: [%s]', ...
        strjoin(datasetNames, ', '));
end

unexpectedMask = ...
    ~ismember(string(datasetNames), string(harnessNames));
ignoredNames = datasetNames(unexpectedMask);

if ~isempty(ignoredNames) && ~ignoreUnexpected
    error( ...
        'simtest:UnexpectedSldvInputs', ...
        ['SLDV Dataset contains signals that are not present in the ' ...
         'Harness input interface. Unexpected=[%s], Harness=[%s]'], ...
        strjoin(ignoredNames, ', '), ...
        strjoin(harnessNames, ', '));
end

selectedIndices = find(~unexpectedMask);
selectedNames = datasetNames(selectedIndices);

end
