function st_validate_mat_harness_interface( ...
        harnessInput, names, types, dimensions, varargin)
%ST_VALIDATE_MAT_HARNESS_INTERFACE Validate the MAT/Harness interface.
actualNames = cellstr(string(names(:)));
expectedNames = cellstr(string(harnessInput.Names(:)));
if numel(types) ~= numel(actualNames) || ...
        numel(dimensions) ~= numel(actualNames) || ...
        numel(harnessInput.Types) ~= numel(expectedNames) || ...
        numel(harnessInput.Dimensions) ~= numel(expectedNames)
    error('simtest:MatHarnessInterfaceMismatch', ...
        ['MAT Dataset or Harness interface metadata is incomplete. ' ...
         'MAT names/types/dims=%d/%d/%d, Harness=%d/%d/%d'], ...
        numel(actualNames), numel(types), numel(dimensions), ...
        numel(expectedNames), numel(harnessInput.Types), ...
        numel(harnessInput.Dimensions));
end
if ~isequal(string(actualNames(:)), string(expectedNames(:)))
    error('simtest:MatHarnessInterfaceMismatch', ...
        ['MAT Dataset/Harness ActiveScenario input count, names, or order ' ...
         'mismatch. MAT=[%s], Harness=[%s]'], ...
        strjoin(actualNames, ', '), strjoin(expectedNames, ', '));
end

for i = 1:numel(expectedNames)
    if ~strcmpi(types{i}, harnessInput.Types{i})
        error('simtest:MatHarnessInterfaceMismatch', ...
            ['MAT Dataset/Harness ActiveScenario data type mismatch at ' ...
             'input %d (%s). MAT=%s, Harness=%s'], ...
            i, expectedNames{i}, types{i}, harnessInput.Types{i});
    end
    dimensionsMatch = st_signal_dimensions_match( ...
        dimensions{i}, harnessInput.Dimensions{i}, types{i});
    if ~dimensionsMatch
        error('simtest:MatHarnessInterfaceMismatch', ...
            ['MAT Dataset/Harness ActiveScenario dimensions mismatch at ' ...
             'input %d (%s). MAT=%s, Harness=%s'], ...
            i, expectedNames{i}, mat2str(dimensions{i}), ...
            mat2str(harnessInput.Dimensions{i}));
    end
    if ~isequal(dimensions{i}, harnessInput.Dimensions{i}) && ...
            ~isempty(varargin)
        st_log(varargin{1}, 'WARN', ...
            ['MAT Dataset/Harness bus-vector orientation mismatch allowed ' ...
             '| Input=%s | MAT=%s | Harness=%s'], ...
            expectedNames{i}, mat2str(dimensions{i}), ...
            mat2str(harnessInput.Dimensions{i}));
    end
end
end
