function catalog = st_specification_decision_catalog(scope)
%ST_SPECIFICATION_DECISION_CATALOG Single source of decision block knowledge.
% One row per Simulink BlockType that can create a branch in a saved model.
% Adding a block type is one row here. Only a type whose expression needs
% special assembly also needs a case in st_specification_decision_descriptor.
%
% SCOPE selects how much of the catalog to return. It is a view over the
% same rows, so the table below always describes every type the toolkit
% knows about.
%   ALL       every row. The default, because a caller that formats an
%             existing workbook must recognize a type the current export
%             scope would have skipped.
%   EXPLICIT  only the blocks that carry a condition in their dialog.
%   NONE      no rows, which turns the DecisionBlocks inventory off.
%
% BlockType          get_param(block,'BlockType') value, used by find_system.
%                    EnablePort and TriggerPort are the exception: the
%                    branch sits on a port block one level inside an
%                    Enabled or Triggered Subsystem, but it belongs to the
%                    subsystem the CUT owns, so the scan reports the
%                    subsystem and uses the port type as the key.
% Outcome            Branch kind recorded in the DecisionBlockDetails Outcome
%                    column and in the JSON object. Also the fallback outcome
%                    when the expression read fails. The main specification
%                    cell always prints T/F instead, so this value is not
%                    constrained by the inline display width.
% DisplayType        Text printed after the outcome. Equal to BlockType unless
%                    the block is better known by another name (If -> IF).
% Formatter          CUSTOM  expression is assembled by a case in the descriptor.
%                    GENERIC expression is FixedText plus "Name=Value" pairs.
% Parameters         Comma separated get_param names read as saved text.
%                    A failed read degrades the row to WARN.
% OptionalParameters Comma separated get_param names that may be absent on a
%                    release or dialog state. A failed read is skipped silently,
%                    so an unverified parameter name belongs here.
% FixedText          Static leading text for a block whose branch has no
%                    configurable parameter (Abs).
% Kind               EXPLICIT: the user writes the condition in the dialog.
%                    IMPLICIT: creates coverage objectives without looking
%                    like a decision. A model with no If or Switch block can
%                    still report Decision coverage because of this group.
% MainExpression     SHOW prints the saved condition in the main cell after
%                    the block type. HIDE prints the type alone. Either way
%                    DecisionBlockDetails keeps the full expression.
%
% A block type may also report more than one branch. The descriptor returns
% one expression per branch and each branch gets its own D number, so an If
% block with two elseif expressions occupies three of them.
%
% Nothing here is evaluated. Values are the saved dialog text only, so a
% lookup table configured from a workspace variable shows the variable name.
if nargin < 1 || isempty(scope)
    scope = "ALL";
end
scope = upper(strtrim(string(scope)));
% "" is a 1x1 string, so isempty above does not catch a blank request.
if isscalar(scope) && ~ismissing(scope) && strlength(scope) == 0
    scope = "ALL";
end
if ~isscalar(scope) || ~ismember(scope, ["ALL","EXPLICIT","NONE"])
    error('simtest:SpecificationDecisionScope', ...
        'DecisionBlockScope must be ALL, EXPLICIT or NONE.');
end

BlockType = [ ...
    "If"; "Switch"; "MinMax"; "MultiPortSwitch"; "SwitchCase"; ...
    "Saturate"; "Abs"; "DeadZone"; "RateLimiter"; "Relay"; ...
    "Lookup_n-D"; "Interpolation_n-D"; "PreLookup"; ...
    "Integrator"; "DiscreteIntegrator"; ...
    "ForIterator"; "WhileIterator"; "Logic"; ...
    "EnablePort"; "TriggerPort"];

Outcome = [ ...
    "T/F"; "T/F"; "SELECT"; "SELECT"; "CASE"; ...
    "LIMIT"; "SIGN"; "BAND"; "RATE"; "ON/OFF"; ...
    "INTERVAL"; "INTERVAL"; "INTERVAL"; ...
    "LIMIT"; "LIMIT"; ...
    "LOOP"; "LOOP"; "CONDITION"; ...
    "ON/OFF"; "EDGE"];

DisplayType = [ ...
    "IF"; "Switch"; "MinMax"; "MultiPortSwitch"; "SwitchCase"; ...
    "Saturate"; "Abs"; "DeadZone"; "RateLimiter"; "Relay"; ...
    "Lookup_n-D"; "Interpolation_n-D"; "PreLookup"; ...
    "Integrator"; "DiscreteIntegrator"; ...
    "ForIterator"; "WhileIterator"; "Logic"; ...
    "EnabledSubsystem"; "TriggeredSubsystem"];

Formatter = [ ...
    "CUSTOM"; "CUSTOM"; "CUSTOM"; "CUSTOM"; "CUSTOM"; ...
    "GENERIC"; "GENERIC"; "GENERIC"; "GENERIC"; "GENERIC"; ...
    "GENERIC"; "GENERIC"; "GENERIC"; ...
    "GENERIC"; "GENERIC"; ...
    "GENERIC"; "GENERIC"; "GENERIC"; ...
    "GENERIC"; "GENERIC"];

Parameters = [ ...
    ""; ""; ""; ""; ""; ...
    "UpperLimit,LowerLimit"; ...
    ""; ...
    "LowerValue,UpperValue"; ...
    "RisingSlewLimit,FallingSlewLimit"; ...
    "OnSwitchValue,OffSwitchValue"; ...
    "NumberOfTableDimensions,InterpMethod"; ...
    "NumberOfTableDimensions,InterpMethod"; ...
    "IndexSearchMethod"; ...
    "LimitOutput,ExternalReset"; ...
    "LimitOutput,ExternalReset"; ...
    "IterationSource"; ...
    "WhileBlockType"; ...
    "Operator,Inputs"; ...
    ""; ""];

OptionalParameters = [ ...
    ""; ""; ""; ""; ""; ...
    ""; ...
    ""; ...
    ""; ""; ""; ...
    "ExtrapMethod,BreakpointsSpecification,BreakpointsForDimension1"; ...
    "ExtrapMethod"; ...
    "BreakpointsSpecification,BreakpointsData,ExtrapMethod"; ...
    "UpperSaturationLimit,LowerSaturationLimit"; ...
    "UpperSaturationLimit,LowerSaturationLimit"; ...
    "IterationLimit"; ...
    "MaxIters"; ...
    ""; ...
    ""; ""];

FixedText = [ ...
    ""; ""; ""; ""; ""; ...
    ""; "u < 0"; ""; ""; ""; ...
    ""; ""; ""; ...
    ""; ""; ...
    ""; ""; ""; ...
    ""; ""];

Kind = [ ...
    "EXPLICIT"; "EXPLICIT"; "EXPLICIT"; "EXPLICIT"; "EXPLICIT"; ...
    "IMPLICIT"; "IMPLICIT"; "IMPLICIT"; "IMPLICIT"; "IMPLICIT"; ...
    "IMPLICIT"; "IMPLICIT"; "IMPLICIT"; ...
    "IMPLICIT"; "IMPLICIT"; ...
    "IMPLICIT"; "IMPLICIT"; "IMPLICIT"; ...
    "IMPLICIT"; "IMPLICIT"];

% SHOW prints the expression after the block type in the main cell. HIDE
% prints the block type alone, for a type whose saved condition is long and
% carries little on one line. DecisionBlockDetails keeps it either way.
MainExpression = [ ...
    "SHOW"; "SHOW"; "SHOW"; "SHOW"; "HIDE"; ...
    "SHOW"; "SHOW"; "SHOW"; "SHOW"; "SHOW"; ...
    "SHOW"; "SHOW"; "SHOW"; ...
    "SHOW"; "SHOW"; ...
    "SHOW"; "SHOW"; "SHOW"; ...
    "SHOW"; "SHOW"];

catalog = table(BlockType, Outcome, DisplayType, Formatter, ...
    Parameters, OptionalParameters, FixedText, Kind, MainExpression);

switch scope
    case "EXPLICIT"
        catalog = catalog(catalog.Kind == "EXPLICIT", :);
    case "NONE"
        catalog = catalog([], :);
end
end
