function usage = st_specification_usage_table(cfg)
%ST_SPECIFICATION_USAGE_TABLE Build the user-facing command guide sheet.
if nargin < 1, cfg = []; end
log_message(cfg, 'INFO', 'Specification usage sheet build start');
rows = [ ...
    "초기화" "st_setup.m" "권장" ...
        "프로젝트 src와 진단 폴더를 MATLAB Path에 추가하고 result 폴더를 준비" ...
        "MATLAB 세션 시작 후 1회" "st_setup"; ...
    "대상 선택" "st_select_target_model.m" "권장" ...
        "실행할 Top Model을 선택해 runtime_target.mat에 저장" ...
        "모델을 처음 선택하거나 변경할 때" "st_select_target_model"; ...
    "대상 선택" "st_save_model_profile.m" "필요 시" ...
        "모델, 관리 Excel, Test File, 결과 경로를 이름으로 묶어 로컬 저장" ...
        "모델을 여러 개 관리할 때 한 번" ...
        "st_save_model_profile('MODEL_A','ModelFile',f,'ManagementExcel',x,'OutputRoot',o);"; ...
    "대상 선택" "st_list_model_profiles.m" "필요 시" ...
        "저장된 모델 profile 목록을 표시" ...
        "어떤 profile이 있는지 확인할 때" "st_list_model_profiles();"; ...
    "대상 선택" "st_select_model_profile.m" "필요 시" ...
        "이름 또는 목록으로 모델 profile을 전환. 빈 문자열은 profile 해제" ...
        "대상 모델을 바꿀 때" "cfg = st_select_model_profile('MODEL_A');"; ...
    "예제" "st_create_example.m" "필요 시" ...
        "익명 모델, Dataset MAT, 관리 Excel을 새 폴더에 생성. 실행은 하지 않음" ...
        "실제 모델 없이 흐름을 익힐 때" ...
        "demo = st_create_example(fullfile(tempdir,'st_demo'));"; ...
    "경로 준비" "st_export_subsystem_paths.m" "필요 시" ...
        "선택 모델에서 발견 가능한 Subsystem 경로를 관리 Excel로 내보냄" ...
        "CUTPath 후보를 확인할 때" "R = st_export_subsystem_paths();"; ...
    "경로 준비" "st_fill_temp_paths_from_indent.m" "필요 시" ...
        "관리 Excel의 들여쓰기로 빈 CUTPath를 임시 작성" ...
        "Targets 계층을 처음 구성할 때" "R = st_fill_temp_paths_from_indent();"; ...
    "사전 검증" "st_pre_validate_targets.m" "권장" ...
        "CUTPath 존재 여부와 Subsystem 여부를 Harness 생성 전에 검사" ...
        "전체 Workflow 실행 전" "R = st_pre_validate_targets();"; ...
    "사전 검증" "st_validate_targets.m" "필요 시" ...
        "CUTPath와 이미 존재하는 Harness의 연결 관계를 검사" ...
        "기존 Harness Workflow를 개별 점검할 때" "R = st_validate_targets();"; ...
    "사전 검증" "st_check_readiness.m" "권장" ...
        "선택한 단계부터 실행해도 되는지 읽기 전용 검사. 준비와 실행은 하지 않음" ...
        "st_run_from_stage 실행 직전" ...
        "[ready, checks] = st_check_readiness('Workflow','FROM_HARNESS','FromStage','HARNESS');"; ...
    "Workflow" "st_run_from_harness.m" "권장" ...
        "Harness 생성부터 준비, Test Manager, 테스트와 보고서까지 전체 수행" ...
        "Harness가 없거나 전체 구성이 필요할 때" ...
        "st_run_from_harness('ExecutionMode','PER_CUT')"; ...
    "Workflow" "st_run_after_harness.m" "권장" ...
        "기존 Harness를 검증하고 SLDV 이후 준비, 테스트와 보고서를 수행" ...
        "Harness가 이미 준비된 경우" ...
        "st_run_after_harness('ExecutionMode','PER_CUT')"; ...
    "Workflow" "st_run_from_stage.m" "필요 시" ...
        "선행 단계를 검증한 뒤 선택 단계부터 끝까지 실행. 앞 단계는 다시 실행하지 않음" ...
        "오래 걸리는 앞 단계를 보존한 채 재시작할 때" ...
        "info = st_run_from_stage('Workflow','FROM_HARNESS','FromStage','ASSESSMENT');"; ...
    "테스트 실행" "st_run_tests_per_cut.m" "필요 시" ...
        "준비된 Test File을 CUT별로 실행하고 CVF 적용, 복원과 개별 보고서를 처리" ...
        "준비 없이 PER_CUT 테스트만 다시 실행할 때" ...
        "st_run_tests_per_cut('ReportMode','SUMMARY')"; ...
    "테스트 실행" "st_run_generated_tests.m" "고급" ...
        "준비된 Test File 전체를 BATCH로 실행하고 기대값 정책을 적용" ...
        "CoverageFilterMode와 CoverageBoundaryMode가 모두 OFF인 BATCH 실행" ...
        "[result, updates] = st_run_generated_tests();"; ...
    "명세서" "st_export_test_specification.m" "권장" ...
        "테스트 실행 없이 input, verify, MaxTime과 DecisionBlocks를 Excel로 추출. DecisionBlockScope로 분기 블록 범위를 EXPLICIT/ALL/NONE 중 선택" ...
        "테스트 명세서를 검토할 때" ...
        "[T, file] = st_export_test_specification();"; ...
    "내보내기" "st_export_test_asset_bundle.m" "필요 시" ...
        "선택한 결과의 MLDATX, CVT, CVF, Coverage, Harness와 입력 자산을 복사" ...
        "테스트 결과를 보관하거나 전달할 때" ...
        "info = st_export_test_asset_bundle('SelectResult',true);"; ...
    "내보내기" "st_export_test_bundle.m" "필요 시" ...
        "다른 PC에서 재실행 가능한 모델, 의존성, Test File과 입력 번들을 생성" ...
        "재현 가능한 전체 실행 번들이 필요할 때" ...
        "info = st_export_test_bundle();"; ...
    "Pipeline" "st_run_standalone_coverage_pipeline.m" "필요 시" ...
        "standalone Harness 실행, 결과 CVF 등록, CUT별 산출물과 Excel을 Action별 생성" ...
        "전체 실행 또는 EXECUTE 뒤 다른 MATLAB 세션에서 PACKAGE/SUMMARY를 재개할 때" ...
        "info = st_run_standalone_coverage_pipeline();"; ...
    "Pipeline 점검" "st_check_standalone_coverage.m" "권장" ...
        "manifest, lifecycle, 산출물과 Summary를 10비트 코드로 읽기 전용 검사" ...
        "standalone Coverage 구현 결과를 한 화면에서 확인할 때" ...
        "[code, summary, details] = st_check_standalone_coverage();"; ...
    "종합 검증" "st_verify_all.m" "필요 시" ...
        "환경, 단위 검사, 실제 모델 또는 fixture 검증 결과를 생성" ...
        "통합 또는 인증 검증 시" ...
        "summary = st_verify_all('Profile','QUICK','Target','CURRENT');"; ...
    "실행 점검" "st_check_actual_system.m" "권장" ...
        "환경, PER_CUT 실행과 CVF 상태를 18비트 코드로 읽기 전용 점검" ...
        "실제 PER_CUT 실행 후 종합 확인" ...
        "summary = st_check_actual_system();"; ...
    "필터 점검" "st_check_per_cut_cvf.m" "필요 시" ...
        "생성된 CVF의 selector, action, 적용과 복원 상태를 읽기 전용 검사" ...
        "PER_CUT 실행 후 필터만 확인할 때" ...
        "[code, details] = st_check_per_cut_cvf();"; ...
    "결과 정리" "st_cleanup_results.m" "필요 시" ...
        "생성 결과, checkpoint, CVF와 export를 범위별로 미리보기 또는 삭제" ...
        "기존 실행 흔적을 정리할 때. 기본은 DRY-RUN" ...
        "st_cleanup_results('Scope','STATE','Apply',true)"; ...
    "고급 단계" "st_create_harnesses.m" "고급" ...
        "일반 Harness 생성 또는 Template clone과 대상별 입력·Assessment 보정" "단계별 진단 또는 부분 재현" ...
        "R = st_create_harnesses();"; ...
    "고급 단계" "st_prepare_sldv_targets.m" "고급" ...
        "OFF, FILE, GENERATE별 SLDV 데이터와 manifest를 준비" ...
        "SLDV 준비 단계만 재현할 때" "[R, scenarios] = st_prepare_sldv_targets();"; ...
    "고급 단계" "st_configure_harnesses.m" "고급" ...
        "기존 Harness의 StopTime 등 실행 설정을 적용" ...
        "Harness 설정 단계만 재현할 때" "R = st_configure_harnesses();"; ...
    "고급 단계" "st_configure_signal_editors.m" "고급" ...
        "Signal Editor MAT와 Scenario를 생성하고 Harness에 연결" ...
        "Signal Editor 단계만 재현할 때" "R = st_configure_signal_editors();"; ...
    "고급 단계" "st_configure_assessments.m" "고급" ...
        "Test Assessment Scenario와 verify Action을 구성" ...
        "Assessment 단계만 재현할 때" "R = st_configure_assessments();"; ...
    "고급 단계" "st_prepare_coverage_filters.m" "고급" ...
        "공유 준비 방식의 Coverage Filter 파일을 생성하고 검증" ...
        "BATCH 필터 준비를 개별 점검할 때. PER_CUT은 실행 시 처리" ...
        "R = st_prepare_coverage_filters();"; ...
    "고급 단계" "st_create_test_manager.m" "고급" ...
        "Test File, Test Case와 Iteration을 구성" ...
        "Test Manager 구성 단계만 재현할 때" "R = st_create_test_manager();"; ...
    "고급 단계" "st_validate_scenario_alignment.m" "고급" ...
        "SLDV, Signal Editor, Assessment와 Test Manager Scenario 정렬을 검사" ...
        "테스트 실행 직전 정렬만 확인할 때" ...
        "R = st_validate_scenario_alignment();" ...
    ];
usage = array2table(rows, 'VariableNames', ...
    {'구분','실행파일','직접실행','역할','사용시점','대표사용법'});
log_message(cfg, 'INFO', ...
    'Specification usage sheet build end | Rows=%d', height(usage));
end

function log_message(cfg, level, format, varargin)
if isempty(cfg), return; end
st_log(cfg, level, format, varargin{:});
end
