function reportInfo = ...
    st_generate_test_report(runContext, workflowResult, workflowPlan)
%ST_GENERATE_TEST_REPORT Create one local bundle for a complete test run.

cfg = st_require_runtime_target();
targetConfig = st_load_targets(cfg.OnlyEnabled);
runInfo = st_report_run_context(runContext);

[runId, runDirectory] = create_run_directory(cfg.TestRunRootDir);
officialDirectory = fullfile(runDirectory, 'official');
coverageDirectory = fullfile(runDirectory, 'coverage');
rawDirectory = fullfile(runDirectory, 'raw');
mkdir(officialDirectory);
mkdir(coverageDirectory);
mkdir(rawDirectory);

artifacts = empty_artifact_table();
targets = empty_target_table();
iterations = empty_iteration_table();
coverage = empty_coverage_table();

try
    [initialTargets, initialIterations] = ...
        st_collect_test_result_summary( ...
            runContext.InitialResult, targetConfig, 'INITIAL');
    [finalTargets, finalIterations] = ...
        st_collect_test_result_summary( ...
            runContext.FinalResult, targetConfig, 'FINAL');
    targets = [initialTargets; finalTargets];
    iterations = [initialIterations; finalIterations];
    artifacts = record_artifact(artifacts, 'SUMMARY_DATA', '', ...
        'OK', 'Test result hierarchy collected');
catch ME
    artifacts = record_artifact(artifacts, 'SUMMARY_DATA', '', ...
        'FAIL', ME.message);
end

try
    initialCoverage = st_collect_coverage_summary( ...
        runContext.InitialResult, targetConfig, 'INITIAL');
    finalCoverage = st_collect_coverage_summary( ...
        runContext.FinalResult, targetConfig, 'FINAL');
    coverage = [initialCoverage; finalCoverage];
    extractionFailures = sum(coverage.Status == "EXTRACTION_FAILED");
    if extractionFailures > 0
        artifacts = record_artifact(artifacts, 'COVERAGE_DATA', '', ...
            'FAIL', sprintf('%d coverage extraction row(s) failed', ...
                extractionFailures));
    else
        artifacts = record_artifact(artifacts, 'COVERAGE_DATA', '', ...
            'OK', 'Decision and Execution coverage collected');
    end
catch ME
    artifacts = record_artifact(artifacts, 'COVERAGE_DATA', '', ...
        'FAIL', ME.message);
end

initialRaw = fullfile(rawDirectory, 'InitialResults.mldatx');
artifacts = export_result_artifact(artifacts, ...
    runContext.InitialResult, initialRaw);
finalRaw = fullfile(rawDirectory, 'FinalResults.mldatx');
artifacts = export_result_artifact(artifacts, ...
    runContext.FinalResult, finalRaw);

initialPdf = fullfile(officialDirectory, 'InitialTestResults.pdf');
artifacts = official_report_artifact(artifacts, ...
    runContext.InitialResult, initialPdf, 'Initial Test Results');
finalPdf = fullfile(officialDirectory, 'FinalTestResults.pdf');
artifacts = official_report_artifact(artifacts, ...
    runContext.FinalResult, finalPdf, 'Final Test Results');

artifacts = coverage_html_artifacts(artifacts, ...
    runContext.FinalResult, coverageDirectory);

summaryPath = fullfile(runDirectory, 'TestSummary.xlsx');
try
    write_summary_workbook(summaryPath, targets, iterations, coverage, ...
        runContext.ExpectedUpdateResult, workflowResult, workflowPlan, ...
        cfg, runId, runDirectory, artifacts);
    artifacts = record_artifact(artifacts, 'EXCEL', summaryPath, ...
        'OK', 'Integrated workbook created');
catch ME
    artifacts = record_artifact(artifacts, 'EXCEL', summaryPath, ...
        'FAIL', ME.message);
end

if isfile(summaryPath)
    latestDir = fileparts(cfg.LatestSummaryFile);
    if ~isfolder(latestDir)
        mkdir(latestDir);
    end
    [ok, message] = copyfile(summaryPath, cfg.LatestSummaryFile, 'f');
    if ok
        artifacts = record_artifact(artifacts, 'LATEST_EXCEL', ...
            cfg.LatestSummaryFile, 'OK', 'Latest summary updated');
    else
        artifacts = record_artifact(artifacts, 'LATEST_EXCEL', ...
            cfg.LatestSummaryFile, 'FAIL', message);
    end
end

manifestPath = fullfile(runDirectory, 'manifest.json');
manifest = build_manifest( ...
    runId, runDirectory, runInfo, cfg, artifacts);
write_json_atomic(manifestPath, manifest);

latest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'Status', manifest.Status, ...
    'UpdatedAt', timestamp_text());
write_json_atomic(cfg.LatestReportPointer, latest);

reportInfo = struct( ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'Status', manifest.Status, ...
    'ArtifactCount', height(artifacts), ...
    'FailedArtifactCount', sum(artifacts.Status == "FAIL"));

if reportInfo.FailedArtifactCount > 0
    warning('simtest:PartialTestReport', ...
        ['Integrated report completed with %d failed artifact(s). ' ...
         'See %s.'], reportInfo.FailedArtifactCount, manifestPath);
end
end

function artifacts = export_result_artifact(artifacts, resultObj, path)
try
    sltest.testmanager.exportResults(resultObj, path);
    artifacts = record_artifact(artifacts, 'MLDATX', path, ...
        'OK', 'ResultSet exported');
catch ME
    artifacts = record_artifact(artifacts, 'MLDATX', path, ...
        'FAIL', ME.message);
end
end

function artifacts = official_report_artifact( ...
        artifacts, resultObj, path, titleText)
try
    sltest.testmanager.report(resultObj, path, ...
        'Title', titleText, ...
        'IncludeMLVersion', true, ...
        'IncludeTestResults', int32(0), ...
        'IncludeCoverageResult', true, ...
        'IncludeSimulationMetadata', true, ...
        'LaunchReport', false);
    artifacts = record_artifact(artifacts, 'PDF', path, ...
        'OK', 'Official Test Manager report created');
catch ME
    artifacts = record_artifact(artifacts, 'PDF', path, ...
        'FAIL', ME.message);
end
end

function artifacts = coverage_html_artifacts(artifacts, resultObj, folder)
try
    coverageObjects = getCoverageResults(resultObj);
catch ME
    artifacts = record_artifact(artifacts, 'HTML', folder, ...
        'FAIL', ME.message);
    return;
end
if isempty(coverageObjects)
    artifacts = record_artifact(artifacts, 'HTML', folder, ...
        'SKIP', 'No final coverage objects were returned');
    return;
end

for i = 1:numel(coverageObjects)
    root = coverage_root(coverageObjects(i));
    fileName = sprintf('%02d_%s.html', i, safe_file_name(root));
    path = fullfile(folder, fileName);
    try
        report = cvhtml(path, coverageObjects(i), '-sRT=0');
        if isstruct(report) && isfield(report, 'fileName') && ...
                isfield(report, 'path')
            path = fullfile(char(report(1).path), char(report(1).fileName));
        end
        artifacts = record_artifact(artifacts, 'HTML', path, ...
            'OK', ['Coverage root: ' root]);
    catch ME
        artifacts = record_artifact(artifacts, 'HTML', path, ...
            'FAIL', ME.message);
    end
end
end

function write_summary_workbook(path, targets, iterations, coverage, ...
        expectedUpdates, workflowResult, workflowPlan, cfg, runId, ...
        runDirectory, artifacts)
if isfile(path)
    delete(path);
end

overview = { ...
    'Metric','Value'; ...
    'Run ID',runId; ...
    'Created At',timestamp_text(); ...
    'Initial Target Results',sum(targets.Run == "INITIAL"); ...
    'Final Target Results',sum(targets.Run == "FINAL"); ...
    'Final Passed',sum(targets.Run == "FINAL" & ...
        upper(targets.Outcome) == "PASSED"); ...
    'Final Failed',sum(targets.Run == "FINAL" & ...
        upper(targets.Outcome) == "FAILED"); ...
    'Coverage Metrics',height(coverage); ...
    'Coverage Threshold Enforcement','REPORT_ONLY'; ...
    'Artifact Failures',sum(artifacts.Status == "FAIL")};
writecell(overview, path, 'Sheet', 'Overview');
writetable(targets, path, 'Sheet', 'Targets');
writetable(iterations, path, 'Sheet', 'Iterations');
writetable(coverage, path, 'Sheet', 'Coverage');

if isempty(expectedUpdates) || width(expectedUpdates) == 0
    expectedUpdates = table("NONE", "No expected-value update rows", ...
        'VariableNames', {'Status','Message'});
end
writetable(expectedUpdates, path, 'Sheet', 'ExpectedUpdates');
writetable(workflowResult, path, 'Sheet', 'Workflow');

Key = ["RunId"; "RunDirectory"; "TopModel"; "ModelFile"; ...
    "TestFile"; "MATLABRelease"; "MATLABVersion"; ...
    "CoverageStructuralLevel"; "CoverageMetricSettings"; ...
    "CoverageIncludeReferencedModels"; "WorkflowPlanRows"];
Value = [string(runId); string(runDirectory); string(cfg.TopModel); ...
    string(cfg.ModelFile); string(cfg.TestFile); string(version('-release')); ...
    string(version()); string(cfg.CoverageStructuralLevel); ...
    string(cfg.CoverageMetricSettings); ...
    string(logical(cfg.CoverageIncludeReferencedModels)); ...
    string(height(workflowPlan))];
metadata = table(Key, Value);
writetable(metadata, path, 'Sheet', 'Metadata');
end

function manifest = build_manifest( ...
        runId, runDirectory, runInfo, cfg, artifacts)
status = char(st_report_status(artifacts.Status));
manifest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'Status', status, ...
    'RunDirectory', runDirectory, ...
    'StartedAt', runInfo.StartedAt, ...
    'CompletedAt', runInfo.CompletedAt, ...
    'ReportCreatedAt', timestamp_text(), ...
    'RerunPerformed', runInfo.RerunPerformed, ...
    'CoverageStructuralLevel', cfg.CoverageStructuralLevel, ...
    'CoverageMetricSettings', cfg.CoverageMetricSettings, ...
    'CoverageThresholdPolicy', 'REPORT_ONLY', ...
    'Artifacts', table2struct(artifacts));
end

function artifacts = record_artifact( ...
        artifacts, type, path, status, message)
artifacts(end+1,:) = {string(type), string(path), ...
    string(status), string(message)};
end

function [runId, folder] = create_run_directory(root)
if ~isfolder(root)
    mkdir(root);
end
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
uuid = char(java.util.UUID.randomUUID());
runId = [timestamp '_' uuid(1:8)];
folder = fullfile(root, runId);
mkdir(folder);
end

function write_json_atomic(path, value)
folder = fileparts(path);
if ~isfolder(folder)
    mkdir(folder);
end
temporary = [tempname(folder) '.json'];
cleanup = onCleanup(@() delete_quiet(temporary)); %#ok<NASGU>
fileId = fopen(temporary, 'w', 'n', 'UTF-8');
if fileId < 0
    error('simtest:ReportManifestWriteFailed', ...
        'Cannot create JSON file: %s', temporary);
end
fileCleanup = onCleanup(@() fclose_quiet(fileId));
fprintf(fileId, '%s\n', jsonencode(value, 'PrettyPrint', true));
clear fileCleanup;
[ok, message] = movefile(temporary, path, 'f');
if ~ok
    error('simtest:ReportManifestWriteFailed', ...
        'Cannot replace %s: %s', path, message);
end
end

function text = coverage_root(cvd)
text = 'coverage';
try
    text = char(cvd.test.rootPath);
catch
end
end

function text = safe_file_name(value)
text = regexprep(char(string(value)), '[^A-Za-z0-9_-]+', '_');
text = regexprep(text, '^_+|_+$', '');
if isempty(text)
    text = 'coverage';
end
if numel(text) > 80
    text = text(1:80);
end
end

function delete_quiet(path)
if isfile(path)
    delete(path);
end
end

function fclose_quiet(fileId)
if fileId >= 0
    fclose(fileId);
end
end

function text = timestamp_text()
text = char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss.SSS'));
end

function T = empty_artifact_table()
T = table(strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    'VariableNames', {'Type','Path','Status','Message'});
end

function T = empty_target_table()
T = table(strings(0,1), zeros(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), zeros(0,1), zeros(0,1), ...
    'VariableNames', {'Run','No','CUTName','CUTPath','TestCaseName', ...
     'Outcome','DurationSec','IterationCount'});
end

function T = empty_iteration_table()
T = table(strings(0,1), zeros(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), zeros(0,1), 'VariableNames', ...
    {'Run','No','CUTName','TestCaseName','IterationName','Outcome', ...
     'DurationSec'});
end

function T = empty_coverage_table()
T = table(strings(0,1), strings(0,1), zeros(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), strings(0,1), zeros(0,1), zeros(0,1), ...
    zeros(0,1), zeros(0,1), strings(0,1), strings(0,1), ...
    strings(0,1), 'VariableNames', ...
    {'Run','Level','No','CUTName','TestCaseName','IterationName', ...
     'CoverageRoot','SourceCoverageRoot','Checksum','Metric','Covered', ...
     'Total','Justified','Percentage','PercentageText','Status','Message'});
end
