function info = st_report_run_context(runContext)
%ST_REPORT_RUN_CONTEXT Validate and describe the initial/final result pair.

required = {'InitialResult','FinalResult','RerunPerformed', ...
    'ExpectedUpdateResult','StartedAt','CompletedAt'};
for i = 1:numel(required)
    if ~isfield(runContext, required{i})
        error('simtest:MissingRunResults', ...
            'Run context is missing %s.', required{i});
    end
end
if isempty(runContext.InitialResult) || isempty(runContext.FinalResult)
    error('simtest:MissingRunResults', ...
        'Initial and final ResultSet objects are required for reporting.');
end

info = struct( ...
    'InitialLabel', 'INITIAL', ...
    'FinalLabel', 'FINAL', ...
    'RerunPerformed', logical(runContext.RerunPerformed), ...
    'StartedAt', char(string(runContext.StartedAt)), ...
    'CompletedAt', char(string(runContext.CompletedAt)));
end
