function info = st_write_standalone_run_report( ...
        runId, runDirectory, targets, coverage, artifacts, cfg, ...
        startedAt, completedAt, reportMode, sourceState)
%ST_WRITE_STANDALONE_RUN_REPORT Write the standalone-model run index.

summaryPath = fullfile(runDirectory, 'TestSummary.xlsx');
manifestPath = fullfile(runDirectory, 'manifest.json');
if any(targets.Status == "FAIL")
    overallStatus = "FAIL";
elseif any(targets.Status == "WARN")
    overallStatus = "PASS_WITH_WARNINGS";
else
    overallStatus = "PASS";
end

try
    if isfile(summaryPath), delete(summaryPath); end
    overview = { ...
        'Metric','Value'; ...
        'Run ID',runId; ...
        'Execution Mode','PER_CUT'; ...
        'SUT Mode','EXPORTED_MODEL'; ...
        'Report Mode',reportMode; ...
        'Status',char(overallStatus); ...
        'Started At',startedAt; ...
        'Completed At',completedAt; ...
        'Target Count',height(targets); ...
        'Failed CUTs',sum(targets.Status == "FAIL"); ...
        'Warnings',sum(targets.Status == "WARN")};
    writecell(overview, summaryPath, 'Sheet', 'Overview');
    writetable(targets, summaryPath, 'Sheet', 'Targets');
    if isempty(coverage)
        writecell({'Message';'No coverage rows were collected'}, ...
            summaryPath, 'Sheet', 'Coverage');
    else
        writetable(coverage, summaryPath, 'Sheet', 'Coverage');
    end
    if isempty(artifacts)
        writecell({'Message';'No artifacts were collected'}, ...
            summaryPath, 'Sheet', 'Artifacts');
    else
        writetable(artifacts, summaryPath, 'Sheet', 'Artifacts');
    end
    sourceRows = struct2table(sourceState, 'AsArray', true);
    writetable(sourceRows, summaryPath, 'Sheet', 'SourceState');
catch ME
    overallStatus = "FAIL";
    st_log(cfg, 'ERROR', ...
        'Standalone root Excel report failed | %s: %s', ...
        ME.identifier, ME.message);
end

manifest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'ExecutionMode', 'PER_CUT', ...
    'SystemUnderTestMode', 'EXPORTED_MODEL', ...
    'ReportMode', char(string(reportMode)), ...
    'Status', char(overallStatus), ...
    'StartedAt', startedAt, ...
    'CompletedAt', completedAt, ...
    'RunDirectory', runDirectory, ...
    'Summary', summaryPath, ...
    'TestFile', fullfile(runDirectory, 'test_manager', ...
        'StandaloneHarnessTests.mldatx'), ...
    'TargetCount', height(targets), ...
    'FailedTargetCount', sum(targets.Status == "FAIL"), ...
    'SourceState', sourceState, ...
    'Targets', table2struct(targets), ...
    'Artifacts', table2struct(artifacts));
st_write_json_atomic(manifestPath, manifest);

latest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'Status', char(overallStatus), ...
    'UpdatedAt', completedAt);
st_write_json_atomic(cfg.StandaloneLatestPointer, latest);

info = struct( ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'Status', char(overallStatus), ...
    'TargetCount', height(targets), ...
    'FailedTargetCount', sum(targets.Status == "FAIL"));
end
