function info = st_write_per_cut_run_report( ...
        runId, runDirectory, targets, coverage, artifacts, cfg, ...
        startedAt, completedAt, reportMode, varargin)
%ST_WRITE_PER_CUT_RUN_REPORT Write the cross-CUT index and latest pointer.

p = inputParser;
addParameter(p, 'WriteExcel', true, ...
    @(x) islogical(x) && isscalar(x));
parse(p, varargin{:});
writeExcel = logical(p.Results.WriteExcel);

summaryPath = '';
if writeExcel
    summaryPath = fullfile(runDirectory, 'TestSummary.xlsx');
end
manifestPath = fullfile(runDirectory, 'manifest.json');

partialCount = count_partial_targets(targets);
if any(targets.Status == "FAIL")
    overallStatus = "FAIL";
elseif partialCount > 0
    % Some scenarios of a CUT produced no usable verify timing or could not
    % have their expected values updated. That is not a plain warning.
    overallStatus = "PARTIAL";
elseif any(targets.Status == "WARN")
    overallStatus = "PASS_WITH_WARNINGS";
else
    overallStatus = "PASS";
end

try
    if writeExcel && isfile(summaryPath)
        delete(summaryPath);
    end
    if writeExcel
        overview = { ...
            'Metric','Value'; ...
            'Run ID',runId; ...
            'Execution Mode','PER_CUT'; ...
            'Report Mode',reportMode; ...
            'Status',char(overallStatus); ...
            'Started At',startedAt; ...
            'Completed At',completedAt; ...
            'Target Count',height(targets); ...
            'Failed CUTs',sum(targets.Status == "FAIL"); ...
            'Partial CUTs',partialCount; ...
            'Warnings',sum(targets.Status == "WARN")};
        writecell(overview, summaryPath, 'Sheet', 'Overview');
        writetable(targets, summaryPath, 'Sheet', 'Targets');
        if ~isempty(coverage)
            writetable(coverage, summaryPath, 'Sheet', 'Coverage');
        else
            writecell({'Message'; 'No coverage rows were collected'}, ...
                summaryPath, 'Sheet', 'Coverage');
        end
        if ~isempty(artifacts)
            writetable(artifacts, summaryPath, 'Sheet', 'Artifacts');
        end
        Key = ["RunId";"RunDirectory";"TopModel";"TestFile"; ...
            "ExecutionMode";"ReportMode";"MATLABRelease";"MATLABVersion"];
        Value = [string(runId);string(runDirectory);string(cfg.TopModel); ...
            string(cfg.TestFile);"PER_CUT";string(reportMode); ...
            string(version('-release'));string(version())];
        writetable(table(Key, Value), summaryPath, 'Sheet', 'Metadata');
    end
catch ME
    overallStatus = "FAIL";
    artifacts(end+1,:) = {0, "ROOT", "EXCEL", string(summaryPath), ...
        "FAIL", string(ME.message)};
end

manifest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'ExecutionMode', 'PER_CUT', ...
    'ReportMode', char(string(reportMode)), ...
    'Status', char(overallStatus), ...
    'StartedAt', startedAt, ...
    'CompletedAt', completedAt, ...
    'RunDirectory', runDirectory, ...
    'Summary', summaryPath, ...
    'ExcelWritten', writeExcel, ...
    'TargetCount', height(targets), ...
    'FailedTargetCount', sum(targets.Status == "FAIL"), ...
    'PartialTargetCount', partialCount, ...
    'Targets', table2struct(targets), ...
    'Artifacts', table2struct(artifacts));
write_json_atomic(manifestPath, manifest);

latest = struct( ...
    'Version', 1, ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'ExcelWritten', writeExcel, ...
    'Status', char(overallStatus), ...
    'UpdatedAt', completedAt);
write_json_atomic(cfg.PerCutLatestPointer, latest);

info = struct( ...
    'RunId', runId, ...
    'RunDirectory', runDirectory, ...
    'Manifest', manifestPath, ...
    'Summary', summaryPath, ...
    'ExcelWritten', writeExcel, ...
    'Status', char(overallStatus), ...
    'TargetCount', height(targets), ...
    'FailedTargetCount', sum(targets.Status == "FAIL"), ...
    'PartialTargetCount', partialCount);
end


function total = count_partial_targets(targets)
%COUNT_PARTIAL_TARGETS Count CUTs whose scenarios only partly succeeded.

total = 0;
names = targets.Properties.VariableNames;
for column = ["VerifyTimingStatus", "ExpectedUpdateStatus"]
    if ~ismember(char(column), names)
        continue;
    end
    values = upper(string(targets.(char(column))));
    total = total + sum(values == "PARTIAL" | values == "FAIL");
end
end


function write_json_atomic(path, value)
folder = fileparts(path);
if ~isfolder(folder)
    mkdir(folder);
end
temporary = [tempname(folder) '.json'];
cleanup = onCleanup(@() delete_if_present(temporary)); %#ok<NASGU>
fileId = fopen(temporary, 'w', 'n', 'UTF-8');
if fileId < 0
    error('simtest:PerCutJsonWriteFailed', ...
        'Cannot open JSON output: %s', path);
end
fileCleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', jsonencode(value, 'PrettyPrint', true));
clear fileCleanup;
[moved, message] = movefile(temporary, path, 'f');
if ~moved
    error('simtest:PerCutJsonWriteFailed', ...
        'Cannot replace JSON output %s: %s', path, message);
end
end


function delete_if_present(path)
if isfile(path)
    delete(path);
end
end
