function tests = test_coverage_filters
%TEST_COVERAGE_FILTERS Unit/static checks for managed coverage filters.
tests = functiontests(localfunctions);
end


function testBlankModeDefaultsToOff(testCase)
[mode, action, rationale] = ...
    st_resolve_coverage_filter_settings([""; missing], ["EXCLUDE"; ""], ...
        ["ignored"; ""]);

verifyEqual(testCase, mode, ["OFF"; "OFF"]);
verifyEqual(testCase, action, [""; ""]);
verifyEqual(testCase, rationale, [""; ""]);
end


function testActiveSettingsAreNormalized(testCase)
[mode, action, rationale] = st_resolve_coverage_filter_settings( ...
    [" subsystem "; "all_content"], [" exclude "; "justify"], ...
    [" inactive cut "; "approved content"]);

verifyEqual(testCase, mode, ["SUBSYSTEM"; "ALL_CONTENT"]);
verifyEqual(testCase, action, ["EXCLUDE"; "JUSTIFY"]);
verifyEqual(testCase, rationale, ...
    ["inactive cut"; "approved content"]);
end


function testInvalidSettingsAreRejected(testCase)
verifyError(testCase, @() st_resolve_coverage_filter_settings( ...
    "BLOCK", "EXCLUDE", "reason"), ...
    'simtest:InvalidCoverageFilterMode');
verifyError(testCase, @() st_resolve_coverage_filter_settings( ...
    "SUBSYSTEM", "IGNORE", "reason"), ...
    'simtest:InvalidCoverageFilterAction');
verifyError(testCase, @() st_resolve_coverage_filter_settings( ...
    "ALL_CONTENT", "JUSTIFY", ""), ...
    'simtest:MissingCoverageFilterRationale');
end


function testGeneratedFiltersAreNeverPersisted(testCase)
% A generated filter is transient. Keeping one in the MLDATX file would make
% the run itself filtered, and the run has to collect coverage unfiltered.
root = st_project_root();
verifyFalse(testCase, isfile(fullfile(root, 'src', 'coverage', ...
    'st_coverage_filter_application_mode.m')));
verifyFalse(testCase, isfield(st_config(), 'CoverageFilterApplicationMode'));

preparation = fileread(fullfile(root, 'src', 'test_manager', ...
    'st_create_test_manager.m'));
verifyEmpty(testCase, regexp(preparation, ...
    'st_apply_test_case_coverage_filters', 'once'));
verifyEmpty(testCase, regexp(preparation, ...
    'st_prepare_coverage_filters', 'once'));
end


function testExistingFilterPolicyValidation(testCase)
cfg = st_config();
verifyEqual(testCase, cfg.CoverageFilterExistingPolicy, 'REPLACE');
verifyEqual(testCase, ...
    st_coverage_filter_existing_policy(' replace '), 'REPLACE');
verifyEqual(testCase, ...
    st_coverage_filter_existing_policy('merge'), 'MERGE');
verifyError(testCase, ...
    @() st_coverage_filter_existing_policy('REUSE'), ...
    'simtest:InvalidCoverageFilterExistingPolicy');
end


function testManagedFileIsStableAndRowSpecific(testCase)
cfg = struct('TopModel', 'Top', ...
    'CoverageFilterDir', fullfile(tempdir, 'managed_filters'));
No = [1; 2];
CUTPath = ["Top/CUT"; "Top/CUT"];
TestCaseName = ["TC"; "TC"];
rows = table(No, CUTPath, TestCaseName);

first = st_coverage_filter_file(rows(1,:), cfg);
verifyEqual(testCase, first, ...
    st_coverage_filter_file(rows(1,:), cfg));
verifyNotEqual(testCase, first, ...
    st_coverage_filter_file(rows(2,:), cfg));
verifyTrue(testCase, endsWith(string(first), ".cvf"));
end


function testApplicationCanIsolateAndRestoreExistingFilters(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'coverage', ...
    'st_apply_test_case_coverage_filters.m'));

verifyNotEmpty(testCase, regexp(source, ...
    'getCoverageSettings\(caseCells\{i\}\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'coverageObjects\{i\}\.CoverageFilterFilename', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'getCoverageSettings\(caseCells\{i\}\.Parent\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'originalFilters\{i\}\s*=\s*current', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'session\s*=\s*struct', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'Restore.*@restore_explicit', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'CoverageFilterRestoreMismatch', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'ExistingFilterPolicy', 'once'));
verifyGreaterThanOrEqual(testCase, numel(regexp(source, ...
    'fileCoverage\.CoverageFilterFilename\s*=\s*\.\.\.', 'match')), 2);
verifyGreaterThanOrEqual(testCase, numel(regexp(source, ...
    'suiteCoverageObjects\{[^}]+\}\.CoverageFilterFilename\s*=\s*\.\.\.', ...
    'match')), 2);
verifyNotEmpty(testCase, regexp(source, ...
    'IgnoredFilterCount', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'CoverageFilterReplacementRequiresRuntime', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'ApplyManagedFiltersDuringRun', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'RESULT_ONLY', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'FilterFile\(i\) = "DEFERRED"', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'creates its managed CVF from the[\s\S]*?after run\(tc\)', 'once'));
end


function testExecutionKeepsSingleTestFileRun(testCase)
% BATCH still executes the whole Test File in one run(tf). It no longer
% applies or restores a coverage filter around that run, so nothing may be
% left holding a filter session; testBatchRunnerNeitherFiltersNorRejectsFilters
% in test_per_cut_execution owns that contract.
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_generated_tests.m'));

verifyGreaterThanOrEqual(testCase, ...
    numel(regexp(source, 'run\(tf\)', 'match')), 1);
verifyEmpty(testCase, regexp(source, 'coverageFilterSession', 'once'));
end


function testGeneratedFilterTargetsDirectChildSubsystems(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'coverage', ...
    'st_generate_coverage_filter_file.m'));

verifyNotEmpty(testCase, regexp(source, ...
    'Simulink\.ID\.getSID\(char\(rulePaths\(i\)\)\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    ['CoverageFilterMode\s*==\s*"SUBSYSTEM"[\s\S]*?' ...
     'BlockSelectorType\.BlockInstance'], 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    ['else[\s\S]*?' ...
     'BlockSelectorType\.SubsystemAllContent'], 'once'));
verifyEmpty(testCase, regexp(source, ...
    'BlockSelectorType\.Subsystem\s*;', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'children\s*=\s*direct_blocks\(cutPath, ''SubSystem''\)', ...
    'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'outside\s*=\s*direct_blocks\(executionRoot, ''''\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''RuleCount'', numel\(rulePaths\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'savedFilter\s*=\s*slcoverage\.Filter\(path\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'numel\(savedRules\)\s*~=\s*numel\(rulePaths\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'CoverageExecutionCUTIdentificationFailed', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "childMode, 'none'", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "slcoverage.FilterMode.Exclude, 'none',", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "setFilterName\\(filterObj, char\\(targetRow.TestCaseName\\)\\)", ...
    'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "setFilterDescription\\(filterObj, 'none'\\)", 'once'));
verifyEmpty(testCase, regexp(source, 'Auto filter -', 'once'));
verifyEmpty(testCase, regexp(source, 'Automatically excluded', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'saveDirectoryCleanup\s*=\s*enter_writable_save_directory', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'writableDirectory\s*=\s*tempname\(tempdir\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "saveBase\s*=\s*fullfile\(writableDirectory, 'coverage_filter'\)", ...
    'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "copyfile\(saveFile, temporaryFile, 'f'\)", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'function restore_save_directory', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "addParameter\(p, 'ValidateSavedFilter', true", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'if validateSavedFilter[\s\S]*?validate_saved_filter', 'once'));
end

function testBoundaryModesAndActiveCombination(testCase)
verifyEqual(testCase, ...
    st_resolve_coverage_boundary_modes(["";"cut_only"]), ...
    ["OFF";"CUT_ONLY"]);
verifyError(testCase, @() st_resolve_coverage_boundary_modes("MODEL"), ...
    'simtest:InvalidCoverageBoundaryMode');
CoverageFilterMode = ["OFF";"SUBSYSTEM";"OFF"];
CoverageBoundaryMode = ["CUT_ONLY";"OFF";"OFF"];
targets = table(CoverageFilterMode, CoverageBoundaryMode);
verifyEqual(testCase, st_coverage_filter_active(targets), ...
    [true;true;false]);

legacyTargets = table(["OFF";"ALL_CONTENT"], ...
    'VariableNames', {'CoverageFilterMode'});
verifyEqual(testCase, st_coverage_filter_active(legacyTargets), ...
    [false;true]);
end


function testCharFilterPathIsNotSplitPerCharacter(testCase)
% st_collect_per_cut_results hands the appliers a char path, and
% string(value(:)) on char yields one string per character. That made the
% resolver look for a coverage filter named "D".
root = st_project_root();
files = ["st_apply_result_coverage_filters.m"; ...
    "st_apply_test_case_coverage_filters.m"];
for i = 1:numel(files)
    source = fileread(fullfile(root, 'src', 'coverage', char(files(i))));
    verifyNotEmpty(testCase, regexp(source, ...
        'function values = filter_string_column\(values\)', 'once'), ...
        char(files(i)));
    verifyNotEmpty(testCase, regexp(source, ...
        'values = string\(cellstr\(values\)\);', 'once'), char(files(i)));
    verifyNotEmpty(testCase, regexp(source, ...
        ['normalize_filter_values\(values?\)\s*\n\s*' ...
         '\w+ = filter_string_column'], 'once'), char(files(i)));
    verifyEmpty(testCase, regexp(source, ...
        'string\(p\.Results\.FilterFiles\(:\)\)', 'once'), char(files(i)));
end
resolver = fileread(fullfile(root, 'src', 'coverage', ...
    'st_apply_result_coverage_filters.m'));
verifyNotEmpty(testCase, regexp(resolver, ...
    ['function files = resolve_filter_files\(values\)\s*\n\s*' ...
     'files = filter_string_column'], 'once'));
end
