function tests = test_per_cut_execution
%TEST_PER_CUT_EXECUTION Pure/static checks for isolated CUT execution.
tests = functiontests(localfunctions);
end


function testAutoKeepsLegacyBatchWhenAllFiltersAreOff(testCase)
T = filter_table(["OFF"; "OFF"]);
verifyEqual(testCase, st_resolve_execution_mode('AUTO', T), 'BATCH');
verifyEqual(testCase, st_resolve_execution_mode('PER_CUT', T), 'PER_CUT');
end


function testAutoSelectsPerCutForEveryRowWhenOneFilterIsActive(testCase)
T = filter_table(["OFF"; "SUBSYSTEM"; "OFF"]);
verifyEqual(testCase, st_resolve_execution_mode('AUTO', T), 'PER_CUT');
end


function testBatchRejectsAnyActiveFilter(testCase)
T = filter_table(["OFF"; "ALL_CONTENT"]);
verifyError(testCase, @() st_resolve_execution_mode('BATCH', T), ...
    'simtest:BatchExecutionWithCoverageFilter');
end


function testTargetDirectoryIsStableAndCollisionResistant(testCase)
runDirectory = fullfile(tempdir, 'per-cut-run');
No = [1; 2];
CUTName = ["CUT A"; "CUT A"];
CUTPath = ["Top/CUT A"; "Top/CUT A"];
TestCaseName = ["TC"; "TC"];
T = table(No, CUTName, CUTPath, TestCaseName);

first = st_per_cut_target_directory(runDirectory, T(1,:));
verifyEqual(testCase, first, ...
    st_per_cut_target_directory(runDirectory, T(1,:)));
verifyNotEqual(testCase, first, ...
    st_per_cut_target_directory(runDirectory, T(2,:)));
verifyTrue(testCase, startsWith(string(first), ...
    string(fullfile(runDirectory, 'targets'))));
end


function testRunnerUsesIndependentTestCaseRunAndRestores(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_per_cut.m'));

verifyGreaterThanOrEqual(testCase, ...
    numel(regexp(source, 'run\(tc\)', 'match')), 1);
verifyNotEmpty(testCase, regexp(source, ...
    'for i = 1:n', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'session\.Restore\(\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'simtest:CoverageFilterRestoreFailed', 'once'));
orderedEvents = {'APPLY_START','RUN_INITIAL_START', ...
    'RESTORE_START','EXPORT_INITIAL_START','TARGET_COMPLETE'};
positions = zeros(numel(orderedEvents),1);
for i = 1:numel(orderedEvents)
    positions(i) = regexp(source, orderedEvents{i}, 'once');
end
verifyTrue(testCase, all(diff(positions) > 0));
verifyEmpty(testCase, regexp(source, ...
    'st_apply_run_test_case_scope', 'once'));
end


function testRunnerKeepsSeparateReportAndPointerPaths(testCase)
cfg = st_config();
verifyTrue(testCase, endsWith(string(cfg.PerCutRunRootDir), ...
    fullfile('result', 'per_cut_runs')));
verifyTrue(testCase, endsWith(string(cfg.PerCutLatestPointer), ...
    fullfile('result', 'per_cut_latest.json')));

root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_per_cut.m'));
verifyNotEmpty(testCase, regexp(source, ...
    'st_per_cut_coverage_filter_file', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    ['''ExistingFilterPolicy''[\s\S]*?' ...
     'existingFilterPolicy'], 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''ApplyManagedFiltersDuringRun'', true', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'ManagedFilterApplication\s*=\s*repmat\("DURING_RUN"', 'once'));
verifyEmpty(testCase, regexp(source, ...
    'appliedCoverage\s*=\s*getCoverageSettings', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''CoverageFilterExistingPolicy'', existingFilterPolicy', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''ManagedFilterApplication'', managedFilterApplication', 'once'));
verifyEmpty(testCase, regexp(source, ...
    'applied\.cvf', 'once'));
verifyEmpty(testCase, regexp(source, ...
    'st_apply_result_coverage_filters', 'once'));
runPosition = regexp(source, 'initialResult\s*=\s*run\(tc\)', 'once');
managedEventPosition = regexp(source, 'RESULT_FILTER_MANAGED', 'once');
verifyTrue(testCase, runPosition < managedEventPosition);
resultFilterSource = fileread(fullfile(root, 'src', 'coverage', ...
    'st_apply_result_coverage_filters.m'));
verifyNotEmpty(testCase, regexp(resultFilterSource, ...
    'coverageObjects\(i\)\.filter\s*=\s*propertyValue', 'once'));
verifyNotEmpty(testCase, regexp(resultFilterSource, ...
    'fileattrib\(located\)', 'once'));
verifyNotEmpty(testCase, regexp(resultFilterSource, ...
    'filter_sets_match\(filterFiles, actual\)', 'once'));
verifyNotEmpty(testCase, regexp(resultFilterSource, ...
    'filter_name_keys\(expected\)', 'once'));
verifyNotEmpty(testCase, regexp(resultFilterSource, ...
    'existing_filter_path\(candidate, true\)', 'once'));
verifyEmpty(testCase, regexp(resultFilterSource, ...
    'java\.io\.File', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''ResultLabel'', ''INITIAL''', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '''ResultLabel'', ''FINAL''', 'once'));
verifyGreaterThanOrEqual(testCase, numel(regexp(source, ...
    '''IncludePortableCoverageDetail'', true', 'match')), 2);
verifyNotEmpty(testCase, regexp(source, ...
    'PerCutInitialReportFailed', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'PerCutFinalReportFailed', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'CVFSHA256', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'stage=INITIAL \| filters=RESTORED', 'once'));
end


function testRunnerKeepsTestVerdictSeparateFromExecutionFailure(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_per_cut.m'));

verifyNotEmpty(testCase, regexp(source, ...
    'Status\(i\) = "WARN"[\s\S]*?final Test Case outcome is', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'TARGET_OUTCOME_NONPASS', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'non-passing outcome[\s\S]*?outcome=%s[\s\S]*?continuing', ...
    'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'format_nonpass_targets', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '%d CUT\(s\) did not pass: %s', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'The root report was incomplete', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'addParameter\(p, ''FailOnNonPass'', false', 'once'));
end


function testPerCutResultIncludesPortableCoverageArtifacts(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'reporting', ...
    'st_export_result_set_report.m'));

verifyNotEmpty(testCase, regexp(source, ...
    "addParameter\(p, 'IncludePortableCoverageDetail', false", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "fullfile\(coverageDirectory, 'detail'\)", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'cvsave\(basePath, coverageObjects\(i\)\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'coverage_integrity_snapshot\(resultObj\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'ResultCoverageChangedDuringExport', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "record_artifact\(artifacts, 'CVT'", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "record_artifact\(artifacts, 'CVF_COPY'", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'copyfile\(source, destination', 'once'));
exportDataPosition = regexp(source, ...
    'artifacts\s*=\s*export_coverage_data', 'once');
copyPosition = regexp(source, ...
    'artifacts\s*=\s*copy_coverage_filters', 'once');
resultPosition = regexp(source, ...
    'sltest\.testmanager\.exportResults', 'once');
verifyTrue(testCase, resultPosition < exportDataPosition && ...
    exportDataPosition < copyPosition);
verifyEmpty(testCase, regexp(source, ...
    'st_apply_result_coverage_filters\(resultObj, destinations, cfg\)', ...
    'once'));
end


function testPerCutFilterUsesTestCaseName(testCase)
directory = fullfile(tempdir, 'per-cut-filter');
row = table("SafeState_DTCOnly_14", ...
    'VariableNames', {'TestCaseName'});

path = st_per_cut_coverage_filter_file(directory, row);

verifyEqual(testCase, path, ...
    fullfile(directory, 'SafeState_DTCOnly_14.cvf'));
end


function testDirectTestCaseResultHierarchyUsesSharedCollector(testCase)
root = st_project_root();
collector = fileread(fullfile(root, 'src', 'reporting', ...
    'st_collect_test_case_results.m'));
verifyNotEmpty(testCase, regexp(collector, ...
    'caseResults\s*=\s*safe_test_case_results\(node\)', 'once'));
verifyNotEmpty(testCase, regexp(collector, ...
    'children\s*=\s*getTestCaseResults\(node\)', 'once'));

consumers = { ...
    fullfile(root, 'src', 'execution', ...
        'st_update_expected_from_results.m'), ...
    fullfile(root, 'src', 'reporting', ...
        'st_collect_test_result_summary.m'), ...
    fullfile(root, 'src', 'reporting', ...
        'st_collect_coverage_summary.m'), ...
    fullfile(root, 'src', 'sldv', ...
        'st_validate_sldv_verify_results.m')};
for i = 1:numel(consumers)
    source = fileread(consumers{i});
    verifyNotEmpty(testCase, regexp(source, ...
        'st_collect_test_case_results', 'once'));
end
end


function testPerCutWorkflowDefersSharedFilterGeneration(testCase)
root = st_project_root();
workflow = fileread(fullfile(root, 'src', 'workflow', ...
    'st_run_workflow.m'));
deferred = fileread(fullfile(root, 'src', 'coverage', ...
    'st_defer_coverage_filters_to_per_cut.m'));
verifyNotEmpty(testCase, regexp(workflow, ...
    'st_defer_coverage_filters_to_per_cut', 'once'));
verifyNotEmpty(testCase, regexp(workflow, ...
    '''DeferCoverageFilters'', true', 'once'));
verifyEmpty(testCase, regexp(deferred, ...
    'st_generate_coverage_filter_file', 'once'));
verifyNotEmpty(testCase, regexp(deferred, ...
    'Deferred to execution-local PER_CUT', 'once'));
end


function testLegacyRunnerRemainsBatchOnly(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_generated_tests.m'));
verifyNotEmpty(testCase, regexp(source, 'run\(tf\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'BatchExecutionWithCoverageFilter', 'once'));
end


function testFixtureDefinesThreeCoverageFilterCases(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'tests', 'fixtures', ...
    'st_build_verification_fixture.m'));
verifyNotEmpty(testCase, regexp(source, ...
    '"SUBSYSTEM"; "ALL_CONTENT"; repmat\("OFF"', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    '"JUSTIFY"; "EXCLUDE"', 'once'));
end


function T = filter_table(modes)
CoverageFilterMode = string(modes(:));
T = table(CoverageFilterMode);
end
