function tests = test_standalone_harness_execution
%TEST_STANDALONE_HARNESS_EXECUTION Static contracts for exported model SUTs.
tests = functiontests(localfunctions);
end

function testDefaultPreservesInternalHarnessMode(testCase)
cfg = st_config();
verifyEqual(testCase, cfg.SystemUnderTestMode, 'INTERNAL_HARNESS');
verifyTrue(testCase, endsWith(string(cfg.StandaloneRunRootDir), ...
    fullfile('result', 'standalone_runs')));
verifyTrue(testCase, endsWith(string(cfg.StandaloneLatestPointer), ...
    fullfile('result', 'standalone_latest.json')));
end

function testSystemUnderTestModeValidation(testCase)
verifyEqual(testCase, ...
    st_resolve_system_under_test_mode(' exported_model '), ...
    'EXPORTED_MODEL');
verifyEqual(testCase, ...
    st_resolve_system_under_test_mode('internal_harness'), ...
    'INTERNAL_HARNESS');
verifyError(testCase, ...
    @() st_resolve_system_under_test_mode('MIXED'), ...
    'simtest:InvalidSystemUnderTestMode');
end

function testExportedModelForcesPerCutAndRejectsBatch(testCase)
CoverageFilterMode = ["OFF";"OFF"];
T = table(CoverageFilterMode);
verifyEqual(testCase, st_resolve_execution_mode( ...
    'AUTO', T, 'EXPORTED_MODEL'), 'PER_CUT');
verifyEqual(testCase, st_resolve_execution_mode( ...
    'PER_CUT', T, 'EXPORTED_MODEL'), 'PER_CUT');
verifyError(testCase, @() st_resolve_execution_mode( ...
    'BATCH', T, 'EXPORTED_MODEL'), ...
    'simtest:StandaloneModelRequiresPerCut');
end

function testStandaloneModelNamesAreStableAndPhaseSpecific(testCase)
No = [1;2];
CUTName = ["Controller CUT";"Controller CUT"];
CUTPath = ["Top/A/Controller CUT";"Top/B/Controller CUT"];
HarnessName = ["Harness";"Harness"];
TestCaseName = ["TC";"TC"];
T = table(No, CUTName, CUTPath, HarnessName, TestCaseName);
first = st_standalone_model_name(T(1,:), 'INITIAL');
verifyEqual(testCase, first, ...
    st_standalone_model_name(T(1,:), 'INITIAL'));
verifyNotEqual(testCase, first, ...
    st_standalone_model_name(T(1,:), 'FINAL'));
verifyNotEqual(testCase, first, ...
    st_standalone_model_name(T(2,:), 'INITIAL'));
verifyTrue(testCase, isvarname(first));
verifyLessThanOrEqual(testCase, numel(first), namelengthmax);
end

function testWorkflowDefersRunLocalStages(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'workflow', ...
    'st_run_workflow.m'));
verifyNotEmpty(testCase, regexp(source, ...
    "'COVERAGE_FILTER','TEST_MANAGER','ALIGNMENT'", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'st_defer_standalone_execution_stage', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "'SystemUnderTestMode', systemUnderTestMode", 'once'));
end

function testStandaloneTestManagerUsesModelSUT(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'test_manager', ...
    'st_create_standalone_test_manager.m'));
required = { ...
    "'Model', modelInfo.ModelName", ...
    "'HarnessOwner', ''", ...
    "'HarnessName', ''", ...
    "'TestSequenceBlock', assessment", ...
    "collect_source_manual_filters", ...
    "filter_property_value(sourceFilters.Case{i})", ...
    "'SignalEditorScenario'", ...
    "'TestSequenceScenario'"};
for i = 1:numel(required)
    verifyNotEmpty(testCase, regexp(source, ...
        regexptranslate('escape', required{i}), 'once'));
end
end

function testStandaloneCoverageUsesExportedCUTPath(testCase)
root = st_project_root();
runner = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_from_exported_harnesses.m'));
collector = fileread(fullfile(root, 'src', 'reporting', ...
    'st_collect_coverage_summary.m'));
verifyNotEmpty(testCase, regexp(runner, ...
    "'CoverageTargetPaths', string\(modelInfo\.ExportedCUTPath\)", ...
    'once'));
verifyNotEmpty(testCase, regexp(collector, ...
    "addParameter\(p, 'CoverageTargetPaths'", 'once'));
end

function testCoverageTargetPathCountMustMatchTargets(testCase)
CUTPath = ["Top/A";"Top/B"];
T = table(CUTPath);
verifyError(testCase, @() st_collect_coverage_summary( ...
    [], T, 'TEST', 'CoverageTargetPaths', "Standalone/A"), ...
    'simtest:CoverageTargetPathCountMismatch');
end

function testStandaloneFiltersKeepCUTOutOfHarnessScope(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'coverage', ...
    'st_generate_standalone_coverage_filters.m'));
verifyNotEmpty(testCase, regexp(source, ...
    'allTopBlocks\(~strcmp\(allTopBlocks, cut\.ExportedPath\)\)', ...
    'once'));
verifyNotEmpty(testCase, regexp(source, 'SubsystemAllContent', 'once'));
verifyNotEmpty(testCase, regexp(source, 'BlockInstance', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "fullfile\(filterDirectory, 'harness-scope\.cvf'\)", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "fullfile\(filterDirectory, 'target-policy\.cvf'\)", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'targetRow\.CoverageFilterMode ~= "OFF"', 'once'));
verifyNotEmpty(testCase, regexp(source, 'SelectorTypes', 'once'));
verifyNotEmpty(testCase, regexp(source, 'Rationales', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "find_system\(cut\.ExportedPath[\s\S]*?'SearchDepth', 1", ...
    'once'));
end

function testExpectedUpdateReexportsAndRegeneratesFinalFilter(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_from_exported_harnesses.m'));
update = regexp(source, 'st_update_expected_from_results', 'once');
finalExport = regexp(source, ...
    "st_prepare_standalone_harness_model\([\s\S]*?'FINAL'", 'once');
finalFilter = regexp(source, ...
    "fullfile\(targetDirectory, 'final', 'filters'\)", 'once');
finalRun = regexp(source, 'RUN_FINAL_START', 'once');
verifyTrue(testCase, update < finalExport && ...
    finalExport < finalFilter && finalFilter < finalRun);
verifyGreaterThanOrEqual(testCase, numel(regexp(source, ...
    'restore_filter_session\(session\)', 'match')), 3);
end

function testFilterApplicationAcceptsMultipleManagedFiles(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'coverage', ...
    'st_apply_test_case_coverage_filters.m'));
verifyNotEmpty(testCase, regexp(source, ...
    "addParameter\(p, 'FilterFileSets'", 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'for filterIndex = 1:numel\(expectedFiles\)', 'once'));
end

function testResultsAndCleanupAreIsolated(testCase)
root = st_project_root();
runner = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_from_exported_harnesses.m'));
writer = fileread(fullfile(root, 'src', 'reporting', ...
    'st_write_standalone_run_report.m'));
cleanup = fileread(fullfile(root, 'src', 'maintenance', ...
    'st_cleanup_results.m'));
verifyNotEmpty(testCase, regexp(runner, ...
    'cfg\.StandaloneRunRootDir', 'once'));
verifyNotEmpty(testCase, regexp(writer, ...
    'cfg\.StandaloneLatestPointer', 'once'));
verifyNotEmpty(testCase, regexp(cleanup, 'STANDALONE_RUNS', 'once'));
verifyEmpty(testCase, regexp(writer, ...
    'cfg\.PerCutLatestPointer', 'once'));
verifyEmpty(testCase, regexp(writer, ...
    'cfg\.LatestReportPointer', 'once'));
end

function testStandaloneRunnerRestoresSourceSession(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'src', 'execution', ...
    'st_run_tests_from_exported_harnesses.m'));
verifyNotEmpty(testCase, regexp(source, 'capture_source_session', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'restore_source_session\(sourceSession, cfg\)', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'StandaloneUnsavedSourceModel', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    'StandaloneUnsavedHarness', 'once'));
end

function testStandaloneSelfCheckUsesSixBitContract(testCase)
root = st_project_root();
source = fileread(fullfile(root, 'diagnostics', 'matlab', ...
    'st_check_standalone_run.m'));
labels = {'S1:ROOT','S2:MODELS','S3:HARNESS_CVF', ...
    'S4:TARGET_CVF','S5:REEXPORT','S6:INTEGRITY'};
for i = 1:numel(labels)
    verifyNotEmpty(testCase, regexp(source, labels{i}, 'once'));
end
verifyNotEmpty(testCase, regexp(source, ...
    'STANDALONE-CHECK-v1 CODE=%s', 'once'));
verifyNotEmpty(testCase, regexp(source, ...
    "strcmp\(code, '111111'\)", 'once'));
end
