function tests = test_cut_path_single_assignment
tests = functiontests(localfunctions);
end


function testClaimedCandidateIsRemovedWithOwnerDetails(testCase)
claims = table( ...
    4, ...
    "Controller", ...
    "MODEL/BranchA/Controller", ...
    'VariableNames', {'ExcelRow','CUTName','CUTPath'});

[available, claimed] = ...
    st_partition_claimed_path_candidates( ...
        { ...
            'MODEL/BranchA/Controller'; ...
            'MODEL/BranchB/Controller'}, ...
        claims);

verifyEqual(testCase, available, {'MODEL/BranchB/Controller'});
verifyEqual(testCase, height(claimed), 1);
verifyEqual(testCase, claimed.CandidatePath, ...
    "MODEL/BranchA/Controller");
verifyEqual(testCase, claimed.ClaimedExcelRow, 4);
verifyEqual(testCase, claimed.ClaimedCUTName, "Controller");
end


function testAllCandidatesCanBeClaimed(testCase)
claims = table( ...
    [4; 7], ...
    ["Controller"; "Controller"], ...
    ["MODEL/A/Controller"; "MODEL/B/Controller"], ...
    'VariableNames', {'ExcelRow','CUTName','CUTPath'});

[available, claimed] = ...
    st_partition_claimed_path_candidates( ...
        ["MODEL/A/Controller"; "MODEL/B/Controller"], ...
        claims);

verifyEmpty(testCase, available);
verifyEqual(testCase, height(claimed), 2);
verifyEqual(testCase, claimed.ClaimedExcelRow, [4; 7]);
end


function testDuplicateExistingClaimsAreRejected(testCase)
claims = table( ...
    [4; 7], ...
    ["Controller A"; "Controller B"], ...
    ["MODEL/A/Controller"; "MODEL/A/Controller"], ...
    'VariableNames', {'ExcelRow','CUTName','CUTPath'});

verifyError(testCase, ...
    @() st_assert_unique_path_claims(claims), ...
    'st_assert_unique_path_claims:DuplicateCUTPath');
end


function testDistinctExistingClaimsAreAccepted(testCase)
claims = table( ...
    [4; 7], ...
    ["Controller A"; "Controller B"], ...
    ["MODEL/A/Controller"; "MODEL/B/Controller"], ...
    'VariableNames', {'ExcelRow','CUTName','CUTPath'});

st_assert_unique_path_claims(claims);
verifyTrue(testCase, true);
end


function testRowOrderContextDoesNotRemoveCandidate(testCase)
candidatePaths = { ...
    'MODEL/LaterCUT/Internal/Controller'; ...
    'MODEL/Other/Controller'};

resolvedAnchors = table( ...
    20, ...
    "LaterCUT", ...
    "MODEL/LaterCUT", ...
    'VariableNames', {'ExcelRow','CUTName','CUTPath'});

[ranking, excluded] = ...
    st_score_path_candidates( ...
        candidatePaths, ...
        10, ...
        resolvedAnchors, ...
        'MODEL', ...
        5);

verifyEqual(testCase, height(ranking), 2);
verifyEmpty(testCase, excluded);
verifyEqual(testCase, sort(ranking.CandidatePath), ...
    sort(string(candidatePaths)));
end


function testInvalidClaimTableIsRejected(testCase)
invalidClaims = table(1, "MODEL/A", ...
    'VariableNames', {'ExcelRow','CUTPath'});

verifyError(testCase, ...
    @() st_partition_claimed_path_candidates( ...
        {'MODEL/A'}, invalidClaims), ...
    'st_partition_claimed_path_candidates:InvalidClaims');
end
