function tests = test_sldv_template_selection
tests = functiontests(localfunctions);
end


function testIndexedTemplatesOverrideSinglePreferredScenario(testCase)
actual = st_select_sldv_template_names( ...
    {'TestCase_1','TestCase_2'}, ...
    'TestCase_1', ...
    {'SLDV Test Case 1','SLDV Test Case 2'}, ...
    [1; 2]);

verifyEqual(testCase, actual, {'TestCase_1';'TestCase_2'});
end


function testOriginalNamesMapDistinctTemplates(testCase)
actual = st_select_sldv_template_names( ...
    {'LowInput','HighInput'}, ...
    'UT_REQ_Controller_001', ...
    {'LowInput','HighInput'}, ...
    [1; 2]);

verifyEqual(testCase, actual, {'LowInput';'HighInput'});
end


function testInputScenarioIsSharedFallback(testCase)
actual = st_select_sldv_template_names( ...
    {'InputScenario','DiagnosticScenario'}, ...
    'UT_REQ_Controller_001', ...
    {'SLDV Test Case 1','SLDV Test Case 2'}, ...
    [1; 2]);

verifyEqual(testCase, actual, {'InputScenario';'InputScenario'});
end


function testAmbiguousTemplatesRemainUnselected(testCase)
actual = st_select_sldv_template_names( ...
    {'ScenarioA','ScenarioB'}, ...
    'UT_REQ_Controller_001', ...
    {'SLDV Test Case 1','SLDV Test Case 2'}, ...
    [1; 2]);

verifyEmpty(testCase, actual);
end
